package bg.registryagency.epzeu.pr.application.validator;

public enum ValidationParamKey {

    VALIDATE_FOR_SECTION_APPLICANT_DATA,
    VALIDATE_BIRTH_PLACE_WITH_PARAMS,
    VALIDATE_NAME_WITH_PARAMS,
    INDIVIDUAL,
    LEGAL_ENTITY,
    VALIDATE_REGISTRY_OFFICE_ON_THE_COUNTER_IS_CHECKED_PARAMS,
    APPLICATION_TYPE,
    VALIDATE_FOR_PREVIOUS_OWNERS,
    IS_SINGLE_PERSON,
    IS_SINGLE_DOCUMENT,
    VALIDATE_FOR_OWNERS,
    VALIDATE_NOMENCLATURE_CHANGES,
    PATH_TO_ERROR
}
