<?
$option = $this->element->getValue();
$id = $this->element->getAttribute('id');
$name = $this->element->getAttribute('name');
$checkedValue = $this->element->getCheckedValue();
$disabled = $this->element->getAttribute('disabled');
?>


<div class="custom-control custom-checkbox">
	<input class="custom-control-input" name="<?=$name?>" id="<?=$id?>" value="<?=$checkedValue?>" type="checkbox" <?= $this->element->getValue() ? ' checked="checked"' : ''?> <?=(!empty($disabled) ? 'disabled="disabled"' : '')?>>
	<label class="custom-control-label" for="<?=$id?>"><?=$this->translate($this->element->getLabel())?></label>
</div>

