<div id="modal-upload-files" class="modal fade" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
    <div class="modal-dialog <?=(!empty($classModalWindow) ? $classModalWindow : 'modal-lg')?>" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title"><?=$title?></h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" title="<?=$this->translate('GL_CLOSE_L')?>" class="close-preview-modal">×</span>
                </button>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">


                <div class="button-bar">
                    <button type="button" class="btn btn-secondary close-preview-modal" data-dismiss="modal"><?=$this->translate('GL_REFUSE_L')?></button>
                    <button type="button" class="btn btn-primary" disabled="disabled" id="save-files"><?=$this->translate('GL_SAVE_L')?></button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

$(document).on('click', '#save-files', function(){
	document.getElementById('iframe_content').contentWindow.saveIages();
});

</script>