<div id="modal-alert" class="modal fade" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">

            	<?
            	$class = 'alert alert-info';

            	if (!empty($classMessageBody))
            		$class = $classMessageBody;

            	echo '<div class="'.$class.'">';

            	echo '</div>';
            	?>

            </div>

            <div class="modal-footer">
				<div class="button-bar">
					<button type="button" class="btn btn-primary close-preview-modal" data-dismiss="modal"><?=(!empty($buttonRefuse) ? $buttonRefuse : $this->translate('GL_CLOSE_L'))?></button>
				</div>
			</div>
        </div>
    </div>
</div>