<?php
$this->headTitle('EP_TRANSLATION_APPLICATION_L');
?>

<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="<?=$this->url('home')?>"><?=$this->translate('GL_HOME_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_TRANSLATION_TRANSLATIONS_L')?></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_TRANSLATION_APPLICATION_L')?></li>
	</ol>
</nav>

<div class="page-title">
	<h2><?=$this->translate('EP_TRANSLATION_APPLICATION_L')?></h2>
</div>

<?=$this->partial('partial\language-drop-down.phtml')?>

<div class="card">

	<div class="card-header">
		<h3><?=$this->translate('GL_SEARCHING_L')?>
			<button class="system-button toggle-collapse" data-toggle="collapse" data-target="#collapsable-content">
				<i class="ui-icon ui-icon-chevron-up" aria-hidden="true"></i>
			</button>
		</h3>
	</div>

	<div id="collapsable-content" class="collapse show">
		<?
		$searchForm->setAttribute('action', $this->url('application_type_list', ['lang' => $params->fromRoute('lang')]));
		$searchForm->prepare();

		echo $this->form()->openTag($searchForm);
		?>


		<div class="card-body">
			<div class="row">
				<div class="col-xl-6">
					<div class="row">
						<div class="form-group col-sm-6 col-xl-3">
							<?=$this->formRow($searchForm->get('registerSelectId'))?>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="card-footer">
			<div class="button-bar">
				<a href="<?=$this->url(null, ['lang' => $lang])?>" class="btn btn-secondary"><?=$this->translate('GL_CLEAR_L')?></a>
				<button type="submit" class="btn btn-primary"><i class="ui-icon ui-icon-search ci-btn"></i>&nbsp;<?=$this->translate('GL_SEARCH_L')?></button>
			</div>
		</div>
		<?=$this->form()->closeTag();?>
	</div>
</div>

<div class="card">

	<div class="card-body">
	<?php if ($applicationTypeList->count()) { ?>

		<nav class="button-bar" aria-label="Page navigation">
			<div class="pagination-container">
			<div class="result-count"><?=$this->translate('GL_TOTAL_L')?>: <?=$totalCount?></div>
			<ul class="sync-pagination"></ul>
			</div>
		</nav>

		<div class="table-responsive">
			<table class="table table-bordered table-striped table-hover">
				<thead>
				<tr>
					<th><?=$this->translate('GL_REGISTER_L')?></th>
					<th><?=$this->translate('GL_APPLICATION_L')?></th>
					<th><?=$this->translate('GL_APPLICATION_L')?><span class="label-description"> (<?=$this->language()->getLanguagesName()?>)</span></th>
					<th><?=$this->translate('GL_ACTIONS_L')?></th>
				</tr>
				</thead>
				<tbody id="content">
					<?=$this->partial('nomenclature/nomenclature/application-type-list-partial.phtml')?>
				</tbody>
			</table>
		</div>


		<nav class="button-bar" aria-label="Page navigation">
			<div class="pagination-container">
			<div class="result-count"><?=$this->translate('GL_TOTAL_L')?>: <?=$totalCount?></div>
			<ul class="sync-pagination"></ul>
			</div>
		</nav>

		<?php
			$this->headScript()->appendFile($this->basePath('/js/jquery.twbsPagination.js'), 'text/javascript');
			$this->headScript()->appendFile($this->basePath('/js/paginator.js'), 'text/javascript');
		?>

		<script type="text/javascript">
			pagination('.sync-pagination', '#content', <?=$totalPages?>);
		</script>

	<?php } else { ?>
		<div class="alert alert-warning" role="alert">
			<?=$this->translate('EP_NOM_NO_LABELS_E')?>
		</div>
	<?php } ?>
	</div>
</div>

<script>

function toggleLanguageSelect() {

	var editableItemsArr = [];

	$('.edit-i18n-section').each(function() {
		if($(this).is(":visible")) {
			editableItemsArr.push(1);
		}
		else {
			editableItemsArr.push(0);
		}
	})

	if(jQuery.inArray(1, editableItemsArr) !== -1) {
		$('#language-select').attr("disabled", true);
	}
	else {
		$('#language-select').attr("disabled", false);
	}
}

function editNameI18n(appId) {

	$('.preview-i18n-'+appId).hide();
	$('.edit-i18n-'+appId).removeClass('d-none');

	$('#language-select').attr("disabled", true);
}

function cancelEditNameI18n(appId) {

	$("#edit-row-"+appId+" .invalid-feedback").remove();

	$('.edit-i18n-'+appId).addClass('d-none');
	$('.preview-i18n-'+appId).show();

	var codeValue = $('.edit-i18n-'+appId +' .code-value').html().trim();
	var oldValue = $('.preview-i18n-'+appId+' .name-value').html();

	if (typeof codeValue !== 'undefined') {
		var regExprCode = new RegExp(codeValue+" ");
		oldValue = oldValue.replace(regExprCode, "");
	}

	var oldValue = br2nl(oldValue);

	$('.edit-i18n-'+appId+' textarea[name="nameValue"]').val(oldValue);

	toggleLanguageSelect();
}

function saveNameChangesI18n(appId) {

	stripTags(appId);

	$("#edit-row-"+appId+" .invalid-feedback").remove();

	var nameValue = $('.edit-i18n-'+appId +' textarea[name="nameValue"]').val();

	var codeValue = $('.edit-i18n-'+appId +' .code-value').html().trim();

	ajaxRequest('', {'updateI18nApplicationTypeName': 1, 'id':appId, 'value': nameValue}, '#edit-name-'+appId, '.edit-i18n-language-'+appId);

	$('.preview-i18n-'+appId+' .name-value').html(codeValue ? codeValue + ' ' + nl2br(nameValue) : nl2br(nameValue));

	$('.edit-i18n-'+appId).addClass('d-none');

	$('.preview-i18n-'+appId).show();

	toggleLanguageSelect();
}

</script>

