<?php
$this->headTitle('EP_TRANSLATION_LABELS_L');
?>

<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="<?=$this->url('home')?>"><?=$this->translate('GL_HOME_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_TRANSLATION_TRANSLATIONS_L')?></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_TRANSLATION_LABELS_L')?></li>
	</ol>
</nav>


<div class="page-title">
	<h2><?=$this->translate('EP_TRANSLATION_LABELS_L')?></h2>
</div>

<?=$this->partial('partial\language-drop-down.phtml')?>

<div class="card">
	<div class="card-header">
		<h3><?=$this->translate('EP_NOM_SEARCH_LABELS_L')?>
			<button class="system-button toggle-collapse" data-toggle="collapse" data-target="#collapsable-content">
				<i class="ui-icon ui-icon-chevron-up" aria-hidden="true"></i>
			</button>
		</h3>
	</div>

	<div id="collapsable-content" class="collapse show">

		<?php
		$searchForm->setAttribute('action', $this->url('label_list_translate', ['lang' => $lang]));
		$searchForm->prepare();

		echo $this->form()->openTag($searchForm);
		?>

	<div class="card-body">
		<div class="row">
			<div class="form-group col-sm-12 col-md-6 col-lg-6 col-xl-4">
				<?=$this->formRow($searchForm->get('code'), null, true)?>
			</div>
			<div class="form-group col-sm-12 col-md-6 col-lg-6 col-xl-4">

				<? $searchForm->get('value')->setLabel($this->translate('GL_TEXT_BG_L')); ?>
				<?=$this->formRow($searchForm->get('value'))?>

			</div>
			<div class="form-group col-xl-4 align-bottom">
				<label class="control-label"></label>
				<?=$this->formRow($searchForm->get('withoutTranslation'), null, null, 'partial/checkbox')?>
			</div>
		</div>

	</div>

	<div class="card-footer">
		<div class="button-bar">
			<a href="<?=$this->url(null, ['lang' => $lang])?>" class="btn btn-secondary"><?=$this->translate('GL_CLEAR_L')?></a>
			<button type="submit" class="btn btn-primary"><i class="ui-icon ui-icon-search ci-btn"></i>&nbsp;<?=$this->translate('GL_SEARCH_L')?></button>
		</div>
	</div>
	<?=$this->form()->closeTag();?>
	</div>
</div>


<div class="card">

	<div class="card-body">
	<?php if ($labelList->count()) { ?>

		<nav class="button-bar" aria-label="Page navigation">
			<div class="pagination-container">
				<div class="result-count"><?=$this->translate('GL_TOTAL_L')?>: <?=$totalCount?></div>
				<ul class="sync-pagination"></ul>
			</div>
		</nav>

		<div class="table-responsive">
			<table class="table table-bordered table-striped table-hover">
				<thead>
				<tr>
					<th class="w-10"><?=$this->translate('GL_CODE_L')?></th>
					<th class="w-30"><?=$this->translate('GL_TEXT_L')?></th>

					<?php if ($lang) { ?>
					<th class="w-40"><?=$this->translate('GL_TEXT_L')?><span class="label-description"> (<?=$this->language()->getLanguagesName()?>)</span></th>
					<?php } ?>

					<th><?=$this->translate('GL_DESCRIPTION_L')?></th>
				</tr>
				</thead>
				<tbody id="content">
					<?=$this->partial('nomenclature/nomenclature/label-list-translate-partial.phtml')?>
				</tbody>
			</table>
		</div>

		<nav class="button-bar" aria-label="Page navigation">
			<div class="pagination-container">
			<div class="result-count"><?=$this->translate('GL_TOTAL_L')?>: <?=$totalCount?></div>
			<ul class="sync-pagination"></ul>
			</div>
		</nav>

		<?php
			$this->headScript()->appendFile($this->basePath('/js/jquery.twbsPagination.js'), 'text/javascript');
			$this->headScript()->appendFile($this->basePath('/js/paginator.js'), 'text/javascript');
		?>

		<script type="text/javascript">
			pagination('.sync-pagination', '#content', <?=$totalPages?>);
		</script>

	<?php } else { ?>
		<div class="alert alert-warning" role="alert">
			<?=$this->translate('EP_NOM_NO_LABELS_E')?>
		</div>
	<?php } ?>
	</div>
</div>

<script>

function toggleLanguageSelect() {

	var editableItemsArr = [];

	$('.edit-i18n-section').each(function() {
		if($(this).is(":visible")) {
			editableItemsArr.push(1);
		}
		else {
			editableItemsArr.push(0);
		}
	})

	if(jQuery.inArray(1, editableItemsArr) !== -1) {
		$('#language-select').attr("disabled", true);
	}
	else {
		$('#language-select').attr("disabled", false);
	}
}

function editLabelI18n(labelId) {

	$('.preview-i18n-'+labelId).hide();
	$('.edit-i18n-'+labelId).removeClass('d-none');

	$('#language-select').attr("disabled", true);
}

function cancelEditLabelI18n(labelId) {

	$("#edit-row-"+labelId+" .invalid-feedback").remove();

	$('.edit-i18n-'+labelId).addClass('d-none');
	$('.preview-i18n-'+labelId).show();

	var oldValue = $('.preview-i18n-'+labelId+' .label-value').html();
	var oldValue = br2nl(oldValue);

	$('.edit-i18n-'+labelId+' textarea[name="labelValue"]').val(oldValue);

	toggleLanguageSelect();
}

function saveLabelChangesI18n(labelId, code) {

	stripTags(labelId);

	$("#edit-row-"+labelId+" .invalid-feedback").remove();

	var labelValue = $('.edit-i18n-'+labelId +' textarea[name="labelValue"]').val();
	ajaxRequest('', {'updateI18nLabel': 1, 'id':labelId, 'value': labelValue, 'code': code}, '#edit-label-'+labelId, '.edit-i18n-language-'+labelId);

	$('.preview-i18n-'+labelId+' .label-value').html(labelValue);
	$('.edit-i18n-'+labelId).addClass('d-none');

	$('.preview-i18n-'+labelId).show();

	toggleLanguageSelect();
}

$(document).on('click', '.label-description-wrapper a', function(e){

	e.preventDefault();

	var url = this.attributes.href.nodeValue;

	url = url.replace(/{GL_EPZEU_PUBLIC_UI_URL}\/?/, '<?=$publicURL?>');

	if (url.search('<?=$publicURL?>CR/') != -1)
		url = url.replace('<?=$publicURL?>CR/', '<?=$publicURL?>CR/<?=$languageCode?>/');
	else if (url.search('<?=$publicURL?>PR/') != -1)
		url = url.replace('<?=$publicURL?>PR/', '<?=$publicURL?>PR/<?=$languageCode?>/');
	else
		url = url.replace('<?=$publicURL?>', '<?=$publicURL.$languageCode?>/');

	window.open(url, '_blank');
});
</script>