import { ObjectHelper, UrlHelper, appConfig } from "Cnsys.Core";
import { AsyncUIProps, BaseRouteProps, BaseRoutePropsExt, withAsyncFrame, withRouter } from "Cnsys.UI.React";
import { EPZEUBaseComponent, EPZEUPagination, IDataServiceProviderProps, withDataServiceProvider } from "EPZEU.Core";
import { action, observable, runInAction } from "mobx";
import { observer } from "mobx-react";
import * as moment from 'moment';
import * as React from "react";
import { DeedSummariesResult } from '../../Models/DeedSummariesResult';
import { BulstatDeedsSearchCriteria } from "../../Models/ModelsAutoGenerated";
import { BulstatDeedsSearchCriteriaValidator } from "../../Models/Validation/BulstatDeedsSearchCriteriaValidator";
import { DeedsDataService } from '../../Services/DeedsDataService';
import { BulstatDeedsResultUI } from "./BulstatDeedsResultUI";
import { BulstatDeedsSearchUI } from "./BulstatDeedsSearchUI";

interface BulstatDeedsUIProps extends BaseRouteProps<any>, AsyncUIProps, BaseRoutePropsExt, IDataServiceProviderProps {
}

@observer class BulstatDeedsUIImpl extends EPZEUBaseComponent<BulstatDeedsUIProps, null> {
    @observable private isAlreadySearched: boolean;
    @observable private currentSearchCriteria: BulstatDeedsSearchCriteria;
    @observable private searchCriteria: BulstatDeedsSearchCriteria;
    @observable private data: DeedSummariesResult;

    constructor(props: BulstatDeedsUIProps) {
        super(props);

        this.isAlreadySearched = false;
        this.currentSearchCriteria = undefined;

        this.searchInternal = this.searchInternal.bind(this);
        this.onSearchResult = this.onSearchResult.bind(this);
        this.onPageChange = this.onPageChange.bind(this);
        this.convertSearchCriteriaToUrlParams = this.convertSearchCriteriaToUrlParams.bind(this);

        if (ObjectHelper.isStringNullOrEmpty(this.props.location.search)) {
            this.searchCriteria = new BulstatDeedsSearchCriteria();
            this.searchCriteria.page = 1;
            this.searchCriteria.pageSize = appConfig.defaultPageSize;
        } else {
            this.searchCriteria = this.getSearchCriteriaFromUrl();
            this.searchCriteria.page = this.searchCriteria.page ? this.searchCriteria.page : 1;
            this.searchCriteria.pageSize = appConfig.defaultPageSize;

            this.props.registerAsyncOperation(this.searchInternal(this.searchCriteria));
        }
    }

    render(): JSX.Element {
        let dataResult: any = null;

        if ((!this.props.asyncErrorMessages || this.props.asyncErrorMessages.length == 0)) {
            if (this.isAlreadySearched && !this.data) {
                dataResult = (<div className="alert alert-info">{this.getResource('GL_NOT_FOUND_RESULTS_E')}</div>);
            }

            if (this.data) {
                dataResult = (
                    <>
                        <EPZEUPagination activePage={this.currentSearchCriteria.page} count={this.currentSearchCriteria.count} pagesCount={this.currentSearchCriteria.getPagesCount()} maxVisiblePage={10} size="sm" onSelect={this.onPageChange} aditionalCssClass="pagination-container--page-top" />
                        <BulstatDeedsResultUI {...this.bind(this.data, 'deed')} />
                        <EPZEUPagination activePage={this.currentSearchCriteria.page} count={this.currentSearchCriteria.count} pagesCount={this.currentSearchCriteria.getPagesCount()} maxVisiblePage={10} size="sm" onSelect={this.onPageChange} />
                    </>);
            }
        }

        return (
            <>
                {/* Вписвания, заличавания и обявявания */}
                <BulstatDeedsSearchUI onSearchCallback={this.onSearchResult} {...this.bind(this.searchCriteria, 'searchCriteria', [new BulstatDeedsSearchCriteriaValidator()])} />
                <br />
                {dataResult}
            </>);
    }

    @action private onSearchResult(): void {
        this.searchCriteria.page = 1;
        this.props.registerAsyncOperation(this.searchInternal(this.searchCriteria));
    }

    private onPageChange(page: any): void {
        this.currentSearchCriteria.page = page;
        this.props.registerAsyncOperation(this.searchInternal(this.currentSearchCriteria, false));
    }

    @action private searchInternal(criteria: BulstatDeedsSearchCriteria, newSearch: boolean = true): Promise<void> {
        let that = this;
        let srv = this.props.dataSrvProvider.getDataService<DeedsDataService>(DeedsDataService);
        let validator = new BulstatDeedsSearchCriteriaValidator();

        if (validator.validate(criteria)) {
            return srv.getBulstatDeeds(criteria).then(res => {
                runInAction(() => {
                    that.isAlreadySearched = true;
                    if (newSearch) {
                        that.currentSearchCriteria = criteria.clone();
                    }

                    if (res && res.length > 0) {
                        that.data = new DeedSummariesResult();
                        that.data.items = res;
                    } else {
                        that.data = undefined;
                    }

                    let urlParams = that.convertSearchCriteriaToUrlParams();
                    that.props.routerExt.changeParams(urlParams);
                });
            })
        }

        return Promise.resolve();
    }

    private getSearchCriteriaFromUrl(): BulstatDeedsSearchCriteria {
        let searchCriteria = new BulstatDeedsSearchCriteria();

        let page = UrlHelper.getUrlParameter('page');
        searchCriteria.page = !ObjectHelper.isStringNullOrEmpty(page) ? Number(page) : undefined;

        let count = UrlHelper.getUrlParameter('count');
        searchCriteria.count = !ObjectHelper.isStringNullOrEmpty(count) ? Number(count) : undefined;

        let fromDate = UrlHelper.getUrlParameter('fromDate');
        searchCriteria.fromDate = !ObjectHelper.isStringNullOrEmpty(fromDate) ? moment(new Date(fromDate)) : undefined;

        let toDate = UrlHelper.getUrlParameter('toDate');
        searchCriteria.toDate = !ObjectHelper.isStringNullOrEmpty(toDate) ? moment(new Date(toDate)) : undefined;

        searchCriteria.courtNumber = +UrlHelper.getUrlParameter('courtNumber');

        return searchCriteria;
    }

    private convertSearchCriteriaToUrlParams(): any {
        let urlParams: any = {};

        urlParams['page'] = this.currentSearchCriteria.page.toString();
        urlParams['pageSize'] = this.currentSearchCriteria.pageSize.toString();
        urlParams['count'] = this.currentSearchCriteria.count.toString();

        urlParams['fromDate'] = JSON.parse(JSON.stringify(this.currentSearchCriteria.fromDate));
        urlParams['toDate'] = JSON.parse(JSON.stringify(this.currentSearchCriteria.toDate));

        urlParams['courtNumber'] = this.currentSearchCriteria.courtNumber.toString();
        return urlParams;
    }
}

export const BulstatDeedsUI = withRouter(withDataServiceProvider(withAsyncFrame(BulstatDeedsUIImpl)));