

// Auto Generated Object
import * as moment from 'moment'
import { observable } from 'mobx'
import { TypeSystem, BaseDataModel } from 'Cnsys.Core'
import { ApplicationFormFieldsBase } from 'EPZEU.CR.Domain'
import { moduleContext } from '../../ModuleContext'
import * as fields from '../Fields/ModelsAutoGenerated'



@TypeSystem.typeDecorator('ApplicationFormVFieldsBase', moduleContext.moduleName)
export class ApplicationFormVFieldsBase extends ApplicationFormFieldsBase { 

    @observable private _draftDeedInfoList: DraftDeedInfo[] = null;
    
    @TypeSystem.propertyArrayDecorator(DraftDeedInfo ? DraftDeedInfo : moduleContext.moduleName + '.' + 'DraftDeedInfo')
    public set draftDeedInfoList(val: DraftDeedInfo[]){
        this._draftDeedInfoList = val;
    }
    
    public get draftDeedInfoList(): DraftDeedInfo[]{
        return this._draftDeedInfoList;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('DraftDeedInfo', moduleContext.moduleName)
export class DraftDeedInfo extends BaseDataModel { 

    @observable private _legalForm: number = null;
    
    @TypeSystem.propertyDecorator('number')
    public set legalForm(val: number){
        this._legalForm = val;
    }
    
    public get legalForm(): number{
        return this._legalForm;
    }
     

    @observable private _companyFullName: string = null;
    
    @TypeSystem.propertyDecorator('string')
    public set companyFullName(val: string){
        this._companyFullName = val;
    }
    
    public get companyFullName(): string{
        return this._companyFullName;
    }
     

    @observable private _companyName: string = null;
    
    @TypeSystem.propertyDecorator('string')
    public set companyName(val: string){
        this._companyName = val;
    }
    
    public get companyName(): string{
        return this._companyName;
    }
     

    @observable private _uic: string = null;
    
    @TypeSystem.propertyDecorator('string')
    public set uic(val: string){
        this._uic = val;
    }
    
    public get uic(): string{
        return this._uic;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('V1Fields', moduleContext.moduleName)
export class V1Fields extends ApplicationFormVFieldsBase { 

    @observable private _transferringTypeOfTradeEnterprise: fields.F600_TransferringTypeOfTradeEnterprise = null;
    
    @TypeSystem.propertyDecorator(fields.F600_TransferringTypeOfTradeEnterprise)
    public set transferringTypeOfTradeEnterprise(val: fields.F600_TransferringTypeOfTradeEnterprise){
        this._transferringTypeOfTradeEnterprise = val;
    }
    
    public get transferringTypeOfTradeEnterprise(): fields.F600_TransferringTypeOfTradeEnterprise{
        return this._transferringTypeOfTradeEnterprise;
    }
     

    @observable private _transferringEnterprise: fields.F601_TransferringEnterprise = null;
    
    @TypeSystem.propertyDecorator(fields.F601_TransferringEnterprise)
    public set transferringEnterprise(val: fields.F601_TransferringEnterprise){
        this._transferringEnterprise = val;
    }
    
    public get transferringEnterprise(): fields.F601_TransferringEnterprise{
        return this._transferringEnterprise;
    }
     

    @observable private _acquisitionEnterprises: fields.F602_AcquisitionEnterprises = null;
    
    @TypeSystem.propertyDecorator(fields.F602_AcquisitionEnterprises)
    public set acquisitionEnterprises(val: fields.F602_AcquisitionEnterprises){
        this._acquisitionEnterprises = val;
    }
    
    public get acquisitionEnterprises(): fields.F602_AcquisitionEnterprises{
        return this._acquisitionEnterprises;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('V21Fields', moduleContext.moduleName)
export class V21Fields extends ApplicationFormVFieldsBase { 

    @observable private _formOfTransforming701: fields.F701_FormOfTransforming701 = null;
    
    @TypeSystem.propertyDecorator(fields.F701_FormOfTransforming701)
    public set formOfTransforming701(val: fields.F701_FormOfTransforming701){
        this._formOfTransforming701 = val;
    }
    
    public get formOfTransforming701(): fields.F701_FormOfTransforming701{
        return this._formOfTransforming701;
    }
     

    @observable private _transformingCompanys: fields.F702_TransformingCompanys = null;
    
    @TypeSystem.propertyDecorator(fields.F702_TransformingCompanys)
    public set transformingCompanys(val: fields.F702_TransformingCompanys){
        this._transformingCompanys = val;
    }
    
    public get transformingCompanys(): fields.F702_TransformingCompanys{
        return this._transformingCompanys;
    }
     

    @observable private _successors703: fields.F703_Successors = null;
    
    @TypeSystem.propertyDecorator(fields.F703_Successors)
    public set successors703(val: fields.F703_Successors){
        this._successors703 = val;
    }
    
    public get successors703(): fields.F703_Successors{
        return this._successors703;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('V22Fields', moduleContext.moduleName)
export class V22Fields extends ApplicationFormVFieldsBase { 

    @observable private _formOfTransforming701: fields.F701_FormOfTransforming701 = null;
    
    @TypeSystem.propertyDecorator(fields.F701_FormOfTransforming701)
    public set formOfTransforming701(val: fields.F701_FormOfTransforming701){
        this._formOfTransforming701 = val;
    }
    
    public get formOfTransforming701(): fields.F701_FormOfTransforming701{
        return this._formOfTransforming701;
    }
     

    @observable private _transformingCompanys: fields.F702_TransformingCompanys = null;
    
    @TypeSystem.propertyDecorator(fields.F702_TransformingCompanys)
    public set transformingCompanys(val: fields.F702_TransformingCompanys){
        this._transformingCompanys = val;
    }
    
    public get transformingCompanys(): fields.F702_TransformingCompanys{
        return this._transformingCompanys;
    }
     

    @observable private _successors703: fields.F703_Successors = null;
    
    @TypeSystem.propertyDecorator(fields.F703_Successors)
    public set successors703(val: fields.F703_Successors){
        this._successors703 = val;
    }
    
    public get successors703(): fields.F703_Successors{
        return this._successors703;
    }
     

    @observable private _branches704: fields.F704_Branches704 = null;
    
    @TypeSystem.propertyDecorator(fields.F704_Branches704)
    public set branches704(val: fields.F704_Branches704){
        this._branches704 = val;
    }
    
    public get branches704(): fields.F704_Branches704{
        return this._branches704;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('V23Fields', moduleContext.moduleName)
export class V23Fields extends ApplicationFormVFieldsBase { 

    @observable private _stoppingEntry: fields.F705_StoppingEntry = null;
    
    @TypeSystem.propertyDecorator(fields.F705_StoppingEntry)
    public set stoppingEntry(val: fields.F705_StoppingEntry){
        this._stoppingEntry = val;
    }
    
    public get stoppingEntry(): fields.F705_StoppingEntry{
        return this._stoppingEntry;
    }
     

    @observable private _numberApplication: fields.F706_NumberApplication = null;
    
    @TypeSystem.propertyDecorator(fields.F706_NumberApplication)
    public set numberApplication(val: fields.F706_NumberApplication){
        this._numberApplication = val;
    }
    
    public get numberApplication(): fields.F706_NumberApplication{
        return this._numberApplication;
    }
     

    @observable private _transformingCompanys: fields.F702_TransformingCompanys = null;
    
    @TypeSystem.propertyDecorator(fields.F702_TransformingCompanys)
    public set transformingCompanys(val: fields.F702_TransformingCompanys){
        this._transformingCompanys = val;
    }
    
    public get transformingCompanys(): fields.F702_TransformingCompanys{
        return this._transformingCompanys;
    }
     

    @observable private _transformingCompanys2: fields.F702a_TransformingCompanys2 = null;
    
    @TypeSystem.propertyDecorator(fields.F702a_TransformingCompanys2)
    public set transformingCompanys2(val: fields.F702a_TransformingCompanys2){
        this._transformingCompanys2 = val;
    }
    
    public get transformingCompanys2(): fields.F702a_TransformingCompanys2{
        return this._transformingCompanys2;
    }
     

    @observable private _successors703: fields.F703_Successors = null;
    
    @TypeSystem.propertyDecorator(fields.F703_Successors)
    public set successors703(val: fields.F703_Successors){
        this._successors703 = val;
    }
    
    public get successors703(): fields.F703_Successors{
        return this._successors703;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('V24Fields', moduleContext.moduleName)
export class V24Fields extends ApplicationFormVFieldsBase { 

    @observable private _formOfTransforming701: fields.F701_FormOfTransforming701 = null;
    
    @TypeSystem.propertyDecorator(fields.F701_FormOfTransforming701)
    public set formOfTransforming701(val: fields.F701_FormOfTransforming701){
        this._formOfTransforming701 = val;
    }
    
    public get formOfTransforming701(): fields.F701_FormOfTransforming701{
        return this._formOfTransforming701;
    }
     

    @observable private _transformingCompanys2: fields.F702a_TransformingCompanys2 = null;
    
    @TypeSystem.propertyDecorator(fields.F702a_TransformingCompanys2)
    public set transformingCompanys2(val: fields.F702a_TransformingCompanys2){
        this._transformingCompanys2 = val;
    }
    
    public get transformingCompanys2(): fields.F702a_TransformingCompanys2{
        return this._transformingCompanys2;
    }
     

    @observable private _successors703: fields.F703_Successors = null;
    
    @TypeSystem.propertyDecorator(fields.F703_Successors)
    public set successors703(val: fields.F703_Successors){
        this._successors703 = val;
    }
    
    public get successors703(): fields.F703_Successors{
        return this._successors703;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('V25Fields', moduleContext.moduleName)
export class V25Fields extends ApplicationFormVFieldsBase { 

    @observable private _formOfTransforming701: fields.F701_FormOfTransforming701 = null;
    
    @TypeSystem.propertyDecorator(fields.F701_FormOfTransforming701)
    public set formOfTransforming701(val: fields.F701_FormOfTransforming701){
        this._formOfTransforming701 = val;
    }
    
    public get formOfTransforming701(): fields.F701_FormOfTransforming701{
        return this._formOfTransforming701;
    }
     

    @observable private _transformingNPOs: fields.F702b_TransformingNPOs = null;
    
    @TypeSystem.propertyDecorator(fields.F702b_TransformingNPOs)
    public set transformingNPOs(val: fields.F702b_TransformingNPOs){
        this._transformingNPOs = val;
    }
    
    public get transformingNPOs(): fields.F702b_TransformingNPOs{
        return this._transformingNPOs;
    }
     

    @observable private _successors703: fields.F703_Successors = null;
    
    @TypeSystem.propertyDecorator(fields.F703_Successors)
    public set successors703(val: fields.F703_Successors){
        this._successors703 = val;
    }
    
    public get successors703(): fields.F703_Successors{
        return this._successors703;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('V26Fields', moduleContext.moduleName)
export class V26Fields extends ApplicationFormVFieldsBase { 

    @observable private _formOfTransforming701: fields.F701_FormOfTransforming701 = null;
    
    @TypeSystem.propertyDecorator(fields.F701_FormOfTransforming701)
    public set formOfTransforming701(val: fields.F701_FormOfTransforming701){
        this._formOfTransforming701 = val;
    }
    
    public get formOfTransforming701(): fields.F701_FormOfTransforming701{
        return this._formOfTransforming701;
    }
     

    @observable private _transformingNPOs: fields.F702b_TransformingNPOs = null;
    
    @TypeSystem.propertyDecorator(fields.F702b_TransformingNPOs)
    public set transformingNPOs(val: fields.F702b_TransformingNPOs){
        this._transformingNPOs = val;
    }
    
    public get transformingNPOs(): fields.F702b_TransformingNPOs{
        return this._transformingNPOs;
    }
     

    @observable private _successors703: fields.F703_Successors = null;
    
    @TypeSystem.propertyDecorator(fields.F703_Successors)
    public set successors703(val: fields.F703_Successors){
        this._successors703 = val;
    }
    
    public get successors703(): fields.F703_Successors{
        return this._successors703;
    }
     

    @observable private _branches704: fields.F704_Branches704 = null;
    
    @TypeSystem.propertyDecorator(fields.F704_Branches704)
    public set branches704(val: fields.F704_Branches704){
        this._branches704 = val;
    }
    
    public get branches704(): fields.F704_Branches704{
        return this._branches704;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('V31Fields', moduleContext.moduleName)
export class V31Fields extends ApplicationFormVFieldsBase { 

    @observable private _formOfTransforming801: fields.F801_FormOfTransforming801 = null;
    
    @TypeSystem.propertyDecorator(fields.F801_FormOfTransforming801)
    public set formOfTransforming801(val: fields.F801_FormOfTransforming801){
        this._formOfTransforming801 = val;
    }
    
    public get formOfTransforming801(): fields.F801_FormOfTransforming801{
        return this._formOfTransforming801;
    }
     

    @observable private _reorganizeCoOperatives: fields.F802_ReorganizeCoOperatives = null;
    
    @TypeSystem.propertyDecorator(fields.F802_ReorganizeCoOperatives)
    public set reorganizeCoOperatives(val: fields.F802_ReorganizeCoOperatives){
        this._reorganizeCoOperatives = val;
    }
    
    public get reorganizeCoOperatives(): fields.F802_ReorganizeCoOperatives{
        return this._reorganizeCoOperatives;
    }
     

    @observable private _successors803: fields.F803_Successors803 = null;
    
    @TypeSystem.propertyDecorator(fields.F803_Successors803)
    public set successors803(val: fields.F803_Successors803){
        this._successors803 = val;
    }
    
    public get successors803(): fields.F803_Successors803{
        return this._successors803;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('V32Fields', moduleContext.moduleName)
export class V32Fields extends ApplicationFormVFieldsBase { 

    @observable private _formOfTransforming801: fields.F801_FormOfTransforming801 = null;
    
    @TypeSystem.propertyDecorator(fields.F801_FormOfTransforming801)
    public set formOfTransforming801(val: fields.F801_FormOfTransforming801){
        this._formOfTransforming801 = val;
    }
    
    public get formOfTransforming801(): fields.F801_FormOfTransforming801{
        return this._formOfTransforming801;
    }
     

    @observable private _reorganizeCoOperatives: fields.F802_ReorganizeCoOperatives = null;
    
    @TypeSystem.propertyDecorator(fields.F802_ReorganizeCoOperatives)
    public set reorganizeCoOperatives(val: fields.F802_ReorganizeCoOperatives){
        this._reorganizeCoOperatives = val;
    }
    
    public get reorganizeCoOperatives(): fields.F802_ReorganizeCoOperatives{
        return this._reorganizeCoOperatives;
    }
     

    @observable private _successors803: fields.F803_Successors803 = null;
    
    @TypeSystem.propertyDecorator(fields.F803_Successors803)
    public set successors803(val: fields.F803_Successors803){
        this._successors803 = val;
    }
    
    public get successors803(): fields.F803_Successors803{
        return this._successors803;
    }
     

    @observable private _branches804: fields.F804_ReorgBranches = null;
    
    @TypeSystem.propertyDecorator(fields.F804_ReorgBranches)
    public set branches804(val: fields.F804_ReorgBranches){
        this._branches804 = val;
    }
    
    public get branches804(): fields.F804_ReorgBranches{
        return this._branches804;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('V33Fields', moduleContext.moduleName)
export class V33Fields extends ApplicationFormVFieldsBase { 

    @observable private _formOfTransforming801a: fields.F801a_FormOfTransforming801a = null;
    
    @TypeSystem.propertyDecorator(fields.F801a_FormOfTransforming801a)
    public set formOfTransforming801a(val: fields.F801a_FormOfTransforming801a){
        this._formOfTransforming801a = val;
    }
    
    public get formOfTransforming801a(): fields.F801a_FormOfTransforming801a{
        return this._formOfTransforming801a;
    }
     

    @observable private _reorganizeCoOperatives2: fields.F802a_ReorganizeCoOperatives2 = null;
    
    @TypeSystem.propertyDecorator(fields.F802a_ReorganizeCoOperatives2)
    public set reorganizeCoOperatives2(val: fields.F802a_ReorganizeCoOperatives2){
        this._reorganizeCoOperatives2 = val;
    }
    
    public get reorganizeCoOperatives2(): fields.F802a_ReorganizeCoOperatives2{
        return this._reorganizeCoOperatives2;
    }
     

    @observable private _successors803: fields.F803_Successors803 = null;
    
    @TypeSystem.propertyDecorator(fields.F803_Successors803)
    public set successors803(val: fields.F803_Successors803){
        this._successors803 = val;
    }
    
    public get successors803(): fields.F803_Successors803{
        return this._successors803;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}






