<? $this->headTitle('EP_USR_ACC_L') ?>

<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="<?=$this->url('home')?>"><?=$this->translate('GL_HOME_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_USR_ACC_L')?></li>
	</ol>
</nav>

<div class="page-title">
	<h2><?=$this->translate('EP_USR_ACC_L')?></h2>
</div>

<div class="card">

	<?php
	$userForm->setAttribute('action', $this->url('user_profile', ['lang' => $lang]));
	$userForm->prepare();

	$userFieldset = $userForm->get('userFieldset');

	echo $this->form()->openTag($userForm);

	?>
	<div class="card-body">

		<div class="row">
			<div class="col-12">
				<?=$this->partial('partial/messages.phtml')?>

				<?=$this->formHidden($userFieldset->get('id'))?>

				<div class="row">

					<div class="col-lg-6 col-xl-4 form-group">
						<?=$this->formRow($userFieldset->get('cin'))?>
					</div>

					<div class="col-lg-6 col-xl-4 form-group">

						<?=$this->formRow($userFieldset->get('updatedOn')->setValue(
								$this->dateFormat(
								strtotime($userObj->getUpdatedOn()),
								IntlDateFormatter::MEDIUM, // date
								IntlDateFormatter::NONE, // time
								$this->plugin('translate')->getTranslator()->getLocale(),
								\Application\View\Helper\DateFormat::DATETIME
							)
						))?>
					</div>

				</div>
				<div class="row">

					<div class="col-lg-6 col-xl-4 form-group">
						<?=$this->formRow($userFieldset->get('username'))?>
					</div>

					<div class="col-lg-6 col-xl-4 form-group">
						<?=$this->formRow($userFieldset->get('email'))?>
					</div>

				</div>

				<div class="row">
					<div class="col-lg-4 form-group">
						<?=$this->formRow($userFieldset->get('firstName'))?>
					</div>

					<div class="col-lg-4 form-group">
						<?=$this->formRow($userFieldset->get('middleName'))?>
					</div>

					<div class="col-lg-4 form-group">
						<?=$this->formRow($userFieldset->get('familyName'))?>
					</div>
				</div>

				<div class="row">

					<div class="col-sm-12 col-lg-6 form-group">
						<label><?=$this->translate('EP_USR_00002_L')?></label>
						<?=$this->formRow($userFieldset->get('crBulletinAcceptance'), 'append', null, 'partial/checkbox')?>
						<?=$this->formRow($userFieldset->get('prBulletinAcceptance'), 'append', null, 'partial/checkbox')?>
					</div>

					<div class="col-sm-12 col-lg-6 form-group">
						<label><?=$this->translate('EP_USR_00013_L')?></label>
						<?=$this->formRow($userFieldset->get('crMessageAcceptance'), 'append', null, 'partial/checkbox')?>
						<?=$this->formRow($userFieldset->get('prMessageAcceptance'), 'append', null, 'partial/checkbox')?>
						<?=$this->formRow($userFieldset->get('epzeuMessageAcceptance'), 'append', null, 'partial/checkbox')?>


					</div>



				</div>

				<div class="row">
					<div class="col-sm-12">
						<div class="form-group form-inline">
						<?=$this->formRow($userFieldset->get('specialAccess'), 'append', null, 'partial/checkbox')?>
						</div>
					</div>
				</div>

				<fieldset id="special-access-section" style="display: none;">
					<legend><?=$this->translate('EP_USR_00007_L');?></legend>
					<div class="row">
						<div class="col-sm-12">
							<div class="alert alert-info">
							<?=$this->translate('EP_USR_00002_I');?>
							</div>
						</div>

						<div class="col-sm-12 col-lg-6 form-group">
							<?=$this->formRow($userFieldset->get('contactData'), null, true, "")?>
							<div class="help-text-inline"><?=$this->translate('EP_USR_00006_I')?></div>
						</div>

						<div class="col-sm-12 col-lg-6 form-group">
							<?=$this->formRow($userFieldset->get('organization'), null, true, "")?>
						</div>

						<div class="w-100"></div>

						<div class="col-sm-6">
							<label for="" class="required-field"><?=$this->translate('EP_USR_00008_L')?></label>
							<?=$this->partial('partial/uploader.phtml')?>
							<?=$this->formRow($userFieldset->get('files'))?>
						</div>


					</div>
				</fieldset>
			</div>
		</div>
	</div>

	<div class="card-footer">
		<div class="button-bar">
			<a href="<?=$this->url('home')?>" class="btn btn-secondary"><?=$this->translate('GL_REFUSE_L')?></a>
			<?=$this->formSubmit($userForm->get('submit'));?>
		</div>
	</div>

	<?=$this->form()->closeTag();?>

</div>



<? if (count($specialAccessArr)) { ?>
<div class="card">

	<div class="card-header">
		<h3><?=$this->translate('EP_USR_LIST_REQSPACC_L')?></h3>
	</div>

	<div class="card-body">
		<table class="table table-striped table-bordered">
				<tr>
					<th><?=$this->translate('EP_USR_REQUEST_DATA_L')?></th>
					<th><?=$this->translate('EP_USR_00008_L')?></th>
					<th><?=$this->translate('EP_USR_CONF_REJ_DATA_L')?></th>
					<th><?=$this->translate('GL_CONDITION_L')?></th>
				</tr>

			<?php foreach ($specialAccessArr as $specialAccess) { ?>
				<tr>
					<td>
					<?=$this->dateFormat(
						strtotime($specialAccess->getCreatedOn()),
					    IntlDateFormatter::MEDIUM, // date
					    IntlDateFormatter::NONE, // time
					    $this->plugin('translate')->getTranslator()->getLocale(),
						\Application\View\Helper\DateFormat::DATETIME
					)?>
					</td>

					<td>
						<?php if (isset($documentArray[$specialAccess->getRequestId()])) { ?>
							<?php foreach ($documentArray[$specialAccess->getRequestId()] as $file) { ?>
								<p><a href="<?=$this->url('special_access_document_download', ['lang' => $lang, 'documentId' => $file->getDocId()])?>"><?=$file->getName()?></a></p>
							<?php } ?>
						<?php } ?>
					</td>

					<td>
					<?=$this->dateFormat(
						strtotime($specialAccess->getProcessingDate()),
					    IntlDateFormatter::MEDIUM, // date
					    IntlDateFormatter::NONE, // time
					    $this->plugin('translate')->getTranslator()->getLocale(),
						\Application\View\Helper\DateFormat::DATETIME
					)?>
					</td>

					<td class="icons-td">
					<?php
					switch ($specialAccessStatusList[$specialAccess->getAccessStatus()]) {

						case 'EP_USR_SP_ACCESS_WAITING_L':
							?>
							<i class="ui-icon ui-icon-state-waiting" aria-hidden="true"></i>
							<?php
							break;

						case 'EP_USR_SP_ACCESS_APPROVED_L':
							?>
							<i class="ui-icon ui-icon-state-active" aria-hidden="true"></i>
							<?php
							break;

						case 'EP_USR_SP_ACCESS_DISAPPROVED_L':
							?>
							<i class="ui-icon ui-icon-state-canceled" aria-hidden="true"></i>
							<?php
							break;
					}
					?>
					<?=$this->translate($specialAccessStatusList[$specialAccess->getAccessStatus()])?>
					</td>
				</tr>
			<?} ?>
		</table>
	</div>
</div>
<?} ?>




<script>

$("#special-access").on('click', function(){
	this.checked ? $('#contact-label').addClass('required-field') : $('#contact-label').removeClass('required-field');
	this.checked ? $("#special-access-section").show() : $("#special-access-section").hide();
});

$(document).ready(function(){
	var specialAccess = document.getElementById("special-access").checked
	specialAccess ? $("#special-access-section").show() : $("#special-access-section").hide();
});
</script>