import { RecordValidator } from 'EPZEU.CR.Domain';
import { F001a_NumberNationalRegister } from '../ModelsAutoGenerated';

export class F001a_NumberNationalRegisterValidator extends RecordValidator<F001a_NumberNationalRegister> {
    constructor() {
        super();
    }

    public validateInternal(obj: F001a_NumberNationalRegister): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}