import { ApplicationFormTypes } from 'EPZEU.CR.Core';
import { RecordOperations, RecordValidator } from 'EPZEU.CR.Domain';
import { F006_SubjectOfActivity } from '../ModelsAutoGenerated';

export class F006_SubjectOfActivityValidator extends RecordValidator<F006_SubjectOfActivity> {
    constructor() {
        super();

        var that = this;       
        //полето е задължително за попълване, освен в изброените заявления, където не участва.
        this.ruleFor(m => m.text).notEmpty().when(m =>
            m.recordOperation != RecordOperations.Erase
            && (that.validationContext.appType != ApplicationFormTypes.A11 &&
                that.validationContext.appType != ApplicationFormTypes.A14 &&
                that.validationContext.appType != ApplicationFormTypes.A15 &&
                that.validationContext.appType != ApplicationFormTypes.A16 &&
                that.validationContext.appType != ApplicationFormTypes.A17 &&
                that.validationContext.appType != ApplicationFormTypes.A18))
            .withMessage(this.getMessage('GL_INPUT_FIELD_MUST_E'));
    }

    public validateInternal(obj: F006_SubjectOfActivity): boolean {

        if (this.validationContext.appType != ApplicationFormTypes.A11 &&
            this.validationContext.appType != ApplicationFormTypes.A14 &&
            this.validationContext.appType != ApplicationFormTypes.A15 &&
            this.validationContext.appType != ApplicationFormTypes.A16 &&
            this.validationContext.appType != ApplicationFormTypes.A17 &&
            this.validationContext.appType != ApplicationFormTypes.A18)
        {
            let isValid = super.validateInternal(obj);

            return isValid;
        } else {
            return true;
        }
    }
}