import { EPZEUBaseValidator } from 'EPZEU.Core';
import { IApplicationFormValidationContext, RecordOperations, ValidatorHelpers } from 'EPZEU.CR.Domain';
import { F007a_AssignedManagers } from '../ModelsAutoGenerated';
import { F007a0_AssignedManagerValidator } from './F007a0_AssignedManagerValidator';

export class F007a_AssignedManagersValidator extends EPZEUBaseValidator<F007a_AssignedManagers, IApplicationFormValidationContext> {
    constructor() {
        super();

        //managersList
        this.ruleFor(m => m.assignedManageList).setCollectionValidator(new F007a0_AssignedManagerValidator());
    }

    public validate(obj: F007a_AssignedManagers): boolean {
        let isValid = super.validate(obj);

        if (obj.assignedManageList.length > 1) {

            for (var i = 0; i < obj.assignedManageList.length; i++) {
                if (ValidatorHelpers.isObjectWithPersonEmpty(obj.assignedManageList[i], "subject")
                    && obj.assignedManageList[i].recordOperation != RecordOperations.Erase) {
                    obj.assignedManageList[i].clearErrors(true);
                    obj.assignedManageList[i].addError(this.getMessage('CR_APP_00063_E'));// Попълнете данните за полето или го изтрийте.
                    isValid = false;
                }
            }
        }

        //Грешката се визуалзира при добавяне на второ и следващо лице със същия идентификатор като на вече добавено лице
        if (ValidatorHelpers.isExistDublicateIndents(obj.assignedManageList, false, "CR_APP_00110_E")) // 
            isValid = false; 
        
        return isValid;
    }
}