import { IPersonValidationContext, PersonTypes, PersonWithCountyValidator, RecordValidator } from 'EPZEU.CR.Domain';
import { F0070_Manager } from '../ModelsAutoGenerated';

export class F0070_ManagerValidator extends RecordValidator<F0070_Manager> {
    constructor() {
        super();

        this.ruleFor(m => m.person).setValidator(new PersonWithCountyValidator());
    }

    public validateInternal(obj: F0070_Manager): boolean {
        let isValid = super.validateInternal(obj);        

        return isValid;
    }

    setValidationContext(validationContext: IPersonValidationContext): void {
        validationContext.personType = PersonTypes.Manager;

        super.setValidationContext(validationContext);
    }
}