import { ObjectHelper } from 'Cnsys.Core';
import { RecordValidator, ValidatorHelpers } from 'EPZEU.CR.Domain';
import { F016_TermsOfPartnership } from '../ModelsAutoGenerated';

export class F016_TermsOfPartnershipValidator extends RecordValidator<F016_TermsOfPartnership> {
    constructor() {
        super();

        let errMsg = this.getMessage('GL_INPUT_DATE_E');
        this.ruleFor(m => m.date).must(m => ValidatorHelpers.isValidDate(m.date)).withMessage(errMsg).when(m => !ObjectHelper.isStringNullOrEmpty(m.date));
    }

    public validateInternal(obj: F016_TermsOfPartnership): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}