import { EPZEUBaseValidator } from 'EPZEU.Core';
import { F017v_RestorationOfStatusInPublicBenefit } from '../ModelsAutoGenerated';

//Наследява EPZEUBaseValidator, а не RecordValidator-a, защото не искаме да се валидира при промяна за "празно или променено поле не може да бъде изтрито" - TRIR-5235
export class F017v_RestorationOfStatusInPublicBenefitValidator extends EPZEUBaseValidator<F017v_RestorationOfStatusInPublicBenefit, any> {
    constructor() {
        super();
    }

    public validate(obj: F017v_RestorationOfStatusInPublicBenefit): boolean {
        let isValid = super.validate(obj);

        return isValid;
    }
}