import { RecordValidator } from 'EPZEU.CR.Domain';
import { F025_SharePaymentResponsibility } from '../ModelsAutoGenerated';

export class F025_SharePaymentResponsibilityValidator extends RecordValidator<F025_SharePaymentResponsibility> {
    constructor() {
        super();

        this.ruleFor(m => m.text).matches('^\\s*\\d+(\\.\\d)*\\s*$|^\\s*\\d+(\\.\\d\\d)*\\s*$').withMessage(this.getMessage('GL_INPUT_VALUE_E'));
    }

    public validateInternal(obj: F025_SharePaymentResponsibility): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}