import { F025b_TotalAmountOfInitialPropertyContributions } from '../ModelsAutoGenerated';
import { RecordValidator, } from 'EPZEU.CR.Domain';
import { ObjectHelper } from 'Cnsys.Core';

export class F025b_TotalAmountOfInitialPropertyContributionsValidator extends RecordValidator<F025b_TotalAmountOfInitialPropertyContributions> {
    constructor() {
        super();

        this.ruleFor(m => m.text).matches('^\\s*\\d+(\\.\\d)*\\s*$|^\\s*\\d+(\\.\\d\\d)*\\s*$').withMessage(this.getMessage('GL_INPUT_VALUE_E')).when(m => !ObjectHelper.isStringNullOrEmpty(m.text));
    }

    public validateInternal(obj: F025b_TotalAmountOfInitialPropertyContributions): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}