import { RecordValidator } from 'EPZEU.CR.Domain';
import { F03111_SpecialConditionsForTransfer } from '../ModelsAutoGenerated';

export class F03111_SpecialConditionsForTransferValidator extends RecordValidator<F03111_SpecialConditionsForTransfer> {

    public validateInternal(obj: F03111_SpecialConditionsForTransfer): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}