import { RecordValidator } from 'EPZEU.CR.Domain';
import { F032_DepositedFunds } from '../ModelsAutoGenerated';

export class F032_DepositedFundsValidator extends RecordValidator<F032_DepositedFunds> {
    constructor() {
        super();

        this.ruleFor(m => m.text).matches('^\\s*\\d+(\\.\\d)*\\s*$|^\\s*\\d+(\\.\\d\\d)*\\s*$').withMessage(this.getMessage('GL_INPUT_VALUE_E'));
    }

    public validateInternal(obj: F032_DepositedFunds): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}