/* Data for the 'nom.s_application_types' table  (Records 1 - 93) */

INSERT INTO nom.s_application_types ("id", "app_type", "name", "register_id", "app_code", "url")
VALUES 
  (1, E'101', E'Заявление за вписване на обстоятелства относно едноличен търговец', 1, E'А1', E'/ApplicationProcesses/A1'),
  (2, E'102', E'Заявление за вписване на обстоятелства относно събирателно дружество', 1, E'А2', E'/ApplicationProcesses/A2'),
  (3, E'103', E'Заявление за вписване на обстоятелства относно командитно дружество', 1, E'А3', E'/ApplicationProcesses/A3'),
  (4, E'104', E'Заявление за вписване на обстоятелства относно дружество с ограничена отговорност', 1, E'А4', E'/ApplicationProcesses/A4'),
  (5, E'105', E'Заявление за вписване на обстоятелства относно акционерно дружество', 1, E'А5', E'/ApplicationProcesses/A5'),
  (6, E'106', E'Заявление за вписване на обстоятелства относно командитно дружество с акции', 1, E'А6', E'/ApplicationProcesses/A6'),
  (7, E'107', E'Заявление за вписване на обстоятелства относно кооперация', 1, E'А7', E'/ApplicationProcesses/A7'),
  (8, E'108', E'Заявление за вписване на обстоятелства относно клон на чуждестранен търговец', 1, E'А8', E'/ApplicationProcesses/A8'),
  (9, E'109', E'Заявление за вписване на обстоятелства относно прокура', 1, E'Б1', E'/ApplicationProcesses/B1'),
  (10, E'110', E'Заявление за вписване на обстоятелства относно клон', 1, E'Б2', E'/ApplicationProcesses/B2'),
  (11, E'111', E'Заявление за вписване на обстоятелства относно залог на дружествен дял', 1, E'Б3', E'/ApplicationProcesses/B3'),
  (12, E'112', E'Заявление за вписване на обстоятелства относно залог на търговско предприятие', 1, E'Б4', E'/ApplicationProcesses/B4'),
  (13, E'113', E'Заявление за вписване на обстоятелства относно запор върху дружествен дял', 1, E'Б5', E'/ApplicationProcesses/B5'),
  (14, E'114', E'Заявление за вписване на обстоятелства относно прекратяване и ликвидация', 1, E'Б6', E'/ApplicationProcesses/B6'),
  (15, E'116', E'Заявление за вписване на обстоятелства относно прехвърляне на търговско предприятие', 1, E'В1', E'/ApplicationProcesses/V1'),
  (16, E'119', E'Заявление за обявяване на актове', 1, E'Г1', E'/ApplicationProcesses/G1'),
  (17, E'120', E'Заявление за запазване на фирма/наименование', 1, E'Д1', E'/ApplicationProcesses/D1'),
  (18, E'121', E'Заявление за вписване на обстоятелства относно търговец, публично предприятие', 1, E'А9', E'/ApplicationProcesses/A9'),
  (19, E'123', E'Заявление за вписване на обстоятелства относно преобразуване на търговски дружества - разделяне и отделяне', 1, E'В22', E'/ApplicationProcesses/V22'),
  (20, E'122', E'Заявление за вписване на обстоятелства относно преобразуване на търговски дружества (без разделяне и отделяне)', 1, E'В21', E'/ApplicationProcesses/V21'),
  (21, E'124', E'Заявление за спиране на вписването при оспорване на преобразуването', 1, E'В23', E'/ApplicationProcesses/V23'),
  (22, E'125', E'Заявление за вписване на обстоятелства относно преустройство на кооперации (без разделяне и отделяне)', 1, E'В31', E'/ApplicationProcesses/V31'),
  (23, E'126', E'Заявление за вписване на обстоятелства относно преустройство на кооперации - разделяне и отделяне', 1, E'В32', E'/ApplicationProcesses/V32'),
  (24, E'128', E'Заявление за промяна на фирма след установено съвпадение при пререгистация', 1, E'АА', E'/ApplicationProcesses/AA'),
  (25, E'132', E'Заявление за издаване на удостоверение за законосъобразност', 1, E'Е1', E'/ApplicationProcesses/E1'),
  (26, E'133', E'Заявление за вписване на обстоятелства относно ЕОИИ', 1, E'А10', E'/ApplicationProcesses/A10'),
  (27, E'134', E'Заявление за вписване на обстоятелства относно поделение в Република България на ЕОИИ със седалище в друга държава членка', 1, E'А11', E'/ApplicationProcesses/A11'),
  (28, E'135', E'Заявление за вписване на обстоятелства относно европейско дружество', 1, E'А12', E'/ApplicationProcesses/A12'),
  (29, E'136', E'Заявление за вписване на обстоятелства относно европейско кооперативно дружество', 1, E'А13', E'/ApplicationProcesses/A13'),
  (30, E'137', E'Заявление за вписване на обстоятелства относно преобразуване с участие на дружества от държави-членки на ЕС', 1, E'В24', E'/ApplicationProcesses/V24'),
  (31, E'138', E'Заявление за вписване на обстоятелства относно преобразуване на европейско кооперативно дружество в кооперация', 1, E'В33', E'/ApplicationProcesses/V33'),
  (32, E'139', E'Заявление за отстраняване на нередовности', 1, E'Ж1', E'/ApplicationProcesses/J1'),
  (33, E'140', E'Заявление за обявяване на годишни финансови отчети', 1, E'Г2', E'/ApplicationProcesses/G2'),
  (34, E'154', E'Заявление за вписване на обстоятелства относно дружество, регистрирано в юрисдикция с преференциален данъчен режим', 1, E'А14', E'/ApplicationProcesses/A14'),
  (35, E'155', E'Заявление за вписване на обстоятелства относно действителни собственици', 1, E'Б7', E'/ApplicationProcesses/B7'),
  (36, E'156', E'Заявление за вписване на обстоятелства относно сдружение', 1, E'А15', E'/ApplicationProcesses/A15'),
  (37, E'157', E'Заявление за вписване на обстоятелства относно фондация', 1, E'А16', E'/ApplicationProcesses/A16'),
  (38, E'158', E'Заявление за вписване на обстоятелства относно народно читалище', 1, E'А17', E'/ApplicationProcesses/A17'),
  (39, E'159', E'Заявление за вписване на обстоятелства относно клон на ЧЮЛНЦ', 1, E'А18', E'/ApplicationProcesses/A18'),
  (40, E'401', E'Искане за изправяне на грешки и непълноти', 1, NULL, E'/ApplicationProcesses/RequestForCorrection'),
  (41, E'1000', E'Подаване на жалба срещу отказ', 1, NULL, E'/ApplicationProcesses/Complaint'),
  (42, E'1201', E'Акт на съда по искова молба за оспорване на преобразуването', 1, NULL, E'/ApplicationProcesses/ActOfContestation'),
  (43, E'43', E'Заявление за издаване на удостоверение за лице от Имотен регистър', 2, NULL, E'/ApplicationProcesses/ApplicationForCertificateForPerson'),
  (44, E'44', E'Заявление за справка чрез отдалечен достъп за документ от Имотен регистър', 2, NULL, E'/ApplicationProcesses/RequestForReportForDocument'),
  (45, E'45', E'Заявление за справка чрез отдалечен достъп за електронна партида на имот от Имотен регистър', 2, NULL, E'/ApplicationProcesses/RequestForReportForAccountProperty'),
  (46, E'46', E'Заявление за справка чрез отдалечен достъп за лице от Имотен регистър за избрана служба по вписвания', 2, NULL, E'/ApplicationProcesses/RequestForReportForPerson'),
  (47, E'601', E'Искане за назначаване на вещи лица, проверител, контрольор или регистриран одитор', 1, NULL, E'/ApplicationProcesses/AppointingExpert'),
  (50, E'606', E'Декларация-съгласие', 1, NULL, E'/ApplicationProcesses/AppointingDeclaration'),
  (51, E'607', E'Доклад и експертиза', 1, NULL, E'/ApplicationProcesses/AppointingReportAndExamination'),
  (52, E'608', E'Искане за корекция на назначенията', 1, NULL, E'/ApplicationProcesses/AppointingRequestForCorrection'),
  (53, E'611', E'Искане за определяне на възнаграждение на контрольор', 1, NULL, E'/ApplicationProcesses/AppointingControllerReward'),
  (54, E'610', E'Искане за освобождаване на депозит', 1, NULL, E'/ApplicationProcesses/AppointingReleaseDeposit'),
  (55, E'603', E'Искане за промяна на съответното лице', 1, NULL, E'/ApplicationProcesses/AppointingChangeRequest'),
  (56, E'602', E'Невъзможност на лицето', 1, NULL, E'/ApplicationProcesses/ReleaseAppointingExpert'),
  (57, E'605', E'Приемане на депозит', 1, NULL, E'/ApplicationProcesses/AppointingPaidDeposit'),
  (58, E'612', E'Становище по искането за промяна на лицето', 1, NULL, E'/ApplicationProcesses/AttitudeOfChangeRequest'),
  (59, E'615', E'Уведомление за липса на средства', 1, NULL, E'/ApplicationProcesses/NotificationOfLackOfMeans'),
  (60, E'613', E'Уведомление за смяна на адреса за изпращане и кореспонденция', 1, NULL, E'/ApplicationProcesses/AppointingContactAddressChange'),
  (61, E'609', E'Уведомление, че вещото лице не може да изготви експертизата в срок', 1, NULL, E'/ApplicationProcesses/NotificationOfExaminationImpossibility'),
  (62, E'62', E'Заявление за справка чрез отдалечен достъп за имот от Имотен регистър', 2, NULL, E'/ApplicationProcesses/RequestForReportForProperty'),
  (64, E'901', E'Удостоверение за запазена фирма/наименование', 1, NULL, E'/ApplicationProcesses/CertificateForReserveFirm'),
  (65, E'160', E'Заявление за обявяване на декларация по чл. 38, ал. 9, т. 2 от ЗСч', 1, E'Г3', E'/ApplicationProcesses/G3'),
  (66, E'1401', E'Удостоверение за актуално състояние', 1, NULL, E'/ApplicationProcesses/ActualStateCertificate'),
  (67, E'1501', E'Удостоверение за вписвания за определен период', 1, NULL, E'/ApplicationProcesses/EntryByPeriodCertificate'),
  (68, E'1601', E'Удостоверение за обявявания за определен период', 1, NULL, E'/ApplicationProcesses/PublicationByPeriodCertificate'),
  (69, E'1701', E'Удостоверение за вписано обстоятелство', 1, NULL, E'/ApplicationProcesses/EnteredCircumstancesCertificate'),
  (70, E'1801', E'Удостоверение за обявяване или копие от обявен акт', 1, NULL, E'/ApplicationProcesses/ActOrCopyOfActCertificate'),
  (71, E'1901', E'Удостоверение за липса на вписано обстоятелство или обявен акт в търговския регистър', 1, NULL, E'/ApplicationProcesses/MissingActsCertificate'),
  (73, E'73', E'Заявление за издаване на удостоверение за имот от Имотен регистър', 2, NULL, E'/ApplicationProcesses/ApplicationForCertificateForProperty'),
  (74, E'74', E'Заявление за издаване на удостоверение за лице от Имотен регистър за определен период', 2, NULL, E'/ApplicationProcesses/ApplicationForCertificateForPeriodForPerson'),
  (75, E'75', E'Заявление за издаване на заверен препис от акт, вписан в Имотен регистър', 2, NULL, E'/ApplicationProcesses/ApplicationForCertifiedCopy'),
  (76, E'76', E'Заявление за издаване на незаверен препис от акт, вписан в Имотен регистър', 2, NULL, E'/ApplicationProcesses/ApplicationForNotCertifiedCopy'),
  (77, E'77', E'Заявление за издаване на удостоверение за имот от Имотен регистър за определен период', 2, NULL, E'/ApplicationProcesses/ApplicationForCertificateForPeriodForProperty'),
  (78, E'78', E'Заявление за деклариране на предстояща сделка с недвижим имот в Имотен регистър', 2, NULL, E'/ApplicationProcesses/ApplicationForDeclarationOfUpcomingDealWithProperty'),
  (80, E'10000', E'Уведомления за грешка при сканиране', 1, NULL, E'/ApplicationProcesses/InitialCommunication'),
  (81, E'81', E'Заявление за справка чрез отдалечен достъп за лице от Имотен регистър за всички служби по вписвания', 2, NULL, E'/ApplicationProcesses/RequestForReportForPersonInAllRegistryOffices'),
  (82, E'161', E'Заявление за вписване на обстоятелства относно преобразуване на сдружения, фондации и читалища (без разделяне и отделяне)', 1, E'В25', E'/ApplicationProcesses/V25'),
  (83, E'162', E'Заявление за вписване на обстоятелства относно преобразуване на сдружения, фондации и читалища - разделяне и отделяне', 1, E'В26', E'/ApplicationProcesses/V26'),
  (86, E'301', E'Акт за оповестяване', 1, NULL, NULL),
  (87, E'302', E'Служебна пререгистрация на клон', 1, NULL, NULL),
  (88, E'303', E'Уведомление от регистри на други държави', 1, NULL, NULL),
  (89, E'304', E'Уведомление от системата за взаимно свързване на регистрите относно клон', 1, NULL, NULL),
  (90, E'305', E'Уведомление от системата за взаимно свързване на регистрите относно преобразуване', 1, NULL, NULL),
  (91, E'402', E'Самосезиране', 1, NULL, NULL),
  (92, E'403', E'Сезиране при назначение', 1, NULL, NULL),
  (93, E'501', E'Допълнителна задача след вписване по партида', 1, NULL, NULL),
  (94, E'701', E'Искане за издаване на карта', 1, NULL, NULL),
  (95, E'801', E'Искане за съгласие на ликвидатор', 1, NULL, NULL),
  (96, E'1101', E'Разпореждане на съда за доокомплектоване', 1, NULL, NULL),
  (97, E'1301', E'Акт на съда по несъстоятелност', 1, NULL, NULL),
  (98, E'2001', E'Копие от документ, въз основа на който е извършено вписване или заличаване', 1, NULL, NULL),
  (99, E'2101', E'Служебна пререгистрация по УАС', 1, NULL, NULL),
  (100, E'2102', E'Удостоверение за актуално състояние на ЮЛНЦ, издадено от съда', 1, NULL, NULL);