import { BaseProps } from "Cnsys.UI.React";
import { EPZEUBaseComponent } from "EPZEU.Core";
import { observer } from "mobx-react";
import * as moment from 'moment';
import * as React from "react";
import { ProtectedRightsCompanyInfo } from "../../Models/ModelsAutoGenerated";
import { RightsForCompanyResult } from "../../Models/RightsForCompanyResult";

interface RightsForCompanyResultUIProps extends BaseProps {
}

@observer export class RightsForCompanyResultUI extends EPZEUBaseComponent<RightsForCompanyResultUIProps, RightsForCompanyResult> {
    constructor(props: RightsForCompanyResultUIProps) {
        super(props);
    }

    render(): JSX.Element {
        if (!this.model || !this.model.items || this.model.items.length == 0) return null;

        return (<div className="table-responsive-block">
            <table className="table table-borderless table-striped table-hover">
                <thead>
                    <tr>
                        <th style={{ width: "35%" }}>{this.getResource('CR_GL_COMPANY_NAME_L')}</th>
                        <th style={{ width: "25%" }}>{this.getResource('CR_GL_FIND_IN_L')}</th>
                        <th style={{ width: "25%" }}>{this.getResource('CR_GL_COMPANY_RIGHTS_L')}</th>
                        <th style={{ width: "15%" }}>{this.getResource('CR_GL_END_DATE_PROTECTION_L')}</th>
                    </tr>
                </thead>
                <tbody>
                    {this.model.items.map((item: ProtectedRightsCompanyInfo, idx: number) => {
                        return (
                            <tr key={`${item.companyName}_${item.legalFormName}_${idx}`}>
                                <td>
                                    <p className="field-text"><b>{item.companyName}</b></p>
                                </td>
                                <td>
                                    <span className="field-title field-title--preview d-sm-none">{this.getResource('CR_GL_FIND_IN_L')}:</span>
                                    <p className="field-text">{item.foundIn}</p>
                                </td>
                                <td>
                                    <span className="field-title field-title--preview d-sm-none">{this.getResource('CR_GL_COMPANY_RIGHTS_L')}:</span>
                                    <p className="field-text">{item.personPosition}</p>
                                </td>
                                <td>
                                    <span className="field-title field-title--preview d-sm-none">{this.getResource('CR_GL_END_DATE_PROTECTION_L')}:</span>
                                    <p className="field-text">{this.dateDisplayFor(item.activeTo, `DD.MM.YYYY ${this.getResource('GL_YEAR_ABBREVIATION_L')} HH:mm:ss`)}</p>
                                </td>
                            </tr>)
                    })
                    }
                </tbody>
            </table>
        </div>);
    }
}