using EPZEU.CR.Domain.ApplicationForms;
using EPZEU.CR.Domain.Fields;
using EPZEU.CR.Web.App.FieldViews.Common;
using EPZEU.Nomenclatures;
using Microsoft.Extensions.Localization;
using StructureMap;

namespace EPZEU.CR.Web.App.FieldViews
{
    public class FieldViewRegistry : Registry
    {
        public FieldViewRegistry()
        {
            RegisterFieldView<F001_UICView>(F001_UIC.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F001a_NumberNationalRegister.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F002_Company.FieldIdentCode);
            RegisterFieldView<F003_LegalFormView>(F003_LegalForm.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F004_Transliteration.FieldIdentCode);
            RegisterFieldView<F005_SeatView>(F005_Seat.FieldIdentCode);
            RegisterFieldView<F005a_SeatForCorrespondenceView>(F005a_SeatForCorrespondence.FieldIdentCode);
            RegisterFieldView<F006_SubjectOfActivityView>(F006_SubjectOfActivity.FieldIdentCode);
            RegisterFieldView<F006a_SubjectOfActivityNKIDView>(F006a_SubjectOfActivityNKID.FieldIdentCode);
            RegisterFieldView<F006b_ObjectivesView>(F006b_Objectives.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F006g_SubjectToAdditionalBusinessActivity.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F006v_MeansOfAchievingTheObjectives.FieldIdentCode);
            RegisterFieldView<F007_ManagersView>(F007_Managers.FieldIdentCode);
            RegisterFieldView<F007a_AssignedManagersView>(F007a_AssignedManagers.FieldIdentCode);
            RegisterFieldView<F008_WayOfManagementView>(F008_WayOfManagement.FieldIdentCode);
            RegisterFieldView<F009_ChairManView>(F009_ChairMan.FieldIdentCode);
            RegisterFieldView<F010_RepresentativesView>(F010_Representatives.FieldIdentCode);
            RegisterFieldView<F0101_Representatives101View>(F0101_Representatives101.FieldIdentCode);
            RegisterFieldView<F0102_Representatives102View>(F0102_Representatives102.FieldIdentCode);
            RegisterFieldView<F0103_Representatives103View>(F0103_Representatives103.FieldIdentCode);
            RegisterFieldView<F011_WayOfRepresentationView>(F011_WayOfRepresentation.FieldIdentCode);
            RegisterFieldView<F012_BoardOfDirectorsView>(F012_BoardOfDirectors.FieldIdentCode);
            RegisterFieldView<F012a_BoardOfManagers3View>(F012a_BoardOfManagers3.FieldIdentCode);
            RegisterFieldView<F012b_AdministrativeBoardView>(F012b_AdministrativeBoard.FieldIdentCode);
            RegisterFieldView<F012g_Authorities12gView>(F012g_Authorities12g.FieldIdentCode);
            RegisterFieldView<F012d_ManagementBodies12dView>(F012d_ManagementBodies12d.FieldIdentCode);
            RegisterFieldView<F012v_AdministrativeBoardSupportersView>(F012v_AdministrativeBoardSupporters.FieldIdentCode);
            RegisterFieldView<F013_BoardOfManagers2View>(F013_BoardOfManagers2.FieldIdentCode);
            RegisterFieldView<F013_BoardOfManagersView>(F013_BoardOfManagers.FieldIdentCode);
            RegisterFieldView<F013a_BoardOfManagersSupportersView>(F013a_BoardOfManagersSupporters.FieldIdentCode);
            RegisterFieldView<F013b_LeadingBoardView>(F013b_LeadingBoard.FieldIdentCode);
            RegisterFieldView<F013v_BoardManagersSupporter2View>(F013v_BoardOfManagersSupporters2.FieldIdentCode);
            RegisterFieldView<F013g_BoardOfTrusties13gView>(F013g_BoardOfTrusties13g.FieldIdentCode);
            RegisterFieldView<F014_SupervisingBoardView>(F014_SupervisingBoard.FieldIdentCode);
            RegisterFieldView<F014b_SupervisingBoard2View>(F014b_SupervisingBoard2.FieldIdentCode);
            RegisterFieldView<F014v_SupervisingBoardSupportersView>(F014v_SupervisingBoardSupporters.FieldIdentCode);
            RegisterFieldView<F015_ControllingBoardView>(F015_ControllingBoard.FieldIdentCode);
            RegisterFieldView<F015a_ControllingBoardSupportersView>(F015a_ControllingBoardSupporters.FieldIdentCode);
            RegisterFieldView<F015b_VerificationCommission15bView>(F015b_VerificationCommission15b.FieldIdentCode);
            RegisterFieldView<F016_TermsOfPartnershipView>(F016_TermsOfPartnership.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F016a_TermOfExisting.FieldIdentCode);
            RegisterFieldView<F016b_TermOfExistingEUIEView>(F016b_TermOfExistingEUIE.FieldIdentCode);
            RegisterFieldView<F016v_TermOfExistenceNonProfitLegalEntityView>(F016v_TermOfExistenceNonProfitLegalEntity.FieldIdentCode);
            RegisterFieldView<F017_SpecialConditionsView>(F017_SpecialConditions.FieldIdentCode);
            RegisterFieldView<CheckRecordFieldView>(F017a_DesignatedToPerformPublicBenefit.FieldIdentCode);
            RegisterFieldView<CheckRecordFieldView>(F017b_TemporarilySuspendedStatusForPublicBenefits.FieldIdentCode);
            RegisterFieldView<CheckRecordFieldView>(F017v_RestorationOfStatusInPublicBenefit.FieldIdentCode);
            RegisterFieldView<CheckRecordFieldView>(F017g_DesignatedToCarryOutPrivateActivity.FieldIdentCode);
            RegisterFieldView<F018_PhysicalPersonTraderView>(F018_PhysicalPersonTrader.FieldIdentCode);
            RegisterFieldView<F019_PartnersView>(F019_Partners.FieldIdentCode);
            RegisterFieldView<F020_UnlimitedLiabilityPartnersView>(F020_UnlimitedLiabilityPartners.FieldIdentCode);
            RegisterFieldView<F020a_UnlimitedLiabilityPartnersEUIEView>(F020a_UnlimitedLiabilityPartnersEUIE.FieldIdentCode);
            RegisterFieldView<F021_LimitedLiabilityPartnersView>(F021_LimitedLiabilityPartners.FieldIdentCode);
            RegisterFieldView<F022_ForeignTradersView>(F022_ForeignTraders.FieldIdentCode);
            RegisterFieldView<F022a_DiscontinuanceOfForeignTraderView>(F022a_DiscontinuanceOfForeignTrader.FieldIdentCode);
            RegisterFieldView<F022b_InsolvenciesOfForeignTraderView>(F022b_InsolvenciesOfForeignTrader.FieldIdentCode);
            RegisterFieldView<F0223_EuropeanEconomicInterestGroupingView>(F0223_EuropeanEconomicInterestGrouping.FieldIdentCode);
            RegisterFieldView<F0224_DiscontinuanceOfTheEUIEView>(F0224_DiscontinuanceOfTheEUIE.FieldIdentCode);
            RegisterFieldView<F0225_InsolvenciesOfEUIEView>(F0225_InsolvenciesOfEUIE.FieldIdentCode);
            RegisterFieldView<F023_SoleCapitalOwnerView>(F023_SoleCapitalOwner.FieldIdentCode);
            RegisterFieldView<F023a_OwnerView>(F023a_Owner.FieldIdentCode);
            RegisterFieldView<F023b_EuropeanHoldingCompanysAsShareholdersView>(F023b_EuropeanHoldingCompanysAsShareholders.FieldIdentCode);
            RegisterFieldView<F024a_HiddenNonMonetaryDepositView>(F024a_HiddenNonMonetaryDeposit.FieldIdentCode);
            RegisterFieldView<F024_ShareTransfersView>(F024_ShareTransfers.FieldIdentCode);
            RegisterFieldView<F025_SharePaymentResponsibilityView>(F025_SharePaymentResponsibility.FieldIdentCode);
            RegisterFieldView<F025a_ConcededEstateValueView>(F025a_ConcededEstateValue.FieldIdentCode);
            RegisterFieldView<F025b_TotalAmountOfInitialPropertyContributionsView>(F025b_TotalAmountOfInitialPropertyContributions.FieldIdentCode);
            RegisterFieldView<F026_CessationOfTradeView>(F026_CessationOfTrade.FieldIdentCode);
            RegisterFieldView<F026a_CessationOfNonProfitLegalEntityView>(F026a_CessationOfNonProfitLegalEntity.FieldIdentCode);
            RegisterFieldView<F025v_SourcesOfInitialFinancing25vView>(F025v_SourcesOfInitialFinancing25v.FieldIdentCode);
            RegisterFieldView<F027_AddemptionOfTraderView>(F027_AddemptionOfTrader.FieldIdentCode);
            RegisterFieldView<F027a_AddemptionOfTraderSeatChangeView>(F027a_AddemptionOfTraderSeatChange.FieldIdentCode);
            RegisterFieldView<F027b_EraseReservationView>(F027b_EraseReservation.FieldIdentCode);
            RegisterFieldView<F027v_AddemptionOfTraderEraseForeignTraderView>(F027v_AddemptionOfTraderEraseForeignTrader.FieldIdentCode);
            RegisterFieldView<F028_ClosureBranchOfForeignTraderView>(F028_ClosureBranchOfForeignTrader.FieldIdentCode);
            RegisterFieldView<F028a_AddemptionOfEUIEView>(F028a_AddemptionOfEUIE.FieldIdentCode);
            RegisterFieldView<F029_PersonConcernedView>(F029_PersonConcerned.FieldIdentCode);
            RegisterFieldView<F031_FundsView>(F031_Funds.FieldIdentCode);
            RegisterFieldView<F031a_SharesView>(F031a_Shares.FieldIdentCode);
            RegisterFieldView<F031b_MinimumAmountView>(F031b_MinimumAmount.FieldIdentCode);
            RegisterFieldView<F032_DepositedFundsView>(F032_DepositedFunds.FieldIdentCode);
            RegisterFieldView<F033_NonMonetaryDepositsView>(F033_NonMonetaryDeposits.FieldIdentCode);
            RegisterFieldView<F034_BuyBackDecisionView>(F034_BuyBackDecision.FieldIdentCode);
            RegisterFieldView<F041_ProcuratorsView>(F041_Procurators.FieldIdentCode);
            RegisterFieldView<F042_SepcialPowersView>(F042_SepcialPowers.FieldIdentCode);
            RegisterFieldView<F043_WayOfRepresentation43View>(F043_WayOfRepresentation43.FieldIdentCode);
            RegisterFieldView<F044_EraseProcuraView>(F044_EraseProcura.FieldIdentCode);
            RegisterFieldView<F051_BranchSeatView>(F051_BranchSeat.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F051a_BranchFirm.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F051b_BranchIdentifier.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F052_BranchSubjectOfActivity.FieldIdentCode);
            RegisterFieldView<F052a_MainActivityNKIDView>(F052a_MainActivityNKID.FieldIdentCode);
            RegisterFieldView<F053_BranchManagersView>(F053_BranchManagers.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F054_VolumeOfRepresentationPower.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F054a_VolumeOfRepresentationPower541.FieldIdentCode);
            RegisterFieldView<F055_BranchClosureView>(F055_BranchClosure.FieldIdentCode);
            RegisterFieldView<F060_DivisionsOfEuropeanUnificationView>(F060_DivisionsOfEuropeanUnification.FieldIdentCode);
            RegisterFieldView<F070_WayOfEstablishingEuropeanCompanyView>(F070_WayOfEstablishingEuropeanCompany.FieldIdentCode);
            RegisterFieldView<F070a_WayOfEstablishingEuropeanCooperativeSocietyView>(F070a_WayOfEstablishingEuropeanCooperativeSociety.FieldIdentCode);
            RegisterFieldView<F071_SeatChangeView>(F071_SeatChange.FieldIdentCode);
            RegisterFieldView<F101_LimitSubjectOfActivity101View>(F101_LimitSubjectOfActivity101.FieldIdentCode);
            RegisterFieldView<LicenseView>(F102_License102.FieldIdentCode);
            RegisterFieldView<LicenseView>(F108_License108.FieldIdentCode);
            RegisterFieldView<F102a_PutUnderParticularSupervisionView>(F102a_PutUnderParticularSupervision.FieldIdentCode);
            RegisterFieldView<F103_AuthorizationView>(F103_Authorization.FieldIdentCode);
            RegisterFieldView<F104_Suquestrators104View>(F104_Suquestrators104.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F105_OtherCircumstances105.FieldIdentCode);
            RegisterFieldView<F106_LimitSubjectOfActivity106View>(F106_LimitSubjectOfActivity106.FieldIdentCode);
            RegisterFieldView<F107_ManageOrganizationAssets107View>(F107_ManageOrganizationAssets107.FieldIdentCode);
            RegisterFieldView<F109_Suquestrators109View>(F109_Suquestrators109.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F110_OtherCircumstances110.FieldIdentCode);
            RegisterFieldView<CheckRecordFieldView>(F115_RefusalOfLicense.FieldIdentCode);

            RegisterFieldView<F111_LimitSubjectOfActivity111View>(F111_LimitSubjectOfActivity111.FieldIdentCode);
            RegisterFieldView<F112_ManageOrganizationAssets112View>(F112_ManageOrganizationAssets112.FieldIdentCode);
            RegisterFieldView<F113_Suquestrators113View>(F113_Suquestrators113.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F114_OtherCircumstances114.FieldIdentCode);
            RegisterFieldView<F116_SpecialManagerView>(F116_SpecialManager.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F117_OtherCircumstances117.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F200_PledgeDDIdentifier.FieldIdentCode);
            RegisterFieldView<F201_PledgorsView>(F201_Pledgors.FieldIdentCode);
            RegisterFieldView<F203_SecuredClaimDebtorsView>(F203_SecuredClaimDebtors.FieldIdentCode);
            RegisterFieldView<F205_PledgeCreditorsView>(F205_PledgeCreditors.FieldIdentCode);
            RegisterFieldView<F207_SecuredClaimReasonView>(F207_SecuredClaimReason.FieldIdentCode);
            RegisterFieldView<F207a_ContractOfPledgeForShareView>(F207a_ContractOfPledgeForShare.FieldIdentCode);
            RegisterFieldView<F208_SecuredClaimSubjectView>(F208_SecuredClaimSubject.FieldIdentCode);
            RegisterFieldView<F209_SecuredClaimAmountView>(F209_SecuredClaimAmount.FieldIdentCode);
            RegisterFieldView<F210_SecuredClaimInterestsView>(F210_SecuredClaimInterests.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F211_SecuredClaimDelayInterests.FieldIdentCode);
            RegisterFieldView<F212_PledgeMoneyView>(F212_PledgeMoney.FieldIdentCode);
            RegisterFieldView<F213_PledgePropertyDescriptionView>(F213_PledgePropertyDescription.FieldIdentCode);
            RegisterFieldView<F214_PledgePropertyPriceView>(F214_PledgePropertyPrice.FieldIdentCode);
            RegisterFieldView<F215_ModalityDateView>(F215_ModalityDate.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F216_ModalityCondition.FieldIdentCode);
            RegisterFieldView<F216a_PledgedCreditorAgreementView>(F216a_PledgedCreditorAgreement.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F217_PledgeExecutionClaim.FieldIdentCode);
            RegisterFieldView<F218_Partners218View>(F218_Partners218.FieldIdentCode);
            RegisterFieldView<F219_PledgeExecutionDepozitarView>(F219_PledgeExecutionDepozitar.FieldIdentCode);
            RegisterFieldView<F220_DepozitarView>(F220_Depozitar.FieldIdentCode);
            RegisterFieldView<F221_DepozitarDistraintRemoveView>(F221_DepozitarDistraintRemove.FieldIdentCode);
            RegisterFieldView<F222_StopOfExecutionSizeView>(F222_StopOfExecutionSize.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F223_StopOfExecutionProperty.FieldIdentCode);
            RegisterFieldView<F223a_EntryIntoPledgeCreditorRightsView>(F223a_EntryIntoPledgeCreditorRights.FieldIdentCode);
            RegisterFieldView<F224_PledgeRenewDateView>(F224_PledgeRenewDate.FieldIdentCode);
            RegisterFieldView<F225_PledgeAddemptionView>(F225_PledgeAddemption.FieldIdentCode);

            //B4
            RegisterFieldView<TextRecordFieldView>(F300_ForfeitCompanyIdentifier.FieldIdentCode);
            RegisterFieldView<F301_DebtorOverSecureClaimsView>(F301_DebtorOverSecureClaims.FieldIdentCode);
            RegisterFieldView<F303_AtPawnCreditorsView>(F303_AtPawnCreditors.FieldIdentCode);

            RegisterFieldView<F305_ReasonView>(F305_Reason.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F305a_PledgeContractForTrader.FieldIdentCode);
            RegisterFieldView<F306_Object306View>(F306_Object306.FieldIdentCode);
            RegisterFieldView<F307_Size307View>(F307_Size307.FieldIdentCode);
            RegisterFieldView<F308_InterestView>(F308_Interest.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F309_InterestAndDefaultForDelay.FieldIdentCode);
            RegisterFieldView<F310_Size310View>(F310_Size310.FieldIdentCode);
            RegisterFieldView<F311_DescriptionView>(F311_Description.FieldIdentCode);
            RegisterFieldView<F312_Price312View>(F312_Price312.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F313_Term.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F314_Circumstances.FieldIdentCode);
            RegisterFieldView<F314a_PledgedCreditorAgreement2View>(F314a_PledgedCreditorAgreement2.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F315_PartOfClaimwhatIsSeek.FieldIdentCode);
            RegisterFieldView<F316_PropertyOverExecutionView>(F316_PropertyOverExecution.FieldIdentCode);
            RegisterFieldView<F317_DepositorView>(F317_Depositor.FieldIdentCode);
            RegisterFieldView<F318_InvitationForAppointingOfManagerView>(F318_InvitationForAppointingOfManager.FieldIdentCode);
            RegisterFieldView<F319_ManagerOfTradeEnterpriseView>(F319_ManagerOfTradeEnterprise.FieldIdentCode);
            RegisterFieldView<F320_RestoringManagementRightView>(F320_RestoringManagementRight.FieldIdentCode);
            RegisterFieldView<F321_DistraintDataView>(F321_DistraintData.FieldIdentCode);
            RegisterFieldView<F322_RaiseDistraintView>(F322_RaiseDistraint.FieldIdentCode);
            RegisterFieldView<F323_Size323View>(F323_Size323.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F324_StopExecutionOverProperty.FieldIdentCode);
            RegisterFieldView<F324a_EntryIntoPledgeCreditorRights2View>(F324a_EntryIntoPledgeCreditorRights2.FieldIdentCode);
            RegisterFieldView<F325_EraseDistraintView>(F325_EraseDistraint.FieldIdentCode);
            RegisterFieldView<F325a_PartialEraseDistraintView>(F325a_PartialEraseDistraint.FieldIdentCode);
            RegisterFieldView<F326_DateOfRenewingDistraintView>(F326_DateOfRenewingDistraint.FieldIdentCode);

            //End Of B4

            #region B5
            RegisterFieldView<TextRecordFieldView>(F400_DistraintIdentifier.FieldIdentCode);
            RegisterFieldView<F401_DistraintsView>(F401_Distraints.FieldIdentCode);
            RegisterFieldView<F403_Reason403View>(F403_Reason403.FieldIdentCode);
            RegisterFieldView<F404_Size404View>(F404_Size404.FieldIdentCode);
            RegisterFieldView<F404a_MoratoryRateView>(F404a_MoratoryRate.FieldIdentCode);
            RegisterFieldView<F405_InterestsView>(F405_Interests.FieldIdentCode);
            RegisterFieldView<F406_DescriptionsView>(F406_Descriptions.FieldIdentCode);
            RegisterFieldView<F408_LiftingDistraintView>(F408_LiftingDistraint.FieldIdentCode);
            RegisterFieldView<F409_Size409View>(F409_Size409.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F410_StopExecutionOverProperty410.FieldIdentCode);
            #endregion

            //B6
            RegisterFieldView<F501_TermsOfLiquidationView>(F501_TermsOfLiquidation.FieldIdentCode);
            RegisterFieldView<F502_LiquidatorsView>(F502_Liquidators.FieldIdentCode);
            RegisterFieldView<F503_Representative503View>(F503_Representative503.FieldIdentCode);
            RegisterFieldView<F504_ContinuingTradeActivityView>(F504_ContinuingTradeActivity.FieldIdentCode);
            //End Of B6

            RegisterFieldView<F506_ResumeOfLiquidationView>(F506_ResumeOfLiquidation.FieldIdentCode);

            //B7
            RegisterFieldView<TextRecordFieldView>(F001b_NumberNationalRegister1b.FieldIdentCode);
            RegisterFieldView<F529_ReasonForEntry529View>(F529_ReasonForEntry529.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F530_OffshoreIdentifier.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F531_OffshoreCompany.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F532_OffshoreTransliteration.FieldIdentCode);
            RegisterFieldView<F533_OffshoreSeatView>(F533_OffshoreSeat.FieldIdentCode);
            RegisterFieldView<F534_OffshoreRepresentativesView>(F534_OffshoreRepresentatives.FieldIdentCode);
            RegisterFieldView<F535_OffshoreWayOfRepresentationView>(F535_OffshoreWayOfRepresentation.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F536_OffshoreSpecialConditions.FieldIdentCode);
            RegisterFieldView<F537_OffshoreDirectControlCompaniesView>(F537_OffshoreDirectControlCompanies.FieldIdentCode);
            RegisterFieldView<F5371_OffshoreDirectControlCompanyRepresentativesView>(F5371_OffshoreDirectControlCompanyRepresentatives.FieldIdentCode);
            RegisterFieldView<F538_OffshoreNoDirectControlCompaniesView>(F538_OffshoreNoDirectControlCompanies.FieldIdentCode);
            RegisterFieldView<F5381_OffshoreNoDirectControlCompanyRepresentativesView>(F5381_OffshoreNoDirectControlCompanyRepresentatives.FieldIdentCode);
            RegisterFieldView<F540_CircumstanceArticle4View>(F540_CircumstanceArticle4.FieldIdentCode);
            RegisterFieldView<F550_ActualOwnersView>(F550_ActualOwners.FieldIdentCode);
            RegisterFieldView<F550a_ContactPerson550aView>(F550a_ContactPerson550a.FieldIdentCode);
            RegisterFieldView<F551_EraseActualOwnerView>(F551_EraseActualOwner.FieldIdentCode);
            //End Of B7

            RegisterFieldView<F505_StopOfLiquidationView>(F505_StopOfLiquidation.FieldIdentCode);
            RegisterFieldView<F600_TransferringTypeOfTradeEnterpriseView>(F600_TransferringTypeOfTradeEnterprise.FieldIdentCode);
            RegisterFieldView<F601_TransferringEnterpriseView>(F601_TransferringEnterprise.FieldIdentCode);
            RegisterFieldView<F602_AcquisitionEnterprisesView>(F602_AcquisitionEnterprises.FieldIdentCode);
            RegisterFieldView<F701_FormOfTransforming701View>(F701_FormOfTransforming701.FieldIdentCode);
            RegisterFieldView<F702_TransformingCompanysView>(F702_TransformingCompanys.FieldIdentCode);
            RegisterFieldView<F702a_TransformingCompanys2View>(F702a_TransformingCompanys2.FieldIdentCode);
            RegisterFieldView<F702b_TransformingNPOsView>(F702b_TransformingNPOs.FieldIdentCode);
            RegisterFieldView<F703_SuccessorsView>(F703_Successors.FieldIdentCode);
            RegisterFieldView<F704_Branches704View>(F704_Branches704.FieldIdentCode);
            RegisterFieldView<F705_StoppingEntryView>(F705_StoppingEntry.FieldIdentCode);
            RegisterFieldView<F706_NumberApplicationView>(F706_NumberApplication.FieldIdentCode);
            RegisterFieldView<F801_FormOfTransforming801View>(F801_FormOfTransforming801.FieldIdentCode);
            RegisterFieldView<F801a_FormOfTransforming801aView>(F801a_FormOfTransforming801a.FieldIdentCode);
            RegisterFieldView<F802_ReorganizeCoOperativesView>(F802_ReorganizeCoOperatives.FieldIdentCode);
            RegisterFieldView<F802a_ReorganizeCoOperatives2View>(F802a_ReorganizeCoOperatives2.FieldIdentCode);
            RegisterFieldView<F803_Successors803View>(F803_Successors803.FieldIdentCode);
            RegisterFieldView<F804_ReorgBranchesView>(F804_ReorgBranches.FieldIdentCode);
            RegisterFieldView<F850_OpenProccedingsView>(F8500_StabilizationOpenProccedings.FieldIdentCode);
            RegisterFieldView<F8510_StabilizationAdoptionOfPrecautionaryMeasuresView>(F8510_StabilizationAdoptionOfPrecautionaryMeasures.FieldIdentCode);
            RegisterFieldView<F8520_StabilizatioLimitingTheDebtorsAuthorityView>(F8520_StabilizatioLimitingTheDebtorsAuthority.FieldIdentCode);
            RegisterFieldView<F8530_StabilizationSuspendProceedingView>(F8530_StabilizationSuspendProceeding.FieldIdentCode);
            RegisterFieldView<F8550_StabilizationDottedPersonsView>(F8550_StabilizationDottedPersons.FieldIdentCode);
            RegisterFieldView<F8560_StabilizationInspectorsView>(F8560_StabilizationInspectors.FieldIdentCode);
            RegisterFieldView<F8570_StabilizationSupervisorBodyView>(F8570_StabilizationSupervisorBody.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F901_OpenProccedings.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F901_2_OpenProccedingsSecIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F901_3_OpenProccedingsThirdIns.FieldIdentCode);
            RegisterFieldView<TextRecordFieldView>(F902_InsolvencyDate.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F902_InsolvencyData.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F902_2_InsolvencyDataSecIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F902_3_InsolvencyDataThirdIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F903_DebtorBodies.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F903_2_DebtorBodiesSecIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F903_3_DebtorBodiesThirdIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F904_HoldProceedings.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F904_2_HoldProceedingsSecIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F904_3_HoldProceedingsThirdIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F905_ReOpenProceedings.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F905_2_ReOpenProceedingsSecIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F905_3_ReOpenProceedingsThirdIns.FieldIdentCode);
            RegisterFieldView<F906_SuspendProceedingsInstanceView>(F906_SuspendProceedings.FieldIdentCode);
            RegisterFieldView<F906_SuspendProceedingsInstanceView>(F906_2_SuspendProceedingsSecIns.FieldIdentCode);
            RegisterFieldView<F906_SuspendProceedingsInstanceView>(F906_3_SuspendProceedingsThirdIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F906a_TraverseOfRecoverPlan.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F906a_2_TraverseOfRecoverPlanSecIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F906a_3_TraverseOfRecoverPlanThirdIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F907_RestrictDebtorOrderPower.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F907_2_RestrictDebtorOrderPowerSecIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F907_3_RestrictDebtorOrderPowerThirdIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F908_GeneralSeizure.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F908_2_GeneralSeizureSecIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F908_3_GeneralSeizureThirdIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F909_CashIn.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F909_2_CashInSecIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F909_3_CashInThirdIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F910_DeclareBankrupt.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F910_2_DeclareBankruptSecIns.FieldIdentCode);
            RegisterFieldView<BankruptcyRecordFieldView>(F910_3_DeclareBankruptThirdIns.FieldIdentCode);
            RegisterFieldView<F911_ReinstatementsView>(F911_Reinstatements.FieldIdentCode);
            RegisterFieldView<F911_2_ReinstatementsSecInsView>(F911_2_ReinstatementsSecIns.FieldIdentCode);
            RegisterFieldView<F911_3_ReinstatementsThirdInsView>(F911_3_ReinstatementsThirdIns.FieldIdentCode);
            RegisterFieldView<F911a_ReinstatementsDisallowPetitionView>(F911a_ReinstatementsDisallowPetition.FieldIdentCode);
            RegisterFieldView<F911a_2_ReinstatementsDisallowPetitionSecInsView>(F911a_2_ReinstatementsDisallowPetitionSecIns.FieldIdentCode);
            RegisterFieldView<F911a_3_ReinstatementsDisallowPetitionThirdInsView>(F911a_3_ReinstatementsDisallowPetitionThirdIns.FieldIdentCode);
            RegisterFieldView<F912_TrusteesView>(F912_Trustees.FieldIdentCode);
            RegisterFieldView<F912_2_TrusteesSecInsView>(F912_2_TrusteesSecIns.FieldIdentCode);
            RegisterFieldView<F912_3_TrusteesThirdInsView>(F912_3_TrusteesThirdIns.FieldIdentCode);
            RegisterFieldView<F915_SupervisionBodyView>(F915_SupervisionBody.FieldIdentCode);
            RegisterFieldView<F915_SupervisionBodyFullView>(F915_SupervisionBodyFull.FieldIdentCode);
            RegisterFieldView<F915_2_SupervisionBodyFullSecInsView>(F915_2_SupervisionBodyFullSecIns.FieldIdentCode);
            RegisterFieldView<F915_3_SupervisionBodyFullThirdInsView>(F915_3_SupervisionBodyFullThirdIns.FieldIdentCode);

            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019A_StatementsA.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019B_StatementsB.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019C_StatementsC.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019D_StatementsD.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019E_StatementsE.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019F_StatementsF.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019G_StatementsG.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019H_StatementsH.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019I_StatementsI.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019J_StatementsJ.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019K_StatementsK.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019L_StatementsL.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019M_StatementsM.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019N_StatementsN.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019O_StatementsO.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019P_StatementsP.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019Q_StatementsQ.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019R_StatementsR.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019S_StatementsS.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019T_StatementsT.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019U_StatementsU.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019V_StatementsV.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019W_StatementsW.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019X_StatementsX.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019Y_StatementsY.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F10019Z_StatementsZ.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AA_StatementsAA.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AB_StatementsAB.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AC_StatementsAC.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AD_StatementsAD.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AE_StatementsAE.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AF_StatementsAF.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AG_StatementsAG.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AH_StatementsAH.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AI_StatementsAI.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AJ_StatementsAJ.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AK_StatementsAK.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AL_StatementsAL.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AM_StatementsAM.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AN_StatementsAN.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AO_StatementsAO.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AP_StatementsAP.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AQ_StatementsAQ.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AR_StatementsAR.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AS_StatementsAS.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AT_StatementsAT.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AU_StatementsAU.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AV_StatementsAV.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AW_StatementsAW.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AX_StatementsAX.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AY_StatementsAY.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001AZ_StatementsAZ.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001BA_StatementsBA.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001BB_StatementsBB.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001BC_StatementsBC.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001BD_StatementsBD.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001BE_StatementsBE.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001BF_StatementsBF.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001BG_StatementsBG.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001BH_StatementsBH.FieldIdentCode);
            RegisterFieldView<F1001_DescriptionOfDeclaredStatementView>(F1001BI_StatementsBI.FieldIdentCode);
            RegisterFieldView<ContestationActView>(ContestationAct.FieldIdentCode);

            IncludeRegistry<ObjectViewRegistry>();
        }

        private void RegisterFieldView<TFieldView>(string fieldIdentCode) where TFieldView : IFieldView
        {
            For<IFieldView>().Use<TFieldView>().Named(fieldIdentCode).Singleton()
                .Setter<IObjectViewFactory>("ObjectViewFactory").IsTheDefault()
                .Setter<IStringLocalizer>("Localizer").IsTheDefault()
                .Setter<IAuthorities>("Authorities").IsTheDefault()
                .Setter<Integration.EPZEU.Nomenclatures.IBankruptcySenderTypes>("BankruptcySenderTypes").IsTheDefault()
                .Setter<Integration.EPZEU.Nomenclatures.IBankruptcySuspendReasons>("BankruptcySuspendReasons").IsTheDefault()
                .Setter<Integration.EPZEU.Nomenclatures.ITrusteeStatuses>("TrusteeStatuses").IsTheDefault()
                .Setter<Integration.EPZEU.Nomenclatures.IForeignComRegisters>("ForeignComRegisters").IsTheDefault()
                .Setter<Integration.EPZEU.Nomenclatures.IForeignLegalForms>("ForeignLegalForms").IsTheDefault();

        }
    }
}
