<?php
$this->headTitle('EP_CMS_BULETIN_EDIT_L');
?>
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="<?=$this->url('home')?>"><?=$this->translate('GL_HOME_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('GL_CONTENT_L')?></li>
		<li class="breadcrumb-item"><a href="<?=$this->url('bulletin_list')?>"><?=$this->translate('EP_CMS_BULLETINS_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_CMS_BULETIN_EDIT_L')?></li>
	</ol>
</nav>

<div class="page-title">
	<h2><?=$this->translate('EP_CMS_BULETIN_EDIT_L')?></h2>
</div>

<div class="card">

	<?php
	$bulletinForm->setAttribute('action', $this->url('edit_bulletin', ['lang' => $params->fromRoute('lang'), 'bulletinId' => $bulletinId]));
	$bulletinForm->prepare();

	$bulletinForm->setAttribute('id', 'bulletin-form');

	echo $this->form()->openTag($bulletinForm);
	?>

	<div class="card-body">

		<?=$this->partial('partial/messages.phtml')?>

		<div class="row">
			<div class="form-group col-sm-6 col-xxl-4">
				<label for="updatedOn"><?=$this->translate('GL_CREATE_UPDATE_DATE_L');?></label>
					<? $updatedOnDate = $this->dateFormat(
							strtotime($baseObj->getUpdatedOn()),
							IntlDateFormatter::NONE, // date
							IntlDateFormatter::NONE, // time
							$this->plugin('translate')->getTranslator()->getLocale(),
							\Application\View\Helper\DateFormat::DATE
						);
					?>
				<input class="form-control" id="updatedOn" disabled="disabled" value="<?=$updatedOnDate?>">
			</div>

			<div class="col-sm-6 form-group">
				<label class="control-label "><?=$this->translate('GL_CONDITION_L')?></label>
				<div class="form-inline">
					<div class="custom-control-inline custom-control custom-radio">
						<input class="custom-control-input" name="status" id="status_0" value="0" type="radio" <?=!$baseObj->getStatus() ? 'checked="checked"' : '' ?> disabled="disabled">
					    <label class="custom-control-label" for="status_0"><?=$this->translate('GL_M_STATE_NO_PUBLIC_L')?></label>
					</div>
					<div class="custom-control-inline custom-control custom-radio">
						<input class="custom-control-input" name="status" id="status_1" value="1" type="radio" <?=$baseObj->getStatus() ? 'checked="checked"' : '' ?> disabled="disabled">
					    <label class="custom-control-label" for="status_1"><?=$this->translate('GL_M_STATE_PUBLIC_L')?></label>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12 col-lg-6">
				<label class="required-field"><?=$this->translate('GL_PERIOD_L')?></label>
				<div class="row">
					<div class="form-group col-sm-6">
			           <div class="input-group date" id="dateFrom" data-target-input="nearest">
			                <label class="mr-2 col-form-label"><?=$this->translate('GL_START_DATE_L')?></label>
			                <?=$this->formRow($bulletinForm->get('dateFrom'), null, false, '')?>
			                <div class="input-group-append" data-target="#dateFrom" data-toggle="datetimepicker">
			                    <button class="btn btn-secondary" type="button">
									<i class="ui-icon ui-icon-calendar"></i>
								</button>
			                </div>
			                <?=$this->FormElementErrors($bulletinForm->get('dateFrom'))?>
			            </div>
				   </div>
					<div class="form-group col-sm-6">
						<div class="input-group date" id="dateTo" data-target-input="nearest">
			                <label class="mr-2 col-form-label"><?=$this->translate('GL_END_DATE_L')?></label>
			                <?=$this->formRow($bulletinForm->get('dateTo'))?>
			                <div class="input-group-append" data-target="#dateTo" data-toggle="datetimepicker">
			                    <button class="btn btn-secondary" type="button">
									<i class="ui-icon ui-icon-calendar"></i>
								</button>
			                </div>
			                <?=$this->FormElementErrors($bulletinForm->get('dateTo'))?>
			            </div>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12 col-xl-6 form-group">
			<?=$this->formLabel($bulletinForm->get('files'))?>

			<?=$this->partial('partial/uploader.phtml', [
					'uploadUrl' 				=> 'upload_bulletin_file',
					'singleFile' 				=> 1,
					'bulletinObj' 				=> $baseObj,
					'isDeletedOriginalFile' 	=> $isDeletedOriginalFile,
					'fileArr' 					=> $fileArr
			])?>

			<?=$this->formElement($bulletinForm->get('files'))?>

			<?=$this->FormElementErrors($bulletinForm->get('files'))?>

			</div>
		</div>
	</div>

	<div class="card-footer">
		<div class="button-bar">
			<a href="<?=$this->url('bulletin_list',['lang' => $params->fromRoute('lang')], ['query' => $params->fromQuery()])?>" class="btn btn-secondary"><?=$this->translate('GL_REFUSE_L')?></a>
			<?=$this->formSubmit($bulletinForm->get('submit'));?>
		</div>
	</div>

	<?=$this->formRow($bulletinForm->get('deletedFiles'))?>

	<?=$this->form()->closeTag();?>

</div>

<?$this->headLink()->appendStylesheet($this->basePath('js/bootstrap-4-datepicker/css/tempusdominus-bootstrap-4.min.css'));?>
<?$this->headScript()->prependFile($this->basePath('js/bootstrap-4-datepicker/js/tempusdominus-bootstrap-4.min.js'));?>
<?$this->headScript()->prependFile($this->basePath('js/moment-with-locales.min.js'));?>

<script type="text/javascript">

	$(document).on('submit', '#bulletin-form', function(){
		showGlobalLoader();
	});

    $(function () {

         $('#dateFrom').datetimepicker({
        	useCurrent: false,
        	format: "DD.MM.YYYY",
        	locale: moment.locale('bg')
        	<?php if ($params->fromQuery('dateTo')) { ?>
			,
    		maxDate: '<?=\Application\Service\AppService::getSqlDate($params->fromQuery('dateTo'))?>'
        	<?php } ?>
	    });

        $('#dateTo').datetimepicker({
            useCurrent: false,
            format: "DD.MM.YYYY",
            locale: moment.locale('bg')
            <?php if ($params->fromQuery('dateFrom')) { ?>
			,
    		minDate: '<?=\Application\Service\AppService::getSqlDate($params->fromQuery('dateFrom'))?>'
        	<?php } ?>
        });

        $("#dateFrom").on("change.datetimepicker", function (e) {
           $('#dateTo').datetimepicker('minDate', e.date);
        });
        $("#dateTo").on("change.datetimepicker", function (e) {
           $('#dateFrom').datetimepicker('maxDate', e.date);
        });

    });
</script>
