<?
$optionList = $this->element->getValueOptions();
$id = $this->element->getAttribute('id');
$name = $this->element->getAttribute('name');
$checkedValues = $this->element->getValue();



?>

<?foreach($optionList as $option => $value){ ?>
	<div class="custom-control custom-checkbox">
    	<input class="custom-control-input" name="<?=$name?>[]" id="<?=$id.'_'.$option?>" value="<?=$option?>" type="checkbox" <?php if(!empty($checkedValues) && in_array($option, $checkedValues)){ echo ' checked'; }?>>
        <label class="custom-control-label" for="<?=$id.'_'.$option?>"><?=$value?></label>
    </div>
<?}?>
