<div id="main-wrapper" class="main-wrapper">
	<div class="page-wrapper">
		<div class="section-wrapper section-wrapper--margins">
			<div class="fixed-content-width">
				<br>
				<div class="card card-page">
					<div class="card-body card-page__body">
						<div class="alert alert-warning" role="alert"><?=$this->translate('GL_TOO_MANY_REQUESTS_E')?></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>