<? $this->headTitle('EP_USR_00011_L') ?>

<div class="page-header-wrapper">
	<div class="breadcrumbs">
		<div class="fixed-content-width">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="<?=$this->url('home', ['lang' => $this->language()->getCurrentLang()])?>"><?=$this->translate('GL_HOME_L')?></a></li>
					<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_USR_00011_L')?></li>
				</ol>
			</nav>
		</div>
	</div>

	<div class="section-wrapper">
		<div class="fixed-content-width">
			<div class="page-header">
				<div class="row">
					<div class="col">
						<h1 class="page-title"><?=$this->translate('EP_USR_00011_L')?></h1>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<div id="main-wrapper" class="main-wrapper">
	<div class="page-wrapper">
		<div class="section-wrapper section-wrapper--margins">
			<div class="fixed-content-width">
				<div class="card card-page">

					<? if ($isRateLimitReached) { ?>
						<div class="alert alert-warning" role="alert"><?=$this->translate('GL_TOO_MANY_REQUESTS_E')?></div>
					<?} else { ?>

						<?php
						$userForm->setAttribute('action', $this->url('forgot_password', ['lang' => $this->language()->getCurrentLang()]));
						$userForm->prepare();

						$userFieldset = $userForm->get('userFieldset');

						echo $this->form()->openTag($userForm);

						?>
						<div class="card-body card-page__body">

							<div class="row">
								<div class="col-12">
									<?=$this->partial('partial/messages.phtml')?>

									<?=$this->formHidden($userFieldset->get('id'))?>

									<div class="row">
										<div class="col-sm-6 form-group">
											<?=$this->formRow($userFieldset->get('email'))?>
										</div>

									</div>

								</div>
							</div>
						</div>

						<div class="card-footer card-page__footer">
							<div class="button-bar">
								<a href="<?=$this->url('login', ['lang' => $this->language()->getCurrentLang()])?>" class="btn btn-secondary"><?=$this->translate('GL_REFUSE_L')?></a>
								<?=$this->formSubmit($userForm->get('submit'));?>
							</div>
						</div>
						<?=$this->form()->closeTag();?>
					<? } ?>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
$(document).on('submit','#userform',function(){
	showGlobalLoader();
});
</script>