<? $this->headTitle($message) ?>

<div class="page-header-wrapper">
	<div class="breadcrumbs">
		<div class="fixed-content-width">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="<?=$this->url('home', ['lang' => $this->language()->getCurrentLang()])?>"><?=$this->translate('GL_HOME_L')?></a></li>
					<li class="breadcrumb-item active" aria-current="page"><?=$this->translate($title)?></li>
				</ol>
			</nav>
		</div>
	</div>

	<div class="section-wrapper">
		<div class="fixed-content-width">
			<div class="page-header">
				<div class="row">
					<div class="col">
						<h1 class="page-title"><?=$this->translate($title)?></h1>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<div id="main-wrapper" class="main-wrapper">
	<div class="page-wrapper">
		<div class="section-wrapper section-wrapper--margins">
			<div class="fixed-content-width">
				<div class="card card-page">
					<div class="alert <?=$success ? 'alert-success' : 'alert-warning'?>" role="alert"><?=$this->translate($message)?></div>
				</div>
			</div>
		</div>
	</div>
</div>
