<?
$userStatusList = array_flip($userStatusList);

foreach ($userStatusList as $key => &$value)
	$value = 'GL_'.$value.'_L';

foreach ($userList as $baseObj) {?>
	<tr>
		<td id="user-td-<?=$baseObj->getUserId()?>">
			<div class="custom-control custom-radio">
				<input class="custom-control-input" type="radio" id="user-radio-<?=$baseObj->getUserId()?>" name="selectUser" value="<?=$baseObj->getUserId()?>">
				<label class="custom-control-label" for="user-radio-<?=$baseObj->getUserId()?>"></label>
			</div>

			<input type="hidden" name="userData" id="userData-<?=$baseObj->getUserId()?>" value='<?=\User\Service\UserService::getUserInfoString($baseObj)?>'>
			<input type="hidden" name="userData" id="userDataEmail-<?=$baseObj->getUserId()?>" value='<?=$baseObj->getEmail()?>'>
		</td>

		<td>
			<?=$this->dateFormat(
				strtotime($baseObj->getUpdatedOn()),
			    IntlDateFormatter::MEDIUM, // date
			    IntlDateFormatter::NONE, // time
			    $this->plugin('translate')->getTranslator()->getLocale(),
				\Application\View\Helper\DateFormat::DATETIME
			)?>
		</td>
		<td><?=$baseObj->getCin()?></td>
		<td><?=$baseObj->getUsername()?></td>
		<td><?=$baseObj->getEmail()?></td>
		<td><?=$baseObj->getFirstName()?></td>
		<td><?=$baseObj->getMiddleName()?></td>
		<td><?=$baseObj->getFamilyName()?></td>
		<td><?=nl2br($baseObj->getContactData())?></td>
		<td><?=$baseObj->getOrganization()?></td>
		<td class="icons-td">
			<?

			$status = $userStatusList[$baseObj->getStatus()];

			switch ($status) {
				case 'GL_ACTIVE_L':
					$iconStatus = 'active';
					break;
				case 'GL_INACTIVE_L':
					$iconStatus = 'inactive';
					break;
				case 'EP_USR_00007_E':
					$iconStatus = 'waiting';
					break;
			}
			?>
			<i class="ui-icon ui-icon-state-<?=$iconStatus?>" aria-hidden="true"></i>
			<span class="text-wrap"><?=$this->translate($status)?></span>
		</td>

	</tr>
<? } ?>

<script type="text/javascript">
	$(document).ready(function() {
		var userId = window.parent.$("#userId").val();
		if (userId) {
			$('#user-radio-'+userId).prop('checked', true);
		}
	})
</script>
