<?php
$pagelabel = $isRedefined ? $this->translate('EP_CMS_EDIT_PREDЕFINE_PAGE_HTML_L') : $this->translate('EP_CMS_EDIT_PAGE_HTML_L');

$pageRoute = $isRedefined ? 'edit_redefined_page' : 'edit_html_page';

$this->headTitle($pagelabel);
?>

<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="<?=$this->url('home')?>"><?=$this->translate('GL_HOME_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('GL_CONTENT_L')?></li>
		<li class="breadcrumb-item"><a href="<?=$isRedefined ? $this->url('redefined_page_list') : $this->url('html_page_list')?>"><?=$isRedefined ? $this->translate('EP_CMS_MANAGING_PAGES_PREDЕFINE_HTML_CONTENT_L') : $this->translate('EP_CMS_MANAGING_PAGES_HTML_CONTENT_CREATE_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$pagelabel?></li>
	</ol>
</nav>

<div class="page-title">
	<h2><?=$pagelabel?></h2>
</div>

<div class="card">

	<?php
	$pageForm->setAttribute('action', $this->url($pageRoute, ['lang' => $params->fromRoute('lang'), 'pageId' => $pageObj->getPageId()]));
	$pageForm->setAttribute('id', 'html-page-form');
	$pageForm->prepare();

	echo $this->form()->openTag($pageForm);
	?>

	<div class="card-body">

		<?=$this->partial('partial/messages.phtml')?>


		<div class="row">
			<div class="col-sm-12 col-md-6 col-xl-5 form-group">
				<? $updatedOn = $this->dateFormat(
						strtotime($pageObj->getUpdatedOn()),
						IntlDateFormatter::NONE, // date
						IntlDateFormatter::NONE, // time
						$this->plugin('translate')->getTranslator()->getLocale(),
						\Application\View\Helper\DateFormat::DATETIME
					);
				?>
				<label for="status"><?=$this->translate('GL_CREATE_UPDATE_DATE_L');?></label>
				<input class="form-control" id="status" disabled="disabled" value="<?=$updatedOn?>">
			</div>

			<div class="col-sm-12 col-md-6 col-xl-7 form-group"> <? // TODO да се подмени с линк към страницата в публичната част ?>
				<? $pageForm->get('URL')->setValue($this->publicUrl([$pageObj->getUrl()]));?>
				<?=$this->formRow($pageForm->get('URL'))?>
			</div>

		</div>

		<div class="row">
			<div class="col-sm-12 col-md-6 col-xl-5 form-group">
				<?=$this->formRow($pageForm->get('moduleId'))?>
			</div>
			<div class="col-sm-12 col-md-6 col-xl-7 form-group">
				<?=$this->formRow($pageForm->get('title'))?>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12 form-group">
				<?=$this->formRow($pageForm->get('content'))?>

				<? if ($this->FormElementErrors($pageForm->get('content'))) { ?>
					<script>
						CKEDITOR.on('instanceReady', function() {
							$('#cke_content').addClass('input-error');
						});
					</script>
				<? } ?>
			</div>
		</div>

	</div>

	<div class="card-footer">
		<div class="button-bar">
			<?php
			$pageRoute = $pageObj->getType() == \Content\Controller\PageController::HTML_PAGE ? 'html_page_list' : 'redefined_page_list';
			?>

			<a href="<?=$this->url($pageRoute, ['lang' => $params->fromRoute('lang')])?>" class="btn btn-secondary"><?=$this->translate('GL_REFUSE_L')?></a>
			<?=$this->formSubmit($pageForm->get('submit'));?>
		</div>
	</div>

	<?=$this->form()->closeTag();?>

</div>

<?$this->headScript()->appendFile($this->basePath('js/ckeditor/ckeditor.js'));?>

<script>
$(document).on('submit', '#html-page-form', function(){
	showGlobalLoader();
});
</script>