<?php
$this->headTitle('EP_CMS_TRANSLATE_VIDEO_PAGE_L');
?>
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="<?=$this->url('home')?>"><?=$this->translate('GL_HOME_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_TRANSLATION_TRANSLATIONS_L')?></li>
		<li class="breadcrumb-item"><a href="<?=$this->url('video_lesson_list_translate')?>"><?=$this->translate('EP_CMS_PAGES_VIDEO_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_CMS_TRANSLATE_VIDEO_PAGE_L')?></li>
	</ol>
</nav>

<div class="page-title">
	<h2><?=$this->translate('EP_CMS_TRANSLATE_VIDEO_PAGE_L')?></h2>
</div>

<?=$this->partial('partial\language-drop-down.phtml')?>

<div class="card">

	<?php
	$videoLessonForm->setAttribute('action', $this->url('video_lesson_translate', ['lang' => $params->fromRoute('lang'), 'lessonId' => $lessonId]));
	$videoLessonForm->setAttribute('id', 'video-lesson-form');
	$videoLessonForm->prepare();

	echo $this->form()->openTag($videoLessonForm);
	?>

	<div class="card-body">

		<?=$this->partial('partial/messages.phtml')?>

		<div class="row">
			<div class="col-sm-12 form-group">
				<label for=""><?=$this->translate($videoLessonForm->get('title')->getLabel())?></label>
				<div>
					<?=$videoLessonForm->get('title')->getValue() ?>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12 form-group">
				<?=$this->formLabel($videoLessonForm->get('titleI18n'))?><span class="label-description"> (<?=$this->language()->getLanguagesName()?>)</span>
				<?=$this->formElement($videoLessonForm->get('titleI18n'))?>
				<?=$this->formElementErrors($videoLessonForm->get('titleI18n'))?>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12 form-group disabled">
				<label for=""><?=$this->translate($videoLessonForm->get('description')->getLabel())?></label>
				<div class="form-text-srollable-large">
					<?=$videoLessonForm->get('description')->getValue() ?>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12 form-group">
				<?=$this->formLabel($videoLessonForm->get('descriptionI18n'))?><span class="label-description"> (<?=$this->language()->getLanguagesName()?>)</span>
				<?=$this->formElement($videoLessonForm->get('descriptionI18n'))?>
				<?=$this->formElementErrors($videoLessonForm->get('descriptionI18n'))?>

				<? if ($this->FormElementErrors($videoLessonForm->get('descriptionI18n'))) { ?>
					<script>
						CKEDITOR.on('instanceReady', function() {
							$('#cke_descriptionI18n').addClass('input-error');
						});
					</script>
				<? } ?>
			</div>
		</div>

		<div class="row">
			<div class="col-sm-12 col-xl-6 form-group">
			<?=$this->formLabel($videoLessonForm->get('files'))?><span class="label-description"> (<?=$this->language()->getLanguagesName()?>)</span>

			<?=$this->partial('partial/uploader.phtml', [
					'uploadUrl' 				=> 'upload_video_file',
					'singleFile' 				=> 1,
					'maxFileSize' 				=> $videoFileSize,
					'videoLessonObj' 			=> $baseObj,
					'deletedFiles' 				=> $deletedFiles,
					'isDeletedOriginalFile' 	=> $isDeletedOriginalFile,
					'fileArr' 					=> $fileArr,
					'translatedFile'			=> 1,
					'lang'						=> $params->fromRoute('lang')
			])?>

			<?=$this->formElement($videoLessonForm->get('files'))?>

			<?=$this->FormElementErrors($videoLessonForm->get('files'))?>

			<div id="emailHelp" class="help-text-inline"><?=str_replace('{EP_CMS_VIDEO_ALLOWED_FORMATS}', $videoFileFormat, $this->translate('EP_CMS_VIDEO_ALLOWED_FORMATS_I'))?></div>
			<div id="emailHelp" class="help-text-inline"><?=str_replace('{EP_CMS_VIDEO_MAX_FILE_SIZE}', $videoFileSize, $this->translate('EP_CMS_VIDEO_MAX_FILE_SIZE_I'))?></div>
			</div>
		</div>

	</div>

	<div class="card-footer">
		<div class="button-bar">
			<a href="<?=$this->url('video_lesson_list_translate',['lang' => $params->fromRoute('lang')], ['query' => $params->fromQuery()])?>" class="btn btn-secondary"><?=$this->translate('GL_REFUSE_L')?></a>
			<?=$this->formSubmit($videoLessonForm->get('submit'));?>
		</div>
	</div>

	<?=$this->formRow($videoLessonForm->get('deletedFiles'))?>

	<?=$this->form()->closeTag();?>

</div>

<?$this->headScript()->appendFile($this->basePath('js/ckeditor/ckeditor.js'));?>

<script>
$(document).on('submit', '#video-lesson-form', function(){
	showGlobalLoader();
});

$(document).ready(function(){
	$('#language-select').attr("disabled", true);
})
</script>
