<?php
$this->headTitle('EP_CMS_PAGES_VIDEO_L');
?>

<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="<?=$this->url('home')?>"><?=$this->translate('GL_HOME_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('GL_CONTENT_L')?></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_CMS_PAGES_VIDEO_L')?></li>
	</ol>
</nav>

<div class="page-title">
	<h2><?=$this->translate('EP_CMS_PAGES_VIDEO_L')?></h2>
</div>

<div class="card">

	<div class="card-header">
		<h3><?=$this->translate('GL_SEARCHING_L')?>
			<button class="system-button toggle-collapse" data-toggle="collapse" data-target="#collapsable-content">
				<i class="ui-icon ui-icon-chevron-up" aria-hidden="true"></i>
			</button>
		</h3>
	</div>

	<div id="collapsable-content" class="collapse show">
		<?
		$searchForm->setAttribute('action', $this->url('video_lesson_list', ['lang' => $params->fromRoute('lang')]));
		$searchForm->prepare();

		echo $this->form()->openTag($searchForm);
		?>


		<div class="card-body">
			<div class="row">
				<div class="col-xl-6">
					<div class="row">
						<div class="form-group col-sm-6 col-xl-3">
							<?=$this->formRow($searchForm->get('registerSelectId'))?>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="card-footer">
			<div class="button-bar">
				<a href="<?=$this->url(null, ['lang' => $params->fromRoute('lang')])?>" class="btn btn-secondary"><?=$this->translate('GL_CLEAR_L')?></a>
				<button type="submit" class="btn btn-primary"><i class="ui-icon ui-icon-search ci-btn"></i>&nbsp;<?=$this->translate('GL_SEARCH_L')?></button>
			</div>
		</div>
		<?=$this->form()->closeTag();?>
	</div>
</div>


<div class="card">
	<div class="card-body">

	<?=$this->partial('partial/messages.phtml')?>

	<?if ($this->isAllowed('add_video_lesson')) { ?>
		<div class="card-navbar">
			<div class="button-bar">
				<div class="left-side"></div>
				<div class="right-side">
					<a href="<?=$this->url('add_video_lesson', ['lang' => $params->fromRoute('lang')])?>" class="btn btn-primary" role="button" aria-pressed="true">
					<i class="ui-icon ui-icon-plus-white"></i>
					<?=$this->translate('EP_CMS_PAGE_VIDEO_ADD_L')?>
					</a>
				</div>
			</div>
		</div>
	<?}?>

	<?if ($videoLessonList->count()) { ?>

		<nav class="button-bar" aria-label="Page navigation">
			<div class="pagination-container">
				<div class="result-count"><?=$this->translate('GL_TOTAL_L')?>: <?=$totalCount?></div>
				<ul class="sync-pagination"></ul>
			</div>
		</nav>

		<div class="table-responsive">
			<table class="table table-bordered table-striped table-hover">
				<thead>
				<tr>
					<th><?=$this->translate('GL_REGISTER_L')?></th>
					<th><?=$this->translate('EP_CMS_HEADER_L')?></th>
					<th><?=$this->translate('GL_DESCRIPTION_L')?></th>
					<th><?=$this->translate('GL_CREATE_UPDATE_DATE_L')?></th>
					<th><?=$this->translate('GL_CONDITION_L')?></th>
					<th><?=$this->translate('GL_ACTIONS_L')?></th>
				</tr>
				</thead>
				<tbody id="content">
					<?=$this->partial('video-lesson-list-partial.phtml')?>
				</tbody>
			</table>
		</div>

		<nav class="button-bar" aria-label="Page navigation">
			<div class="pagination-container">
				<div class="result-count"><?=$this->translate('GL_TOTAL_L')?>: <?=$totalCount?></div>
				<ul class="sync-pagination"></ul>
			</div>
		</nav>

		<?
			$this->headScript()->appendFile($this->basePath('/js/jquery.twbsPagination.js'), 'text/javascript');
			$this->headScript()->appendFile($this->basePath('/js/paginator.js'), 'text/javascript');
		?>

		<script type="text/javascript">
			pagination('.sync-pagination', '#content', <?=$totalPages?>);
		</script>

	<? } ?>
	</div>
</div>

<?=$this->partial('partial/modal-confirm.phtml')?>