import { ObjectHelper } from 'Cnsys.Core'
import { ApplicationWithFieldsFormBaseManager, IApplicationWithFieldsFormManager, DeedsDataService, Address } from 'EPZEU.CR.Domain'
import { ApplicationFormBBase } from '../Models/ApplicationForms/ApplicationFormsB'
import { ApplicationFormBFieldsBase } from '../Models/ApplicationForms/ModelsAutoGenerated'

export interface IApplicationFormBManager extends IApplicationWithFieldsFormManager { }

export abstract class ApplicationFormBBaseManager<TAppl extends ApplicationFormBBase<ApplicationFormBFieldsBase>> extends ApplicationWithFieldsFormBaseManager<TAppl> implements IApplicationFormBManager {


    public get canFillAppExchangeAddress(): boolean {
        return true;
    }

    public getSeatAddress(): Promise<Address> {
        return new DeedsDataService().getCompanySeat(this.application.fields.uic.text).then((seat) => {
            if (seat) {
                return JSON.parse(JSON.stringify(seat.address));
            }
            else {
                return null;
            }
        });
    }
}

export function isApplicationFormBManager(obj: IApplicationFormBManager | any): obj is IApplicationFormBManager {
    return obj && ObjectHelper.isSubClassOf(obj, ApplicationFormBBaseManager);
}