<? $this->headTitle('EP_CMS_FORUM_L') ?>

<div class="page-header-wrapper">
	<div class="breadcrumbs">
		<div class="fixed-content-width">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="<?=$this->url('home', ['lang' => $this->language()->getCurrentLang()])?>"><?=$this->translate('GL_HOME_L')?></a></li>
					<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_CMS_FORUM_L')?></li>
				</ol>
			</nav>
		</div>
	</div>

	<div class="section-wrapper">
		<div class="fixed-content-width">
			<div class="page-header">
				<div class="row">
					<div class="col">
						<h1 class="page-title"><?=$this->translate('EP_CMS_FORUM_L')?></h1>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="main-wrapper" class="main-wrapper">
	<div class="page-wrapper">
		<div class="section-wrapper section-wrapper--margins">
			<div class="fixed-content-width">
				<div class="card card-page">
					<div class="row">
						<div class="col-12">
							<?=$this->partial('partial/messages.phtml')?>
						</div>
					</div>

					<? if (!$userObj->getFirstName()) { ?>
					<div class="col-12">
						<div class="alert alert-danger" role="alert"><?=$this->translate('EP_FORUM_USER_NAME_E')?></div>
					</div>
					<? } ?>

					<div class="card-body card-page__body">

						<? if ($userObj->getFirstName()) { ?>
						<a href="<?=$this->url('new_topic', ['lang' => $this->language()->getCurrentLang()])?>" class="btn btn-outline-light text-dark mb-2">
							<i class="ui-icon ui-icon-plus" aria-hidden="true"></i>
							<?=$this->translate('EP_CMS_FORUM_NEW_TOPIC_L')?>
						</a>
						<? } ?>

						<div class="row">
							<div class="col-12">

							<nav class="pagination-container pagination-container--page-top" aria-label="Page navigation">
								<div class="result-count">
									<?=$this->translate('GL_TOTAL_L')?>: <?=$totalCount?>
								</div>
								<ul class="sync-pagination pagination pagination--page"></ul>
							</nav>

							<div id="content">
								<?=$this->partial('forum/forum/topic-list-partial.phtml')?>
							</div>

							<nav class="pagination-container pagination-container--page-bottom" aria-label="Page navigation">
								<div class="result-count">
									<?=$this->translate('GL_TOTAL_L')?>: <?=$totalCount?>
								</div>
								<ul class="sync-pagination pagination pagination--page"></ul>
							</nav>

							<?php
							$this->headScript()->appendFile($this->basePath('/js/jquery.twbsPagination.js'), 'text/javascript');
							$this->headScript()->appendFile($this->basePath('/js/paginator.js'), 'text/javascript');
							?>

							<script type="text/javascript">
							pagination('.sync-pagination', '#content', <?=$totalPages?>);
							</script>

							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>