<? $this->headTitle('EP_CMS_BULLETINS_L') ?>

<div class="page-header-wrapper">
	<div class="breadcrumbs">
		<div class="fixed-content-width">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="<?=$this->url('home', ['lang' => $this->language()->getCurrentLang()])?>"><?=$this->translate('GL_HOME_L')?></a></li>
					<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_CMS_BULLETINS_L')?></li>
				</ol>
			</nav>
		</div>
	</div>

	<div class="section-wrapper">
		<div class="fixed-content-width">
			<div class="page-header">
				<div class="row">
					<div class="col">
						<h1 class="page-title"><?=$this->translate('EP_CMS_BULLETINS_L')?></h1>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="main-wrapper" class="main-wrapper">
	<div class="page-wrapper">
		<div class="section-wrapper section-wrapper--margins">
			<div class="fixed-content-width">

				<? if ($bulletinList->count()) { ?>

					<div class="card card-page">
						<div class="card-body card-page__body">

							<nav class="pagination-container pagination-container--page-top" aria-label="Page navigation">
								<div class="result-count">
									<?=$this->translate('GL_TOTAL_L')?>: <?=$totalCount?>
								</div>
								<ul class="pagination pagination--page"></ul>
							</nav>

							<section id="content">
								<?=$this->partial('bulletin-list-partial.phtml')?>
							</section>

							<nav class="pagination-container pagination-container--page-bottom" aria-label="Page navigation">
								<div class="result-count">
									<?=$this->translate('GL_TOTAL_L')?>: <?=$totalCount?>
								</div>
								<ul class="pagination pagination--page"></ul>
							</nav>

							<?php
							$this->headScript()->appendFile($this->basePath('/js/jquery.twbsPagination.js'), 'text/javascript');
							$this->headScript()->appendFile($this->basePath('/js/paginator.js'), 'text/javascript');
							?>

							<script type="text/javascript">
							pagination('.pagination', '#content', <?=$totalPages?>);
							</script>

						</div>
					</div>
				<? } ?>

			</div>
		</div>
	</div>
</div>