import * as React from "react";
import { EPZEUBaseComponent } from 'EPZEU.Core'
import { F005a_SeatForCorrespondence } from '../../Models/Fields/ModelsAutoGenerated'
import { withFieldRecordContainer, FieldContainerProps, AddressUI } from 'EPZEU.CR.Domain';

class F005a_SeatForCorrespondenceUI extends EPZEUBaseComponent<FieldContainerProps, F005a_SeatForCorrespondence> {

    constructor(props?: FieldContainerProps) {
        super(props);
    }

    renderEdit(): JSX.Element {
        return <>
            <AddressUI {...this.bind(m => m.address)} disabledCountry={true} />
        </>
    }

    renderDisplay(): JSX.Element {
        return (
            <>
                <AddressUI {...this.bind(m => m.address)} disabledCountry={true} />
            </>);
    }
}

export const F005a_SeatForCorrespondenceFieldUI = withFieldRecordContainer(F005a_SeatForCorrespondenceUI, { fieldLabelTextKey: "CR_F_5a_L" });