import { EPZEUBaseComponent, ValidationSummaryStrategy } from 'EPZEU.Core';
import { FieldContainerProps, PersonTypes, PersonUI, withFieldRecordContainer } from 'EPZEU.CR.Domain';
import * as React from "react";
import { F009_ChairMan } from "../../Models/Fields/ModelsAutoGenerated";

class F009_ChairManUI extends EPZEUBaseComponent<FieldContainerProps, F009_ChairMan> {

    renderEdit(): JSX.Element {
        return <>
            <PersonUI {...this.bind(m => m.person)} PersonType={PersonTypes.ChairMan} />
        </>
    }

    renderDisplay(): JSX.Element {
        return <PersonUI {...this.bind(m => m.person)} PersonType={PersonTypes.ChairMan} />
    }
}

export const F009_ChairManFieldUI = withFieldRecordContainer(F009_ChairManUI, {
    fieldLabelTextKey: "CR_F_9_L",
    isMandatoryField: true,
    valSummaryStrategy: ValidationSummaryStrategy.excludeAllExcept,
    valSummaryRecursive: true,
    valSummaryPropNames: ["", "person."],
});