import * as React from "react";
import { EPZEUBaseComponent, ValidationSummaryStrategy } from 'EPZEU.Core'
import { withFieldRecordContainer, withTextRecordContainer } from 'EPZEU.CR.Domain';
import { F012g_Authorities12g, F012g_Authority12g } from '../../Models/Fields/ModelsAutoGenerated'
import { withFieldSingleListRecordsContainer, ListRecordsContainerProps, PersonUI, PersonTypes, SectionInfoUI } from 'EPZEU.CR.Domain';

class F012g_Authoritiy12gUI extends EPZEUBaseComponent<ListRecordsContainerProps, F012g_Authority12g> {

    renderEdit(): JSX.Element {
        return (
            <>
                <div className="row">
                    <div className="form-group col-12">
                        {this.textBoxFor(m => m.text)}
                    </div>
                </div>
            </>);
    }

    renderDisplay(): JSX.Element {
        return (
            <>
                {this.model.text && <>{this.model.text} </>}
            </>
        );
    }
}

export const F012g_Authorities12gFieldUI = withFieldSingleListRecordsContainer(F012g_Authoritiy12gUI, F012g_Authority12g, {
    addButtonLabelKey: "GL_ADD_L",
    listSelector: m => m.authorities12gList,
    fieldLabelTextKey: "CR_F_12g_L",
    hasAtLeastOneRecord: true,
    isMandatoryField: true,
    valSummaryStrategy: ValidationSummaryStrategy.excludeAllExcept,
    valSummaryRecursive: true,
    valSummaryPropNames: [""]
})
