import * as React from "react";
import { EPZEUBaseComponent, ValidationSummaryStrategy, Nomenclatures } from 'EPZEU.Core'
import { F01321_BoardManager2 } from '../../Models/Fields/ModelsAutoGenerated'
import { PersonUI, PersonTypes, withListRecordsContainer, ListRecordsContainerProps, Person } from 'EPZEU.CR.Domain';

class F01321_BoardManager2UIImpl extends EPZEUBaseComponent<ListRecordsContainerProps, F01321_BoardManager2> {

    renderEdit(): JSX.Element {
        return (
            <>
                <PersonUI {...this.bind(m => m.subject)} PersonType={PersonTypes.Supervisor} />
            </>
        );
    }

    renderDisplay(): JSX.Element {
        return (
            <>
                <PersonUI {...this.bind(m => m.subject)} PersonType={PersonTypes.Supervisor} />
            </>
        );
    }
}

export const F01321_BoardManager2UI = withListRecordsContainer(F01321_BoardManager2UIImpl, F01321_BoardManager2, {
    addButtonLabelKey: "CR_APP_ADD_MEMBER_TO_GOVERNING_BOARD_L",
    hasAtLeastOneRecord: true,
    valSummaryStrategy: ValidationSummaryStrategy.excludeAllExcept,
    valSummaryRecursive: true,
    valSummaryPropNames: ["", "subject."],
    newRecordCtor: () => {
        return Nomenclatures.getBGCountry().then(bgCountry => {
            var boardManager = new F01321_BoardManager2();

            boardManager.subject = new Person();
            boardManager.subject.countryCode = bgCountry.code;
            boardManager.subject.countryID = bgCountry.id;
            boardManager.subject.countryName = bgCountry.name;

            return boardManager;
        })
    }
})