import { EPZEUBaseComponent, ValidationSummaryStrategy, Nomenclatures } from 'EPZEU.Core';
import { ListRecordsContainerProps, PersonTypes, PersonUI, SectionInfoUI, withFieldSingleListRecordsContainer, Person } from 'EPZEU.CR.Domain';
import * as React from "react";
import { F01310_BoardOfManagersSupportersPerson } from '../../Models/Fields/ModelsAutoGenerated';

class F013a_BoardOfManagersSupportersUI extends EPZEUBaseComponent<ListRecordsContainerProps, F01310_BoardOfManagersSupportersPerson> {

    renderEdit(): JSX.Element {
        return (
            <>                
                <PersonUI {...this.bind(m => m.person)} PersonType={PersonTypes.ChairMan} />
            </>);
    }

    renderDisplay(): JSX.Element {
        return <PersonUI {...this.bind(m => m.person)} PersonType={PersonTypes.ChairMan} />
    }
}
export const F013a_BoardOfManagersSupportersFieldUI = withFieldSingleListRecordsContainer(F013a_BoardOfManagersSupportersUI, F01310_BoardOfManagersSupportersPerson, {
    addButtonLabelKey: "CR_APP_ADD_RUNNER_TO_GOVERNING_BOARD_L",
    listSelector: m => m.boardOfManagersSupportersPersonList,
    fieldLabelTextKey: "CR_F_13a_L",
    hasAtLeastOneRecord: true,
    valSummaryStrategy: ValidationSummaryStrategy.excludeAllExcept,
    valSummaryRecursive: true,
    valSummaryPropNames: ["", "person."],
    newRecordCtor: () => {
        return Nomenclatures.getBGCountry().then(bgCountry => {
            var manager = new F01310_BoardOfManagersSupportersPerson();

            manager.person = new Person();
            manager.person.countryCode = bgCountry.code;
            manager.person.countryID = bgCountry.id;
            manager.person.countryName = bgCountry.name;

            return manager;
        })
    }
})