import * as React from "react";
import { EPZEUBaseComponent, ValidationSummaryStrategy, Nomenclatures } from 'EPZEU.Core'
import { F01340_BoardManagersSupporter2 } from '../../Models/Fields/ModelsAutoGenerated'
import { PersonUI, PersonTypes, withListRecordsContainer, ListRecordsContainerProps, Person } from 'EPZEU.CR.Domain';

class F01340_BoardManagersSupporter2UIImpl extends EPZEUBaseComponent<ListRecordsContainerProps, F01340_BoardManagersSupporter2> {

    renderEdit(): JSX.Element {
        return (
            <>
                <PersonUI {...this.bind(m => m.subject)} PersonType={PersonTypes.Director} />
            </>
        );
    }

    renderDisplay(): JSX.Element {
        return (
            <>
                <PersonUI {...this.bind(m => m.subject)} PersonType={PersonTypes.Director} />
            </>
        );
    }
}

export const F01340_BoardManagersSupporter2UI = withListRecordsContainer(F01340_BoardManagersSupporter2UIImpl, F01340_BoardManagersSupporter2, {
    addButtonLabelKey: "CR_APP_ADD_DEPUTY_MEMBER_TO_MANAGEMENT_BOARD_L",
    hasAtLeastOneRecord: true,
    valSummaryStrategy: ValidationSummaryStrategy.excludeAllExcept,
    valSummaryRecursive: true,
    valSummaryPropNames: ["", "subject."],
 
})

