import { EPZEUBaseComponent, Nomenclatures } from 'EPZEU.Core';
import { FieldContainerProps, ListRecordsContainerProps, MandateUI, withFieldContainer, Person, SectionSubTitle } from 'EPZEU.CR.Domain';
import * as React from "react";
import { F015b_VerificationCommission15b, F015b1_CommissionMember15b } from '../../Models/Fields/ModelsAutoGenerated';
import { F015b1_CommissionMember15bUI } from "./F015b1_CommissionMember15bUI";


class F015b_VerificationCommission15bUI extends EPZEUBaseComponent<FieldContainerProps, F015b_VerificationCommission15b> {

    constructor(props?: ListRecordsContainerProps) {
        super(props);
    }

    renderEdit(): JSX.Element {
        return (
            <>
                <MandateUI {...this.bind(m => m.verificationCommission15bMandate)} />
                <SectionSubTitle subTitleTextKey={"CR_APP_MEMBERS_VERIFICATION_COMMISSION_L"} />
                <F015b1_CommissionMember15bUI {...this.bind(x => x.commissionMembers15bList)} newRecordCtor={() => {
                    return Nomenclatures.getBGCountry().then(bgCountry => {
                        var manager = new F015b1_CommissionMember15b();

                        manager.person = new Person();
                        manager.person.countryCode = bgCountry.code;
                        manager.person.countryID = bgCountry.id;
                        manager.person.countryName = bgCountry.name;

                        return manager;
                    })
                }}/>
            </>);
    }

    renderDisplay(): JSX.Element {
        return (
            <>
                <MandateUI {...this.bind(m => m.verificationCommission15bMandate)} />
                <F015b1_CommissionMember15bUI {...this.bind(x => x.commissionMembers15bList)} />
            </>
        );
    }
}

export const F015b_VerificationCommission15bFieldUI = withFieldContainer(F015b_VerificationCommission15bUI, {
    fieldLabelTextKey: "CR_F_15b_L",
    isMandatoryField: true,
});
