import { EPZEUBaseComponent, ValidationSummaryStrategy } from 'EPZEU.Core';
import { FieldContainerProps, PersonTypes, PersonUI, SectionInfoUI, withFieldRecordContainer } from 'EPZEU.CR.Domain';
import * as React from "react";
import { F023_SoleCapitalOwner } from '../../Models/Fields/ModelsAutoGenerated';

class F023_SoleCapitalOwnerUI extends EPZEUBaseComponent<FieldContainerProps, F023_SoleCapitalOwner> {

    renderEdit(): JSX.Element {
        return (<>
            <PersonUI {...this.bind(m => m.subject)} PersonType={PersonTypes.SoleCapitalOwner} />
        </>)
    }

    renderDisplay(): JSX.Element {
        return <PersonUI {...this.bind(m => m.subject)} PersonType={PersonTypes.SoleCapitalOwner} />;
    }
}

export const F023_SoleCapitalOwnerFieldUI = withFieldRecordContainer(F023_SoleCapitalOwnerUI, {
    fieldLabelTextKey: "CR_F_23_L",
    valSummaryStrategy: ValidationSummaryStrategy.excludeAllExcept,
    valSummaryRecursive: true,
    valSummaryPropNames: ["", "subject."]
});