<?php
$this->headTitle('EP_MSG_L');
?>

<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="<?=$this->url('home')?>"><?=$this->translate('GL_HOME_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_MSG_L')?></li>
	</ol>
</nav>


<div class="page-title">
	<h2><?=$this->translate('EP_MSG_L')?></h2>
</div>

<div class="card">

	<div class="card-header">
		<h3><?=$this->translate('GL_SEARCHING_L')?>
			<button class="system-button toggle-collapse" data-toggle="collapse" data-target="#collapsable-content">
				<i class="ui-icon ui-icon-chevron-up" aria-hidden="true"></i>
			</button>
		</h3>
	</div>

	<div id="collapsable-content" class="collapse show">
		<?
		$searchForm->setAttribute('method', 'get');
		$searchForm->setAttribute('action', $this->url('message_list', ['lang' => $params->fromRoute('lang')]));
		$searchForm->prepare();

		echo $this->form()->openTag($searchForm);
		?>

		<div class="card-body">

			<?=$this->formRow($searchForm->get('search'))?>

			<div class="row">

				<div class="col-sm-12 col-lg-6 col-xxl-4">
					<label><?=$this->translate('GL_PERIOD_CREATED_LAST_UPDATED_L')?></label>
					<div class="row">
						<div class="form-group col-sm-6">
							<div class="input-group date" id="dateFrom" data-target-input="nearest">
								<label class="mr-2 col-form-label"><?=$this->translate('GL_START_DATE_L')?></label>
								<?=$this->formRow($searchForm->get('dateFrom'), null, false)?>
								<div class="input-group-append" data-target="#dateFrom" data-toggle="datetimepicker">
									<button class="btn btn-secondary" type="button">
										<i class="ui-icon ui-icon-calendar"></i>
									</button>
								</div>
								<?=$this->FormElementErrors($searchForm->get('dateFrom'))?>
							</div>
						</div>
						<div class="form-group col-sm-6">
							<div class="input-group date" id="dateTo" data-target-input="nearest">
						    	<label class="mr-2 col-form-label"><?=$this->translate('GL_END_DATE_L')?></label>
								<?=$this->formRow($searchForm->get('dateTo'), null, false)?>
						        <div class="input-group-append" data-target="#dateTo" data-toggle="datetimepicker">
									<button class="btn btn-secondary" type="button">
										<i class="ui-icon ui-icon-calendar"></i>
									</button>
								</div>
								<?=$this->FormElementErrors($searchForm->get('dateTo'))?>
							</div>
						</div>
					</div>
				</div>

				<div class="form-group col-sm-6 col-xl-3 col-xxl-5">
					<?=$this->formRow($searchForm->get('about'))?>
				</div>

				<div class="form-group col-sm-6 col-xl-3">
					<?=$this->formRow($searchForm->get('status'))?>
				</div>

			</div>

		</div>

		<div class="card-footer">
			<div class="button-bar">
				<a href="<?=$this->url('message_list', ['lang' => $params->fromRoute('lang')])?>" class="btn btn-secondary"><?=$this->translate('GL_CLEAR_L')?></a>
				<button type="submit" class="btn btn-primary"><i class="ui-icon ui-icon-search ci-btn"></i>&nbsp;<?=$this->translate('GL_SEARCH_L')?></button>
			</div>
		</div>

		<?=$this->form()->closeTag();?>

	</div>
</div>

<div class="card">
	<div class="card-body">

	<?=$this->partial('partial/messages.phtml')?>

	<?if ($this->isAllowed('add_message')) { ?>
		<div class="card-navbar">
			<div class="button-bar">
				<div class="left-side"></div>
				<div class="right-side">
					<a href="<?=$this->url('add_message', ['lang' => $params->fromRoute('lang')])?>" class="btn btn-primary" role="button" aria-pressed="true">
					<i class="ui-icon ui-icon-plus-white"></i>
					<?=$this->translate('EP_MSG_ADD_L')?>
					</a>
				</div>
			</div>
		</div>
	<?}?>

	<?if ($params->fromQuery('search') || $messageList->count()) { ?>

		<?if ($messageList->count()) { ?>

			<nav class="button-bar" aria-label="Page navigation">
				<div class="pagination-container">
					<div class="result-count"><?=$this->translate('GL_TOTAL_L')?>: <?=$totalCount?></div>
					<ul class="sync-pagination"></ul>
				</div>
			</nav>

			<div class="table-responsive">
				<table class="table table-bordered table-striped table-hover">
					<thead>
					<tr>
						<th><?=$this->translate('GL_CREATE_UPDATE_DATE_L')?></th>
						<th><?=$this->translate('EP_MSG_SUBJECT_L')?></th>
						<th><?=$this->translate('GL_CONDITION_L')?></th>
						<th><?=$this->translate('GL_ACTIONS_L')?></th>
					</tr>
					</thead>
					<tbody id="content">
						<?=$this->partial('message-list-partial.phtml')?>
					</tbody>
				</table>
			</div>

			<nav class="button-bar" aria-label="Page navigation">
				<div class="pagination-container">
					<div class="result-count"><?=$this->translate('GL_TOTAL_L')?>: <?=$totalCount?></div>
					<ul class="sync-pagination"></ul>
				</div>
			</nav>

			<?
				$this->headScript()->appendFile($this->basePath('/js/jquery.twbsPagination.js'), 'text/javascript');
				$this->headScript()->appendFile($this->basePath('/js/paginator.js'), 'text/javascript');
			?>

			<script type="text/javascript">
				pagination('.sync-pagination', '#content', <?=$totalPages?>);
			</script>

		<? } else { ?>
			<div class="alert alert-warning" role="alert">
				<?=$this->translate('GL_NO_RESULTS_I')?>
			</div>
		<? }
	}?>
	</div>
</div>

<?$this->headLink()->appendStylesheet($this->basePath('js/bootstrap-4-datepicker/css/tempusdominus-bootstrap-4.min.css'));?>
<?$this->headScript()->prependFile($this->basePath('js/bootstrap-4-datepicker/js/tempusdominus-bootstrap-4.min.js'));?>
<?$this->headScript()->prependFile($this->basePath('js/moment-with-locales.min.js'));?>

<?=$this->partial('partial/modal-preview.phtml', ['title' => $this->translate('EP_MSG_VIEW_L')])?>
<?=$this->partial('partial/modal-confirm.phtml')?>
<script>

$(function () {

	$('#dateFrom').datetimepicker({
		useCurrent: false,
		format: "DD.MM.YYYY",
		locale: moment.locale('bg')
		<?php if ($params->fromQuery('dateTo')) { ?>
		,
		maxDate: '<?=\Application\Service\AppService::getSqlDate($params->fromQuery('dateTo'))?>'
		<?php } ?>
	});

	$('#dateTo').datetimepicker({
		useCurrent: false,
		format: "DD.MM.YYYY",
		locale: moment.locale('bg')
		<?php if ($params->fromQuery('dateFrom')) { ?>
		,
		minDate: '<?=\Application\Service\AppService::getSqlDate($params->fromQuery('dateFrom'))?>'
		<?php } ?>
	});

	$("#dateFrom").on("change.datetimepicker", function (e) {
		$('#dateTo').datetimepicker('minDate', e.date);
	});
	$("#dateTo").on("change.datetimepicker", function (e) {
		$('#dateFrom').datetimepicker('maxDate', e.date);
	});
});
</script>