<div id="main-wrapper" class="main-wrapper">
	<div class="page-wrapper">
		<div class="section-wrapper section-wrapper--margins">
			<div class="fixed-content-width">
				<div class="card card-page">
					<div class="card-body card-page__body">
						<div class="row">
							<div class="col-12">
								<div class="alert alert-warning" role="alert"><?=$this->translate('GL_EP_USR_NOT_SERTIFICATE_LOGIN_E')?></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>