

// Auto Generated Object
import * as moment from 'moment'
import { observable } from 'mobx'
import { TypeSystem, BaseDataModel } from 'Cnsys.Core'
import { ApplicationFormFieldsBase } from 'EPZEU.CR.Domain'
import { moduleContext } from '../../ModuleContext'
import * as fields from '../Fields/ModelsAutoGenerated'



@TypeSystem.typeDecorator('ApplicationFormBFieldsBase', moduleContext.moduleName)
export class ApplicationFormBFieldsBase extends ApplicationFormFieldsBase { 

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('B1Fields', moduleContext.moduleName)
export class B1Fields extends ApplicationFormBFieldsBase { 

    @observable private _procurators: fields.F041_Procurators = null;
    
    @TypeSystem.propertyDecorator(fields.F041_Procurators)
    public set procurators(val: fields.F041_Procurators){
        this._procurators = val;
    }
    
    public get procurators(): fields.F041_Procurators{
        return this._procurators;
    }
     

    @observable private _sepcialPowers: fields.F042_SepcialPowers = null;
    
    @TypeSystem.propertyDecorator(fields.F042_SepcialPowers)
    public set sepcialPowers(val: fields.F042_SepcialPowers){
        this._sepcialPowers = val;
    }
    
    public get sepcialPowers(): fields.F042_SepcialPowers{
        return this._sepcialPowers;
    }
     

    @observable private _wayOfRepresentation: fields.F043_WayOfRepresentation43 = null;
    
    @TypeSystem.propertyDecorator(fields.F043_WayOfRepresentation43)
    public set wayOfRepresentation(val: fields.F043_WayOfRepresentation43){
        this._wayOfRepresentation = val;
    }
    
    public get wayOfRepresentation(): fields.F043_WayOfRepresentation43{
        return this._wayOfRepresentation;
    }
     

    @observable private _eraseProcura: fields.F044_EraseProcura = null;
    
    @TypeSystem.propertyDecorator(fields.F044_EraseProcura)
    public set eraseProcura(val: fields.F044_EraseProcura){
        this._eraseProcura = val;
    }
    
    public get eraseProcura(): fields.F044_EraseProcura{
        return this._eraseProcura;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('B2Fields', moduleContext.moduleName)
export class B2Fields extends ApplicationFormBFieldsBase { 

    @observable private _branchFirm: fields.F051a_BranchFirm = null;
    
    @TypeSystem.propertyDecorator(fields.F051a_BranchFirm)
    public set branchFirm(val: fields.F051a_BranchFirm){
        this._branchFirm = val;
    }
    
    public get branchFirm(): fields.F051a_BranchFirm{
        return this._branchFirm;
    }
     

    @observable private _branchIdentifier: fields.F051b_BranchIdentifier = null;
    
    @TypeSystem.propertyDecorator(fields.F051b_BranchIdentifier)
    public set branchIdentifier(val: fields.F051b_BranchIdentifier){
        this._branchIdentifier = val;
    }
    
    public get branchIdentifier(): fields.F051b_BranchIdentifier{
        return this._branchIdentifier;
    }
     

    @observable private _branchSeat: fields.F051_BranchSeat = null;
    
    @TypeSystem.propertyDecorator(fields.F051_BranchSeat)
    public set branchSeat(val: fields.F051_BranchSeat){
        this._branchSeat = val;
    }
    
    public get branchSeat(): fields.F051_BranchSeat{
        return this._branchSeat;
    }
     

    @observable private _branchSubjectOfActivity: fields.F052_BranchSubjectOfActivity = null;
    
    @TypeSystem.propertyDecorator(fields.F052_BranchSubjectOfActivity)
    public set branchSubjectOfActivity(val: fields.F052_BranchSubjectOfActivity){
        this._branchSubjectOfActivity = val;
    }
    
    public get branchSubjectOfActivity(): fields.F052_BranchSubjectOfActivity{
        return this._branchSubjectOfActivity;
    }
     

    @observable private _mainActivityNKID: fields.F052a_MainActivityNKID = null;
    
    @TypeSystem.propertyDecorator(fields.F052a_MainActivityNKID)
    public set mainActivityNKID(val: fields.F052a_MainActivityNKID){
        this._mainActivityNKID = val;
    }
    
    public get mainActivityNKID(): fields.F052a_MainActivityNKID{
        return this._mainActivityNKID;
    }
     

    @observable private _branchManagers: fields.F053_BranchManagers = null;
    
    @TypeSystem.propertyDecorator(fields.F053_BranchManagers)
    public set branchManagers(val: fields.F053_BranchManagers){
        this._branchManagers = val;
    }
    
    public get branchManagers(): fields.F053_BranchManagers{
        return this._branchManagers;
    }
     

    @observable private _volumeOfRepresentationPower: fields.F054_VolumeOfRepresentationPower = null;
    
    @TypeSystem.propertyDecorator(fields.F054_VolumeOfRepresentationPower)
    public set volumeOfRepresentationPower(val: fields.F054_VolumeOfRepresentationPower){
        this._volumeOfRepresentationPower = val;
    }
    
    public get volumeOfRepresentationPower(): fields.F054_VolumeOfRepresentationPower{
        return this._volumeOfRepresentationPower;
    }
     

    @observable private _branchClosure: fields.F055_BranchClosure = null;
    
    @TypeSystem.propertyDecorator(fields.F055_BranchClosure)
    public set branchClosure(val: fields.F055_BranchClosure){
        this._branchClosure = val;
    }
    
    public get branchClosure(): fields.F055_BranchClosure{
        return this._branchClosure;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('B3Fields', moduleContext.moduleName)
export class B3Fields extends ApplicationFormBFieldsBase { 

    @observable private _pledgeDDIdentifier: fields.F200_PledgeDDIdentifier = null;
    
    @TypeSystem.propertyDecorator(fields.F200_PledgeDDIdentifier)
    public set pledgeDDIdentifier(val: fields.F200_PledgeDDIdentifier){
        this._pledgeDDIdentifier = val;
    }
    
    public get pledgeDDIdentifier(): fields.F200_PledgeDDIdentifier{
        return this._pledgeDDIdentifier;
    }
     

    @observable private _pledgors: fields.F201_Pledgors = null;
    
    @TypeSystem.propertyDecorator(fields.F201_Pledgors)
    public set pledgors(val: fields.F201_Pledgors){
        this._pledgors = val;
    }
    
    public get pledgors(): fields.F201_Pledgors{
        return this._pledgors;
    }
     

    @observable private _securedClaimDebtors: fields.F203_SecuredClaimDebtors = null;
    
    @TypeSystem.propertyDecorator(fields.F203_SecuredClaimDebtors)
    public set securedClaimDebtors(val: fields.F203_SecuredClaimDebtors){
        this._securedClaimDebtors = val;
    }
    
    public get securedClaimDebtors(): fields.F203_SecuredClaimDebtors{
        return this._securedClaimDebtors;
    }
     

    @observable private _pledgeCreditors: fields.F205_PledgeCreditors = null;
    
    @TypeSystem.propertyDecorator(fields.F205_PledgeCreditors)
    public set pledgeCreditors(val: fields.F205_PledgeCreditors){
        this._pledgeCreditors = val;
    }
    
    public get pledgeCreditors(): fields.F205_PledgeCreditors{
        return this._pledgeCreditors;
    }
     

    @observable private _securedClaimReason: fields.F207_SecuredClaimReason = null;
    
    @TypeSystem.propertyDecorator(fields.F207_SecuredClaimReason)
    public set securedClaimReason(val: fields.F207_SecuredClaimReason){
        this._securedClaimReason = val;
    }
    
    public get securedClaimReason(): fields.F207_SecuredClaimReason{
        return this._securedClaimReason;
    }
     

    @observable private _contractOfPledgeForShare: fields.F207a_ContractOfPledgeForShare = null;
    
    @TypeSystem.propertyDecorator(fields.F207a_ContractOfPledgeForShare)
    public set contractOfPledgeForShare(val: fields.F207a_ContractOfPledgeForShare){
        this._contractOfPledgeForShare = val;
    }
    
    public get contractOfPledgeForShare(): fields.F207a_ContractOfPledgeForShare{
        return this._contractOfPledgeForShare;
    }
     

    @observable private _securedClaimSubject: fields.F208_SecuredClaimSubject = null;
    
    @TypeSystem.propertyDecorator(fields.F208_SecuredClaimSubject)
    public set securedClaimSubject(val: fields.F208_SecuredClaimSubject){
        this._securedClaimSubject = val;
    }
    
    public get securedClaimSubject(): fields.F208_SecuredClaimSubject{
        return this._securedClaimSubject;
    }
     

    @observable private _securedClaimAmount: fields.F209_SecuredClaimAmount = null;
    
    @TypeSystem.propertyDecorator(fields.F209_SecuredClaimAmount)
    public set securedClaimAmount(val: fields.F209_SecuredClaimAmount){
        this._securedClaimAmount = val;
    }
    
    public get securedClaimAmount(): fields.F209_SecuredClaimAmount{
        return this._securedClaimAmount;
    }
     

    @observable private _securedClaimInterests: fields.F210_SecuredClaimInterests = null;
    
    @TypeSystem.propertyDecorator(fields.F210_SecuredClaimInterests)
    public set securedClaimInterests(val: fields.F210_SecuredClaimInterests){
        this._securedClaimInterests = val;
    }
    
    public get securedClaimInterests(): fields.F210_SecuredClaimInterests{
        return this._securedClaimInterests;
    }
     

    @observable private _securedClaimDelayInterests: fields.F211_SecuredClaimDelayInterests = null;
    
    @TypeSystem.propertyDecorator(fields.F211_SecuredClaimDelayInterests)
    public set securedClaimDelayInterests(val: fields.F211_SecuredClaimDelayInterests){
        this._securedClaimDelayInterests = val;
    }
    
    public get securedClaimDelayInterests(): fields.F211_SecuredClaimDelayInterests{
        return this._securedClaimDelayInterests;
    }
     

    @observable private _pledgeMoney: fields.F212_PledgeMoney = null;
    
    @TypeSystem.propertyDecorator(fields.F212_PledgeMoney)
    public set pledgeMoney(val: fields.F212_PledgeMoney){
        this._pledgeMoney = val;
    }
    
    public get pledgeMoney(): fields.F212_PledgeMoney{
        return this._pledgeMoney;
    }
     

    @observable private _pledgePropertyDescription: fields.F213_PledgePropertyDescription = null;
    
    @TypeSystem.propertyDecorator(fields.F213_PledgePropertyDescription)
    public set pledgePropertyDescription(val: fields.F213_PledgePropertyDescription){
        this._pledgePropertyDescription = val;
    }
    
    public get pledgePropertyDescription(): fields.F213_PledgePropertyDescription{
        return this._pledgePropertyDescription;
    }
     

    @observable private _pledgePropertyPrice: fields.F214_PledgePropertyPrice = null;
    
    @TypeSystem.propertyDecorator(fields.F214_PledgePropertyPrice)
    public set pledgePropertyPrice(val: fields.F214_PledgePropertyPrice){
        this._pledgePropertyPrice = val;
    }
    
    public get pledgePropertyPrice(): fields.F214_PledgePropertyPrice{
        return this._pledgePropertyPrice;
    }
     

    @observable private _modalityDate: fields.F215_ModalityDate = null;
    
    @TypeSystem.propertyDecorator(fields.F215_ModalityDate)
    public set modalityDate(val: fields.F215_ModalityDate){
        this._modalityDate = val;
    }
    
    public get modalityDate(): fields.F215_ModalityDate{
        return this._modalityDate;
    }
     

    @observable private _modalityCondition: fields.F216_ModalityCondition = null;
    
    @TypeSystem.propertyDecorator(fields.F216_ModalityCondition)
    public set modalityCondition(val: fields.F216_ModalityCondition){
        this._modalityCondition = val;
    }
    
    public get modalityCondition(): fields.F216_ModalityCondition{
        return this._modalityCondition;
    }
     

    @observable private _pledgedCreditorAgreement: fields.F216a_PledgedCreditorAgreement = null;
    
    @TypeSystem.propertyDecorator(fields.F216a_PledgedCreditorAgreement)
    public set pledgedCreditorAgreement(val: fields.F216a_PledgedCreditorAgreement){
        this._pledgedCreditorAgreement = val;
    }
    
    public get pledgedCreditorAgreement(): fields.F216a_PledgedCreditorAgreement{
        return this._pledgedCreditorAgreement;
    }
     

    @observable private _pledgeExecutionClaim: fields.F217_PledgeExecutionClaim = null;
    
    @TypeSystem.propertyDecorator(fields.F217_PledgeExecutionClaim)
    public set pledgeExecutionClaim(val: fields.F217_PledgeExecutionClaim){
        this._pledgeExecutionClaim = val;
    }
    
    public get pledgeExecutionClaim(): fields.F217_PledgeExecutionClaim{
        return this._pledgeExecutionClaim;
    }
     

    @observable private _partners218: fields.F218_Partners218 = null;
    
    @TypeSystem.propertyDecorator(fields.F218_Partners218)
    public set partners218(val: fields.F218_Partners218){
        this._partners218 = val;
    }
    
    public get partners218(): fields.F218_Partners218{
        return this._partners218;
    }
     

    @observable private _pledgeExecutionDepozitar: fields.F219_PledgeExecutionDepozitar = null;
    
    @TypeSystem.propertyDecorator(fields.F219_PledgeExecutionDepozitar)
    public set pledgeExecutionDepozitar(val: fields.F219_PledgeExecutionDepozitar){
        this._pledgeExecutionDepozitar = val;
    }
    
    public get pledgeExecutionDepozitar(): fields.F219_PledgeExecutionDepozitar{
        return this._pledgeExecutionDepozitar;
    }
     

    @observable private _depozitar: fields.F220_Depozitar = null;
    
    @TypeSystem.propertyDecorator(fields.F220_Depozitar)
    public set depozitar(val: fields.F220_Depozitar){
        this._depozitar = val;
    }
    
    public get depozitar(): fields.F220_Depozitar{
        return this._depozitar;
    }
     

    @observable private _depozitarDistraintRemove: fields.F221_DepozitarDistraintRemove = null;
    
    @TypeSystem.propertyDecorator(fields.F221_DepozitarDistraintRemove)
    public set depozitarDistraintRemove(val: fields.F221_DepozitarDistraintRemove){
        this._depozitarDistraintRemove = val;
    }
    
    public get depozitarDistraintRemove(): fields.F221_DepozitarDistraintRemove{
        return this._depozitarDistraintRemove;
    }
     

    @observable private _stopOfExecutionSize: fields.F222_StopOfExecutionSize = null;
    
    @TypeSystem.propertyDecorator(fields.F222_StopOfExecutionSize)
    public set stopOfExecutionSize(val: fields.F222_StopOfExecutionSize){
        this._stopOfExecutionSize = val;
    }
    
    public get stopOfExecutionSize(): fields.F222_StopOfExecutionSize{
        return this._stopOfExecutionSize;
    }
     

    @observable private _stopOfExecutionProperty: fields.F223_StopOfExecutionProperty = null;
    
    @TypeSystem.propertyDecorator(fields.F223_StopOfExecutionProperty)
    public set stopOfExecutionProperty(val: fields.F223_StopOfExecutionProperty){
        this._stopOfExecutionProperty = val;
    }
    
    public get stopOfExecutionProperty(): fields.F223_StopOfExecutionProperty{
        return this._stopOfExecutionProperty;
    }
     

    @observable private _pledgeRenewDate: fields.F224_PledgeRenewDate = null;
    
    @TypeSystem.propertyDecorator(fields.F224_PledgeRenewDate)
    public set pledgeRenewDate(val: fields.F224_PledgeRenewDate){
        this._pledgeRenewDate = val;
    }
    
    public get pledgeRenewDate(): fields.F224_PledgeRenewDate{
        return this._pledgeRenewDate;
    }
     

    @observable private _pledgeAddemption: fields.F225_PledgeAddemption = null;
    
    @TypeSystem.propertyDecorator(fields.F225_PledgeAddemption)
    public set pledgeAddemption(val: fields.F225_PledgeAddemption){
        this._pledgeAddemption = val;
    }
    
    public get pledgeAddemption(): fields.F225_PledgeAddemption{
        return this._pledgeAddemption;
    }
     

    @observable private _entryIntoPledgeCreditorRights: fields.F223a_EntryIntoPledgeCreditorRights = null;
    
    @TypeSystem.propertyDecorator(fields.F223a_EntryIntoPledgeCreditorRights)
    public set entryIntoPledgeCreditorRights(val: fields.F223a_EntryIntoPledgeCreditorRights){
        this._entryIntoPledgeCreditorRights = val;
    }
    
    public get entryIntoPledgeCreditorRights(): fields.F223a_EntryIntoPledgeCreditorRights{
        return this._entryIntoPledgeCreditorRights;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('B4Fields', moduleContext.moduleName)
export class B4Fields extends ApplicationFormBFieldsBase { 

    @observable private _forfeitCompanyIdentifier: fields.F300_ForfeitCompanyIdentifier = null;
    
    @TypeSystem.propertyDecorator(fields.F300_ForfeitCompanyIdentifier)
    public set forfeitCompanyIdentifier(val: fields.F300_ForfeitCompanyIdentifier){
        this._forfeitCompanyIdentifier = val;
    }
    
    public get forfeitCompanyIdentifier(): fields.F300_ForfeitCompanyIdentifier{
        return this._forfeitCompanyIdentifier;
    }
     

    @observable private _debtorOverSecureClaims: fields.F301_DebtorOverSecureClaims = null;
    
    @TypeSystem.propertyDecorator(fields.F301_DebtorOverSecureClaims)
    public set debtorOverSecureClaims(val: fields.F301_DebtorOverSecureClaims){
        this._debtorOverSecureClaims = val;
    }
    
    public get debtorOverSecureClaims(): fields.F301_DebtorOverSecureClaims{
        return this._debtorOverSecureClaims;
    }
     

    @observable private _atPawnCreditors: fields.F303_AtPawnCreditors = null;
    
    @TypeSystem.propertyDecorator(fields.F303_AtPawnCreditors)
    public set atPawnCreditors(val: fields.F303_AtPawnCreditors){
        this._atPawnCreditors = val;
    }
    
    public get atPawnCreditors(): fields.F303_AtPawnCreditors{
        return this._atPawnCreditors;
    }
     

    @observable private _reason: fields.F305_Reason = null;
    
    @TypeSystem.propertyDecorator(fields.F305_Reason)
    public set reason(val: fields.F305_Reason){
        this._reason = val;
    }
    
    public get reason(): fields.F305_Reason{
        return this._reason;
    }
     

    @observable private _pledgeContractForTrader: fields.F305a_PledgeContractForTrader = null;
    
    @TypeSystem.propertyDecorator(fields.F305a_PledgeContractForTrader)
    public set pledgeContractForTrader(val: fields.F305a_PledgeContractForTrader){
        this._pledgeContractForTrader = val;
    }
    
    public get pledgeContractForTrader(): fields.F305a_PledgeContractForTrader{
        return this._pledgeContractForTrader;
    }
     

    @observable private _object306: fields.F306_Object306 = null;
    
    @TypeSystem.propertyDecorator(fields.F306_Object306)
    public set object306(val: fields.F306_Object306){
        this._object306 = val;
    }
    
    public get object306(): fields.F306_Object306{
        return this._object306;
    }
     

    @observable private _size307: fields.F307_Size307 = null;
    
    @TypeSystem.propertyDecorator(fields.F307_Size307)
    public set size307(val: fields.F307_Size307){
        this._size307 = val;
    }
    
    public get size307(): fields.F307_Size307{
        return this._size307;
    }
     

    @observable private _interest: fields.F308_Interest = null;
    
    @TypeSystem.propertyDecorator(fields.F308_Interest)
    public set interest(val: fields.F308_Interest){
        this._interest = val;
    }
    
    public get interest(): fields.F308_Interest{
        return this._interest;
    }
     

    @observable private _interestAndDefaultForDelay: fields.F309_InterestAndDefaultForDelay = null;
    
    @TypeSystem.propertyDecorator(fields.F309_InterestAndDefaultForDelay)
    public set interestAndDefaultForDelay(val: fields.F309_InterestAndDefaultForDelay){
        this._interestAndDefaultForDelay = val;
    }
    
    public get interestAndDefaultForDelay(): fields.F309_InterestAndDefaultForDelay{
        return this._interestAndDefaultForDelay;
    }
     

    @observable private _size310: fields.F310_Size310 = null;
    
    @TypeSystem.propertyDecorator(fields.F310_Size310)
    public set size310(val: fields.F310_Size310){
        this._size310 = val;
    }
    
    public get size310(): fields.F310_Size310{
        return this._size310;
    }
     

    @observable private _description: fields.F311_Description = null;
    
    @TypeSystem.propertyDecorator(fields.F311_Description)
    public set description(val: fields.F311_Description){
        this._description = val;
    }
    
    public get description(): fields.F311_Description{
        return this._description;
    }
     

    @observable private _price312: fields.F312_Price312 = null;
    
    @TypeSystem.propertyDecorator(fields.F312_Price312)
    public set price312(val: fields.F312_Price312){
        this._price312 = val;
    }
    
    public get price312(): fields.F312_Price312{
        return this._price312;
    }
     

    @observable private _term: fields.F313_Term = null;
    
    @TypeSystem.propertyDecorator(fields.F313_Term)
    public set term(val: fields.F313_Term){
        this._term = val;
    }
    
    public get term(): fields.F313_Term{
        return this._term;
    }
     

    @observable private _circumstances: fields.F314_Circumstances = null;
    
    @TypeSystem.propertyDecorator(fields.F314_Circumstances)
    public set circumstances(val: fields.F314_Circumstances){
        this._circumstances = val;
    }
    
    public get circumstances(): fields.F314_Circumstances{
        return this._circumstances;
    }
     

    @observable private _pledgedCreditorAgreement2: fields.F314a_PledgedCreditorAgreement2 = null;
    
    @TypeSystem.propertyDecorator(fields.F314a_PledgedCreditorAgreement2)
    public set pledgedCreditorAgreement2(val: fields.F314a_PledgedCreditorAgreement2){
        this._pledgedCreditorAgreement2 = val;
    }
    
    public get pledgedCreditorAgreement2(): fields.F314a_PledgedCreditorAgreement2{
        return this._pledgedCreditorAgreement2;
    }
     

    @observable private _partOfClaimwhatIsSeek: fields.F315_PartOfClaimwhatIsSeek = null;
    
    @TypeSystem.propertyDecorator(fields.F315_PartOfClaimwhatIsSeek)
    public set partOfClaimwhatIsSeek(val: fields.F315_PartOfClaimwhatIsSeek){
        this._partOfClaimwhatIsSeek = val;
    }
    
    public get partOfClaimwhatIsSeek(): fields.F315_PartOfClaimwhatIsSeek{
        return this._partOfClaimwhatIsSeek;
    }
     

    @observable private _propertyOverExecution: fields.F316_PropertyOverExecution = null;
    
    @TypeSystem.propertyDecorator(fields.F316_PropertyOverExecution)
    public set propertyOverExecution(val: fields.F316_PropertyOverExecution){
        this._propertyOverExecution = val;
    }
    
    public get propertyOverExecution(): fields.F316_PropertyOverExecution{
        return this._propertyOverExecution;
    }
     

    @observable private _depositor: fields.F317_Depositor = null;
    
    @TypeSystem.propertyDecorator(fields.F317_Depositor)
    public set depositor(val: fields.F317_Depositor){
        this._depositor = val;
    }
    
    public get depositor(): fields.F317_Depositor{
        return this._depositor;
    }
     

    @observable private _invitationForAppointingOfManager: fields.F318_InvitationForAppointingOfManager = null;
    
    @TypeSystem.propertyDecorator(fields.F318_InvitationForAppointingOfManager)
    public set invitationForAppointingOfManager(val: fields.F318_InvitationForAppointingOfManager){
        this._invitationForAppointingOfManager = val;
    }
    
    public get invitationForAppointingOfManager(): fields.F318_InvitationForAppointingOfManager{
        return this._invitationForAppointingOfManager;
    }
     

    @observable private _managerOfTradeEnterprise: fields.F319_ManagerOfTradeEnterprise = null;
    
    @TypeSystem.propertyDecorator(fields.F319_ManagerOfTradeEnterprise)
    public set managerOfTradeEnterprise(val: fields.F319_ManagerOfTradeEnterprise){
        this._managerOfTradeEnterprise = val;
    }
    
    public get managerOfTradeEnterprise(): fields.F319_ManagerOfTradeEnterprise{
        return this._managerOfTradeEnterprise;
    }
     

    @observable private _restoringManagementRight: fields.F320_RestoringManagementRight = null;
    
    @TypeSystem.propertyDecorator(fields.F320_RestoringManagementRight)
    public set restoringManagementRight(val: fields.F320_RestoringManagementRight){
        this._restoringManagementRight = val;
    }
    
    public get restoringManagementRight(): fields.F320_RestoringManagementRight{
        return this._restoringManagementRight;
    }
     

    @observable private _distraintData: fields.F321_DistraintData = null;
    
    @TypeSystem.propertyDecorator(fields.F321_DistraintData)
    public set distraintData(val: fields.F321_DistraintData){
        this._distraintData = val;
    }
    
    public get distraintData(): fields.F321_DistraintData{
        return this._distraintData;
    }
     

    @observable private _raiseDistraint: fields.F322_RaiseDistraint = null;
    
    @TypeSystem.propertyDecorator(fields.F322_RaiseDistraint)
    public set raiseDistraint(val: fields.F322_RaiseDistraint){
        this._raiseDistraint = val;
    }
    
    public get raiseDistraint(): fields.F322_RaiseDistraint{
        return this._raiseDistraint;
    }
     

    @observable private _size323: fields.F323_Size323 = null;
    
    @TypeSystem.propertyDecorator(fields.F323_Size323)
    public set size323(val: fields.F323_Size323){
        this._size323 = val;
    }
    
    public get size323(): fields.F323_Size323{
        return this._size323;
    }
     

    @observable private _stopExecutionOverProperty: fields.F324_StopExecutionOverProperty = null;
    
    @TypeSystem.propertyDecorator(fields.F324_StopExecutionOverProperty)
    public set stopExecutionOverProperty(val: fields.F324_StopExecutionOverProperty){
        this._stopExecutionOverProperty = val;
    }
    
    public get stopExecutionOverProperty(): fields.F324_StopExecutionOverProperty{
        return this._stopExecutionOverProperty;
    }
     

    @observable private _entryIntoPledgeCreditorRights2: fields.F324a_EntryIntoPledgeCreditorRights2 = null;
    
    @TypeSystem.propertyDecorator(fields.F324a_EntryIntoPledgeCreditorRights2)
    public set entryIntoPledgeCreditorRights2(val: fields.F324a_EntryIntoPledgeCreditorRights2){
        this._entryIntoPledgeCreditorRights2 = val;
    }
    
    public get entryIntoPledgeCreditorRights2(): fields.F324a_EntryIntoPledgeCreditorRights2{
        return this._entryIntoPledgeCreditorRights2;
    }
     

    @observable private _eraseDistraint: fields.F325_EraseDistraint = null;
    
    @TypeSystem.propertyDecorator(fields.F325_EraseDistraint)
    public set eraseDistraint(val: fields.F325_EraseDistraint){
        this._eraseDistraint = val;
    }
    
    public get eraseDistraint(): fields.F325_EraseDistraint{
        return this._eraseDistraint;
    }
     

    @observable private _partialEraseDistraint: fields.F325a_PartialEraseDistraint = null;
    
    @TypeSystem.propertyDecorator(fields.F325a_PartialEraseDistraint)
    public set partialEraseDistraint(val: fields.F325a_PartialEraseDistraint){
        this._partialEraseDistraint = val;
    }
    
    public get partialEraseDistraint(): fields.F325a_PartialEraseDistraint{
        return this._partialEraseDistraint;
    }
     

    @observable private _dateOfRenewingDistraint: fields.F326_DateOfRenewingDistraint = null;
    
    @TypeSystem.propertyDecorator(fields.F326_DateOfRenewingDistraint)
    public set dateOfRenewingDistraint(val: fields.F326_DateOfRenewingDistraint){
        this._dateOfRenewingDistraint = val;
    }
    
    public get dateOfRenewingDistraint(): fields.F326_DateOfRenewingDistraint{
        return this._dateOfRenewingDistraint;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('B5Fields', moduleContext.moduleName)
export class B5Fields extends ApplicationFormBFieldsBase { 

    @observable private _distraintIdentifier: fields.F400_DistraintIdentifier = null;
    
    @TypeSystem.propertyDecorator(fields.F400_DistraintIdentifier)
    public set distraintIdentifier(val: fields.F400_DistraintIdentifier){
        this._distraintIdentifier = val;
    }
    
    public get distraintIdentifier(): fields.F400_DistraintIdentifier{
        return this._distraintIdentifier;
    }
     

    @observable private _distraints: fields.F401_Distraints = null;
    
    @TypeSystem.propertyDecorator(fields.F401_Distraints)
    public set distraints(val: fields.F401_Distraints){
        this._distraints = val;
    }
    
    public get distraints(): fields.F401_Distraints{
        return this._distraints;
    }
     

    @observable private _reason403: fields.F403_Reason403 = null;
    
    @TypeSystem.propertyDecorator(fields.F403_Reason403)
    public set reason403(val: fields.F403_Reason403){
        this._reason403 = val;
    }
    
    public get reason403(): fields.F403_Reason403{
        return this._reason403;
    }
     

    @observable private _size404: fields.F404_Size404 = null;
    
    @TypeSystem.propertyDecorator(fields.F404_Size404)
    public set size404(val: fields.F404_Size404){
        this._size404 = val;
    }
    
    public get size404(): fields.F404_Size404{
        return this._size404;
    }
     

    @observable private _interests: fields.F405_Interests = null;
    
    @TypeSystem.propertyDecorator(fields.F405_Interests)
    public set interests(val: fields.F405_Interests){
        this._interests = val;
    }
    
    public get interests(): fields.F405_Interests{
        return this._interests;
    }
     

    @observable private _descriptions: fields.F406_Descriptions = null;
    
    @TypeSystem.propertyDecorator(fields.F406_Descriptions)
    public set descriptions(val: fields.F406_Descriptions){
        this._descriptions = val;
    }
    
    public get descriptions(): fields.F406_Descriptions{
        return this._descriptions;
    }
     

    @observable private _liftingDistraint: fields.F408_LiftingDistraint = null;
    
    @TypeSystem.propertyDecorator(fields.F408_LiftingDistraint)
    public set liftingDistraint(val: fields.F408_LiftingDistraint){
        this._liftingDistraint = val;
    }
    
    public get liftingDistraint(): fields.F408_LiftingDistraint{
        return this._liftingDistraint;
    }
     

    @observable private _size409: fields.F409_Size409 = null;
    
    @TypeSystem.propertyDecorator(fields.F409_Size409)
    public set size409(val: fields.F409_Size409){
        this._size409 = val;
    }
    
    public get size409(): fields.F409_Size409{
        return this._size409;
    }
     

    @observable private _stopExecutionOverProperty410: fields.F410_StopExecutionOverProperty410 = null;
    
    @TypeSystem.propertyDecorator(fields.F410_StopExecutionOverProperty410)
    public set stopExecutionOverProperty410(val: fields.F410_StopExecutionOverProperty410){
        this._stopExecutionOverProperty410 = val;
    }
    
    public get stopExecutionOverProperty410(): fields.F410_StopExecutionOverProperty410{
        return this._stopExecutionOverProperty410;
    }
     

    @observable private _moratoryRate: fields.F404a_MoratoryRate = null;
    
    @TypeSystem.propertyDecorator(fields.F404a_MoratoryRate)
    public set moratoryRate(val: fields.F404a_MoratoryRate){
        this._moratoryRate = val;
    }
    
    public get moratoryRate(): fields.F404a_MoratoryRate{
        return this._moratoryRate;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('B6Fields', moduleContext.moduleName)
export class B6Fields extends ApplicationFormBFieldsBase { 

    @observable private _termsOfLiquidation: fields.F501_TermsOfLiquidation = null;
    
    @TypeSystem.propertyDecorator(fields.F501_TermsOfLiquidation)
    public set termsOfLiquidation(val: fields.F501_TermsOfLiquidation){
        this._termsOfLiquidation = val;
    }
    
    public get termsOfLiquidation(): fields.F501_TermsOfLiquidation{
        return this._termsOfLiquidation;
    }
     

    @observable private _liquidators: fields.F502_Liquidators = null;
    
    @TypeSystem.propertyDecorator(fields.F502_Liquidators)
    public set liquidators(val: fields.F502_Liquidators){
        this._liquidators = val;
    }
    
    public get liquidators(): fields.F502_Liquidators{
        return this._liquidators;
    }
     

    @observable private _representative503: fields.F503_Representative503 = null;
    
    @TypeSystem.propertyDecorator(fields.F503_Representative503)
    public set representative503(val: fields.F503_Representative503){
        this._representative503 = val;
    }
    
    public get representative503(): fields.F503_Representative503{
        return this._representative503;
    }
     

    @observable private _continuingTradeActivity: fields.F504_ContinuingTradeActivity = null;
    
    @TypeSystem.propertyDecorator(fields.F504_ContinuingTradeActivity)
    public set continuingTradeActivity(val: fields.F504_ContinuingTradeActivity){
        this._continuingTradeActivity = val;
    }
    
    public get continuingTradeActivity(): fields.F504_ContinuingTradeActivity{
        return this._continuingTradeActivity;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

@TypeSystem.typeDecorator('B7Fields', moduleContext.moduleName)
export class B7Fields extends ApplicationFormBFieldsBase { 

    @observable private _numberNationalRegister1b: fields.F001b_NumberNationalRegister1b = null;
    
    @TypeSystem.propertyDecorator(fields.F001b_NumberNationalRegister1b)
    public set numberNationalRegister1b(val: fields.F001b_NumberNationalRegister1b){
        this._numberNationalRegister1b = val;
    }
    
    public get numberNationalRegister1b(): fields.F001b_NumberNationalRegister1b{
        return this._numberNationalRegister1b;
    }
     

    @observable private _reasonForEntry529: fields.F529_ReasonForEntry529 = null;
    
    @TypeSystem.propertyDecorator(fields.F529_ReasonForEntry529)
    public set reasonForEntry529(val: fields.F529_ReasonForEntry529){
        this._reasonForEntry529 = val;
    }
    
    public get reasonForEntry529(): fields.F529_ReasonForEntry529{
        return this._reasonForEntry529;
    }
     

    @observable private _offshoreCompany: fields.F531_OffshoreCompany = null;
    
    @TypeSystem.propertyDecorator(fields.F531_OffshoreCompany)
    public set offshoreCompany(val: fields.F531_OffshoreCompany){
        this._offshoreCompany = val;
    }
    
    public get offshoreCompany(): fields.F531_OffshoreCompany{
        return this._offshoreCompany;
    }
     

    @observable private _offshoreTransliteration: fields.F532_OffshoreTransliteration = null;
    
    @TypeSystem.propertyDecorator(fields.F532_OffshoreTransliteration)
    public set offshoreTransliteration(val: fields.F532_OffshoreTransliteration){
        this._offshoreTransliteration = val;
    }
    
    public get offshoreTransliteration(): fields.F532_OffshoreTransliteration{
        return this._offshoreTransliteration;
    }
     

    @observable private _offshoreSeat: fields.F533_OffshoreSeat = null;
    
    @TypeSystem.propertyDecorator(fields.F533_OffshoreSeat)
    public set offshoreSeat(val: fields.F533_OffshoreSeat){
        this._offshoreSeat = val;
    }
    
    public get offshoreSeat(): fields.F533_OffshoreSeat{
        return this._offshoreSeat;
    }
     

    @observable private _offshoreRepresentatives: fields.F534_OffshoreRepresentatives = null;
    
    @TypeSystem.propertyDecorator(fields.F534_OffshoreRepresentatives)
    public set offshoreRepresentatives(val: fields.F534_OffshoreRepresentatives){
        this._offshoreRepresentatives = val;
    }
    
    public get offshoreRepresentatives(): fields.F534_OffshoreRepresentatives{
        return this._offshoreRepresentatives;
    }
     

    @observable private _offshoreWayOfRepresentation: fields.F535_OffshoreWayOfRepresentation = null;
    
    @TypeSystem.propertyDecorator(fields.F535_OffshoreWayOfRepresentation)
    public set offshoreWayOfRepresentation(val: fields.F535_OffshoreWayOfRepresentation){
        this._offshoreWayOfRepresentation = val;
    }
    
    public get offshoreWayOfRepresentation(): fields.F535_OffshoreWayOfRepresentation{
        return this._offshoreWayOfRepresentation;
    }
     

    @observable private _offshoreSpecialConditions: fields.F536_OffshoreSpecialConditions = null;
    
    @TypeSystem.propertyDecorator(fields.F536_OffshoreSpecialConditions)
    public set offshoreSpecialConditions(val: fields.F536_OffshoreSpecialConditions){
        this._offshoreSpecialConditions = val;
    }
    
    public get offshoreSpecialConditions(): fields.F536_OffshoreSpecialConditions{
        return this._offshoreSpecialConditions;
    }
     

    @observable private _offshoreDirectControlCompanies: fields.F537_OffshoreDirectControlCompanies = null;
    
    @TypeSystem.propertyDecorator(fields.F537_OffshoreDirectControlCompanies)
    public set offshoreDirectControlCompanies(val: fields.F537_OffshoreDirectControlCompanies){
        this._offshoreDirectControlCompanies = val;
    }
    
    public get offshoreDirectControlCompanies(): fields.F537_OffshoreDirectControlCompanies{
        return this._offshoreDirectControlCompanies;
    }
     

    @observable private _offshoreDirectControlCompanyRepresentatives: fields.F5371_OffshoreDirectControlCompanyRepresentatives = null;
    
    @TypeSystem.propertyDecorator(fields.F5371_OffshoreDirectControlCompanyRepresentatives)
    public set offshoreDirectControlCompanyRepresentatives(val: fields.F5371_OffshoreDirectControlCompanyRepresentatives){
        this._offshoreDirectControlCompanyRepresentatives = val;
    }
    
    public get offshoreDirectControlCompanyRepresentatives(): fields.F5371_OffshoreDirectControlCompanyRepresentatives{
        return this._offshoreDirectControlCompanyRepresentatives;
    }
     

    @observable private _offshoreNoDirectControlCompanies: fields.F538_OffshoreNoDirectControlCompanies = null;
    
    @TypeSystem.propertyDecorator(fields.F538_OffshoreNoDirectControlCompanies)
    public set offshoreNoDirectControlCompanies(val: fields.F538_OffshoreNoDirectControlCompanies){
        this._offshoreNoDirectControlCompanies = val;
    }
    
    public get offshoreNoDirectControlCompanies(): fields.F538_OffshoreNoDirectControlCompanies{
        return this._offshoreNoDirectControlCompanies;
    }
     

    @observable private _offshoreNoDirectControlCompanyRepresentatives: fields.F5381_OffshoreNoDirectControlCompanyRepresentatives = null;
    
    @TypeSystem.propertyDecorator(fields.F5381_OffshoreNoDirectControlCompanyRepresentatives)
    public set offshoreNoDirectControlCompanyRepresentatives(val: fields.F5381_OffshoreNoDirectControlCompanyRepresentatives){
        this._offshoreNoDirectControlCompanyRepresentatives = val;
    }
    
    public get offshoreNoDirectControlCompanyRepresentatives(): fields.F5381_OffshoreNoDirectControlCompanyRepresentatives{
        return this._offshoreNoDirectControlCompanyRepresentatives;
    }
     

    @observable private _article4: fields.F540_CircumstanceArticle4 = null;
    
    @TypeSystem.propertyDecorator(fields.F540_CircumstanceArticle4)
    public set article4(val: fields.F540_CircumstanceArticle4){
        this._article4 = val;
    }
    
    public get article4(): fields.F540_CircumstanceArticle4{
        return this._article4;
    }
     

    @observable private _actualOwners: fields.F550_ActualOwners = null;
    
    @TypeSystem.propertyDecorator(fields.F550_ActualOwners)
    public set actualOwners(val: fields.F550_ActualOwners){
        this._actualOwners = val;
    }
    
    public get actualOwners(): fields.F550_ActualOwners{
        return this._actualOwners;
    }
     

    @observable private _contactPerson550a: fields.F550a_ContactPerson550a = null;
    
    @TypeSystem.propertyDecorator(fields.F550a_ContactPerson550a)
    public set contactPerson550a(val: fields.F550a_ContactPerson550a){
        this._contactPerson550a = val;
    }
    
    public get contactPerson550a(): fields.F550a_ContactPerson550a{
        return this._contactPerson550a;
    }
     

    @observable private _eraseActualOwner: fields.F551_EraseActualOwner = null;
    
    @TypeSystem.propertyDecorator(fields.F551_EraseActualOwner)
    public set eraseActualOwner(val: fields.F551_EraseActualOwner){
        this._eraseActualOwner = val;
    }
    
    public get eraseActualOwner(): fields.F551_EraseActualOwner{
        return this._eraseActualOwner;
    }
     

    constructor(obj?: any){
        super(obj)

        this.copyFrom(obj);
    }
}

























