<?php
$this->headTitle($pageTitle);
?>
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="<?=$this->url('home')?>"><?=$this->translate('GL_HOME_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_GL_PAYMENTS')?></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate($pageTitle)?></li>
	</ol>
</nav>

<div class="page-title">
	<h2><?=$this->translate($pageTitle)?></h2>
</div>

<div class="card">

	<?php
	$registryAgencyForm->setAttribute('action', $this->url('edit_registry_agency_data_'.$params->fromRoute('registryAgencyType'), ['lang' => $params->fromRoute('lang'), 'registryAgencyType' => $params->fromRoute('registryAgencyType')]));
	$registryAgencyForm->setAttribute('id', 'registry-agency-data-form');
	$registryAgencyForm->prepare();

	echo $this->form()->openTag($registryAgencyForm);
	?>

	<div class="card-body">

		<?=$this->partial('partial/messages.phtml')?>

		<div class="row">

			<div class="col-sm-6 form-group">
				<?=$this->formRow($registryAgencyForm->get('cin')->setLabel($lblCin))?>
			</div>

			<div class="col-sm-6 form-group">
				<?=$this->formRow($registryAgencyForm->get('secretWord')->setLabel($lblSecretWord))?>
			</div>

			<div class="col-sm-6 form-group">
				<? if ($registryAgencyType == 'epay') { ?>
					<?=$this->formRow($registryAgencyForm->get('email'))?>
				<? }
				else { ?>
					<?=$this->formRow($registryAgencyForm->get('urlResponse'))?>
				<? } ?>
			</div>

			<div class="col-sm-6">
				<label class="required-field"><?=$this->translate('EP_PAY_POV_PAYMENT_L')?></label>
				<div class="row">
					<div class="col-sm-7 col-md-7 col-lg-5 col-xl-4 form-group">
						<div class="input-group date" id="validityPeriod" data-target-input="nearest">
							<?=$this->formRow($registryAgencyForm->get('validityPeriod'), null, false)?>
							<div class="input-group-append" data-target="#validityPeriod" data-toggle="datetimepicker">
								<button class="btn btn-secondary" type="button">
									<i class="ui-icon ui-icon-clock"></i>
								</button>
							</div>
							<?=$this->FormElementErrors($registryAgencyForm->get('validityPeriod'))?>
						</div>
					</div>
				</div>
			</div>

			<div class="col-sm-6 form-group">
				<?=$this->formRow($registryAgencyForm->get('url'), null, true, '')?>
			</div>

			<div class="col-sm-6 form-group">
				<? if ($registryAgencyType == 'pep') { ?>
					<?=$this->formRow($registryAgencyForm->get('urlServices'), null, true, '')?>
				<? } ?>
			</div>

		</div>

	</div>

	<div class="card-footer">
		<div class="button-bar">

			<div class="left-side"></div>
			<div class="right-side">
				<?=$this->formSubmit($registryAgencyForm->get('submit'));?>
			</div>
		</div>
	</div>

	<?=$this->form()->closeTag();?>

</div>

<?$this->headLink()->appendStylesheet($this->basePath('js/bootstrap-4-datepicker/css/tempusdominus-bootstrap-4.min.css'));?>
<?$this->headScript()->prependFile($this->basePath('js/bootstrap-4-datepicker/js/tempusdominus-bootstrap-4.min.js'));?>
<?$this->headScript()->prependFile($this->basePath('js/moment-with-locales.min.js'));?>

<script>

$(function () {
	$('#validityPeriod').datetimepicker({
		useCurrent: false,
		format: "HH:mm:ss",
		locale: moment.locale('bg')
	});
});
</script>

<script>
$(document).on('submit', '#registry-agency-data-form', function(){
	showGlobalLoader();
});
</script>
