import { RecordValidator } from 'EPZEU.CR.Domain';
import { F051a_BranchFirm } from '../ModelsAutoGenerated';

export class F051a_BranchFirmValidator extends RecordValidator<F051a_BranchFirm> {
    constructor() {
        super();

        this.ruleFor(m => m.text).notEmpty().withMessage(this.getMessage('GL_INPUT_FIELD_MUST_E'));
        this.ruleFor(m => m.text).matches('^(?:(?![ЫЭыэ])[А-Яа-я0-9-~@#$%^&*()_+{}|":><.,/?\';=|!\\\\ ])+$').withMessage(this.getMessage('GL_INPUT_CIRILIC_MUST_E'));
    }

    public validateInternal(obj: F051a_BranchFirm): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}