import { RecordValidator } from 'EPZEU.CR.Domain';
import { F052a_MainActivityNKID } from '../ModelsAutoGenerated';

export class F052a_MainActivityNKIDValidator extends RecordValidator<F052a_MainActivityNKID> {
    constructor() {
        super();
    }

    public validateInternal(obj: F052a_MainActivityNKID): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}