import { RecordValidator } from 'EPZEU.CR.Domain';
import { F212_PledgeMoney } from '../ModelsAutoGenerated';

export class F212_PledgeMoneyValidator extends RecordValidator<F212_PledgeMoney> {

    public validateInternal(obj: F212_PledgeMoney): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}