import { ObjectHelper } from 'Cnsys.Core';
import { RecordValidator } from 'EPZEU.CR.Domain';
import { F213_PledgePropertyDescription } from '../ModelsAutoGenerated';

export class F213_PledgePropertyDescriptionValidator extends RecordValidator<F213_PledgePropertyDescription> {

    public validateInternal(obj: F213_PledgePropertyDescription): boolean {
        let isValid = super.validateInternal(obj);

        if (ObjectHelper.isStringNullOrEmpty(obj.capital) || !obj.corporateShare && !obj.partOfCorporateShare) {
            obj.addError(this.getMessage('CR_APP_00141_E')); //Изберете между дружествен дял или част от дружествен дял и попълнете част от капитала, на която съответства заложеният дял или частта от дружествения дял при ООД.

            isValid = false;
        }

        return isValid;
    }
}