import { RecordValidator } from 'EPZEU.CR.Domain';
import { F216a_PledgedCreditorAgreement } from '../ModelsAutoGenerated';

export class F216a_PledgedCreditorAgreementValidator extends RecordValidator<F216a_PledgedCreditorAgreement> {
    constructor() {
        super();
    }

    public validateInternal(obj: F216a_PledgedCreditorAgreement): boolean {
        let isValid = super.validateInternal(obj);
        return isValid;
    }
}