import { RecordValidator } from 'EPZEU.CR.Domain';
import { F216_ModalityCondition } from '../ModelsAutoGenerated';

export class F216_ModalityConditionValidator extends RecordValidator<F216_ModalityCondition> {

    public validateInternal(obj: F216_ModalityCondition): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}