import { RecordValidator } from 'EPZEU.CR.Domain';
import { F307_Size307 } from '../ModelsAutoGenerated';

export class F307_Size307Validator extends RecordValidator<F307_Size307> {

    constructor() {
        super();
    }

    public validateInternal(obj: F307_Size307): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}