import { RecordValidator } from 'EPZEU.CR.Domain';
import { F324_StopExecutionOverProperty } from '../ModelsAutoGenerated';

export class F324_StopExecutionOverPropertyValidator extends RecordValidator<F324_StopExecutionOverProperty> {

    constructor() {
        super();
    }

    public validateInternal(obj: F324_StopExecutionOverProperty): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}