import { ObjectHelper } from 'Cnsys.Core';
import { RecordValidator, ValidatorHelpers } from 'EPZEU.CR.Domain';
import { F326_DateOfRenewingDistraint } from '../ModelsAutoGenerated';

export class F326_DateOfRenewingDistraintValidator extends RecordValidator<F326_DateOfRenewingDistraint> {

    constructor() {
        super();

        this.ruleFor(m => m.date).must(m => ValidatorHelpers.isValidDate(m.date)).withMessage(this.getMessage('GL_INPUT_DATE_E')).when(m => !ObjectHelper.isStringNullOrEmpty(m.date));
    }

    public validateInternal(obj: F326_DateOfRenewingDistraint): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}