import { RecordValidator } from 'EPZEU.CR.Domain';
import { F408_LiftingDistraint } from '../ModelsAutoGenerated';

export class F408_LiftingDistraintValidator extends RecordValidator<F408_LiftingDistraint> {
    constructor() {
        super();
    }

    public validateInternal(obj: F408_LiftingDistraint): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}