import { ObjectHelper } from 'Cnsys.Core';
import { RecordValidator, ValidatorHelpers } from 'EPZEU.CR.Domain';
import { F501_TermsOfLiquidation } from '../ModelsAutoGenerated';

export class F501_TermsOfLiquidationValidator extends RecordValidator<F501_TermsOfLiquidation> {
    constructor() {
        super();

        this.ruleFor(m => m.date).must(m => ValidatorHelpers.isValidDate(m.date)).withMessage(this.getMessage('GL_INPUT_DATE_E')).when(m => !ObjectHelper.isStringNullOrEmpty(m.date));
    }

    public validateInternal(obj: F501_TermsOfLiquidation): boolean {
        let isValid = super.validateInternal(obj);

        if (ObjectHelper.isStringNullOrEmpty(obj.date)
            && ObjectHelper.isStringNullOrEmpty(obj.termType)) {
            obj.addError(this.getMessage('GL_INPUT_FIELD_MUST_E'));
            isValid = false;
        }

        return isValid;
    }
}