import { ContactsAddressValidator, RecordValidator, SimpleAddressValidator } from 'EPZEU.CR.Domain';
import { F533_OffshoreSeat } from '../ModelsAutoGenerated';

export class F533_OffshoreSeatValidator extends RecordValidator<F533_OffshoreSeat> {
    constructor() {
        super();

        this.ruleFor(m => m.address).setValidator(new SimpleAddressValidator());
        this.ruleFor(m => m.contacts).setValidator(new ContactsAddressValidator);
    }

    public validateInternal(obj: F533_OffshoreSeat): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}