import { RecordValidator } from 'EPZEU.CR.Domain';
import { F536_OffshoreSpecialConditions } from '../ModelsAutoGenerated';

export class F536_OffshoreSpecialConditionsValidator extends RecordValidator<F536_OffshoreSpecialConditions> {
    constructor() {
        super();
    }

    public validateInternal(obj: F536_OffshoreSpecialConditions): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}