<? $this->headTitle('EP_PAY_REVIEW_PAY_REQ_L') ?>

<div class="page-header-wrapper">
	<div class="breadcrumbs">
		<div class="fixed-content-width">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="<?=$this->url('home', ['lang' => $this->language()->getCurrentLang()])?>"><?=$this->translate('GL_HOME_L')?></a></li>
					<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_PAY_REVIEW_PAY_REQ_L')?></li>
				</ol>
			</nav>
		</div>
	</div>
	<div class="section-wrapper">
		<div class="fixed-content-width">
			<div class="page-header">
				<div class="row">
					<div class="col">
						<h1 class="page-title"><?=$this->translate('EP_PAY_REVIEW_PAY_REQ_L')?></h1>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="main-wrapper section-wrapper section-wrapper--margins fixed-content-width">

	<div class="page-wrapper">

		<ul class="nav nav-tabs flex-column flex-sm-row flex-nowrap">
			<? foreach ($registerList as $id => $register) { ?>
				<li class="nav-item <?=($selectedRegisterId == $id ? 'active': '')?> tab-register">
					<a href="javascript://" class="nav-link <?=($selectedRegisterId == $id ? 'active': '')?>" id="tab_<?=$id?>"><?=$this->translate('GL_'.$register.'_REG_NAME_L'.($register == 'CR' ? '_SHORT_L' : ''))?></a>
				</li>
			<? } ?>
		</ul>

		<div class="section-wrapper">
			<div id="tab-register-content">
			<?=$this->partial('duty-list-section.phtml')?>
			</div>
		</div>

	</div>

</div>

<?$this->headScript()->prependFile($this->basePath('js/combobox.js'));?>
<?$this->headScript()->prependFile($this->basePath('js/jquery-ui.js'));?>

<?$this->headLink()->appendStylesheet($this->basePath('js/bootstrap-4-datepicker/css/tempusdominus-bootstrap-4.min.css'));?>
<?$this->headScript()->prependFile($this->basePath('js/bootstrap-4-datepicker/js/tempusdominus-bootstrap-4.min.js'));?>
<?$this->headScript()->prependFile($this->basePath('js/moment-with-locales.min.js'));?>

<?$this->headScript()->appendFile($this->basePath('/js/jquery.twbsPagination.js'), 'text/javascript');?>
<?$this->headScript()->appendFile($this->basePath('/js/paginator.js'), 'text/javascript');?>

<?=$this->partial('partial/modal-preview.phtml', ['title' => $this->translate('EP_PAY_PAYMENT_ORDERS_L'), 'showBtnRight' => 1, 'btnRightClass' => 'btn-secondary'])?>
<div id="modalPayment"></div>

<script>
$('.tab-register').on("click", function(e){

	var selectedRegisterId = $(this).find('a:first').attr('id').replace('tab_', '');

	$('.nav-link').removeClass('active');
	$('.nav-item').removeClass('active');

	$('#tab_'+selectedRegisterId).addClass('active');
	$('#tab_'+selectedRegisterId).closest('.nav-item').addClass('active');

	$("#registerId").val(selectedRegisterId);

	$("#selectedApplicationList").empty();

	$("#count-selected-application-pay").text(0);

	history.pushState(null, null, createQuery({registerId:selectedRegisterId}, {page: 'page', search: 'search', applicationNumber: 'applicationNumber', dateFrom: 'dateFrom', dateTo: 'dateTo', applicationTypeId: 'applicationTypeId', isUnpaidDuty: 'isUnpaidDuty'}));

	ajaxRequest('', {'changeRegisterTab':1, 'registerId': selectedRegisterId}, '#tab-register-content', '#tab-register-content');
})
</script>