<div class="field-container">
	<div class="row">
		<div class="col">
			<div class="help-text"><?=$this->translate('EP_PAY_00003_I')?></div>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<label class="field-title field-title--form required-field" for=""><?=$this->translate('GL_VALUE_L')?></label>
		</div>
	</div>
	<div class="row">
		<div class="form-group col-8 col-sm-6 col-md-3">
			<div class="form-row">
				<div class="col">
					<input class="form-control text-right" type="text" name="sumPersonalAccount" id="sumPersonalAccount" value="" maxlength="8">
				</div>
				<div class="col-auto">
					<label class="col-form-label"><?=$this->translate('GL_BGN_ABBRAVETION_L')?></label>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="field-container">
	<div class="row">
		<div class="col-12">
			<label class="field-title field-title--form required-field">
				<?=$this->translate('EP_CHOICE_PAYMENT_METHOD_L')?>
			</label>
		</div>
	</div>
	<div class="row">
		<div class="col-12 form-group" id="paymentSection">
			<div class="custom-control custom-radio">
				<input class="custom-control-input" checked="checked" name="paymentMethod" id="epay" value="epay" type="radio">
				<label class="custom-control-label" for="epay"><?=$this->translate('EP_EPAY_L')?></label>
			</div>

			<!--
			<div class="custom-control custom-radio ">
				<input class="custom-control-input" name="paymentMethod" id="pepdaeu" value="pepdaeu" type="radio">
				<label class="custom-control-label" for="pepdaeu"><?=$this->translate('EP_PEPDAEU_L')?></label>
			</div>
			-->
		</div>
	</div>
</div>

<div id="obligPersonSection" class="field-container d-none">

	<div class="row">
		<div class="form-group col-md-6">
			<label class="field-title field-title--form required-field" for=""><?=$this->translate('EP_NAME_OBL_PERS_L')?></label>
			<input type="text" class="form-control" name="obligPerson" id="obligPerson" value="<?=$obligPerson?>">
		</div>
	</div>

	<div class="row">
		<div class="form-group col-md-6">
			<label class="field-title field-title--form required-field" for=""><?=$this->translate('EP_ORDERER_IDENT_L')?></label>
			<input type="text" class="form-control" name="obligPersonIdentity" id="obligPersonIdentity" value="" maxlength="10">
		</div>
		<div class="form-group col-md-6">
			<label class="field-title field-title--form required-field" for=""><?=$this->translate('EP_KIND_IDENT_L')?></label>
			<div class="form-inline" id="identityKindSection">
				<div class="custom-control-inline custom-control custom-radio">
					<input class="custom-control-input" name="obligPersonIdentityKind" id="egn" value="1" type="radio">
					<label class="custom-control-label" for="egn"><?=$this->translate('GL_BULGARIAN_PERSON_ID_L')?></label>
				</div>
				<div class="custom-control-inline custom-control custom-radio">
					<input class="custom-control-input" name="obligPersonIdentityKind" id="lnc" value="2" type="radio">
					<label class="custom-control-label" for="lnc"><?=$this->translate('GL_FOREIGN_PERSON_ID_L')?></label>
				</div>
				<div class="custom-control-inline custom-control custom-radio">
					<input class="custom-control-input" name="obligPersonIdentityKind" id="bulstat" value="3" type="radio">
					<label class="custom-control-label" for="bulstat"><?=$this->translate('EP_GL_UIC_BULSTAT_L')?></label>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="generateCodePEPDAEU" class="field-container  d-none">
	<div class="help-text"><p><?=$this->translate('EP_PAY_00013_I')?></p></div>
	<div  class="row">
		<div class="form-group col-12">
			<button id="generateCodePEPDAUE" class="btn btn-outline-light text-dark" type="button"><i class="ui-icon ui-icon-number" aria-hidden="true"></i> <?=$this->translate('EP_PAY_GEN_CODE_L')?></button>
		</div>
	</div>
</div>

<div id="viewCodePEPDAEU" class="field-container d-none">
	<div class="help-text"><p><?=$this->translate('EP_PAY_00014_I')?></p></div>
	<div class="row">
		<div class="form-group col-12">
			<label class="field-title field-title--form" for=""><?=$this->translate('EP_PAY_CODE_PEP_L')?></label>
			<p class="field-text" id="codePEPDAEU"></p>
			<input id="pepdaeuNumber" name="pepdaeuNumber" type="hidden" value="0">
		</div>
	</div>
</div>

<div id="formSection">
	<form method="POST" name="epayForm" id="epayForm" style="display: block;">
		<input type=hidden name=PAGE value="">
		<input type=hidden name=ENCODED value="">
		<input type=hidden name=CHECKSUM value="">
		<input type=hidden name=URL_OK value="">
		<input type=hidden name=URL_CANCEL value="">
	</form>
</div>

<script>

//
$(document).ready(function(){
	$('#obligPersonSection').removeClass("d-none");
})

// Избрано ePay
$('#epay').on('click', function () {

	$('#generateCodePEPDAEU').addClass("d-none");
	$('#viewCodePEPDAEU').addClass("d-none");
	$('#pepdaeuNumber').val("0");

	$('.invalid-feedback').remove();
	$('#obligPersonSection').removeClass("d-none");
});

//Избрано ПЕПДАЕУ
$('#pepdaeu').on('click', function () {

	$('#generateCodePEPDAEU').removeClass("d-none");
	$('#viewCodePEPDAEU').addClass("d-none");
	$('#pepdaeuNumber').val("0");

	$('.invalid-feedback').remove();
	$('#obligPersonSection').removeClass("d-none");
});

$('#confirmPaymentBtn').unbind('click').bind('click', function () {

	$(this).removeAttr('data-dismiss');

	$('.invalid-feedback').remove();
	$('input[type="text"]').removeClass('input-error');

	var registerId = '<?=$registerId?>';

	var paymentMethod = $('input[name="paymentMethod"]:checked').val();

	var sumPersonalAccount = $("#sumPersonalAccount").val();

	var obligPerson = $("#obligPerson").val();

	// плащане към epay или към пепдаеу
	if (paymentMethod == 'epay' || paymentMethod == 'pepdaeu') {

		showGlobalLoader();

		// плащане към epay
		if (paymentMethod == 'epay') {

			var obligPersonIdentityKind = $('input[name="obligPersonIdentityKind"]:checked').val();

			var obligPersonIdentity = $("#obligPersonIdentity").val();

			var data ={"paymentMethod" : paymentMethod, "registerId" : registerId, "sumPersonalAccount" : sumPersonalAccount, "obligPerson" : obligPerson, "obligPersonIdentity" : obligPersonIdentity, "obligPersonIdentityKind" : obligPersonIdentityKind};
		}

		// плащане към пепдаеу
		else if (paymentMethod == 'pepdaeu') {

			var codePepdaeu = $('#codePEPDAEU').html();
			var numberPepdeau = $('#pepdaeuNumber').val();

			var obligPersonIdentityKind = $('input[name="obligPersonIdentityKind"]:checked').val();

			var obligPersonIdentity = $("#obligPersonIdentity").val();

			var data ={"paymentMethod" : paymentMethod, "registerId" : registerId, "sumPersonalAccount" : sumPersonalAccount, "obligPerson" : obligPerson, "obligPersonIdentity" : obligPersonIdentity, "obligPersonIdentityKind" : obligPersonIdentityKind, 'codePepdaeu' : codePepdaeu, 'numberPepdeau': numberPepdeau};
		}

		$.ajax({
			method: "POST",
			url: (paymentMethod == 'epay') ? '<?=$this->url('epay_payment_power_personal_account',['lang' => $this->language()->getCurrentLang()])?>' : '<?=$this->url('pepdaeu_payment_power_personal_account')?>',
			data: data,
			async: true
		})
		.fail(function(jqXHR, textStatus, errorThrown) {
			location.reload();
		})
		.done(function(msg) {

			var obj = jQuery.parseJSON(JSON.stringify(msg));

			if (obj.hasOwnProperty('status')) {

				switch(obj.status) {
					case 'success':

						closeGlobalLoader();

						if (obj.paymentMethod == 'epay') {

							$("#epayForm").attr('action', obj.epayData['URL']);

							$("#epayForm input[name=PAGE]").val("");
							$("#epayForm input[name=ENCODED]").val("");
							$("#epayForm input[name=CHECKSUM]").val("");
							$("#epayForm input[name=URL_OK]").val("");
							$("#epayForm input[name=URL_CANCEL]").val("");

							$("#epayForm input[name=PAGE]").val(obj.epayData['PAGE']);
							$("#epayForm input[name=ENCODED]").val(obj.epayData['ENCODED']);
							$("#epayForm input[name=CHECKSUM]").val(obj.epayData['CHECKSUM']);
							$("#epayForm input[name=URL_OK]").val(obj.epayData['URL_OK']);
							$("#epayForm input[name=URL_CANCEL]").val(obj.epayData['URL_CANCEL']);

							$("#epayForm").submit();
						}

						else if (obj.paymentMethod == 'pepdaeu') {
							window.location.replace(obj.urlToRedirect);
						}

						$('#confirmPaymentBtn').attr('data-dismiss', 'modal');
						$("#modal-payment .close").click();

						break;

					case 'error':

						closeGlobalLoader();

						for (var i = 0; i < obj.errors.length; i++) {
						    var key = Object.keys(obj.errors[i])[0];
						    var message = createErrorMessage(obj.errors[i][key]);

							if (key != 0) {
						    	$('#'+key+' .invalid-feedback').remove();

						    	if ($('#'+key).is('input')) {
						    		$('#'+key).addClass("input-error");
						    	}

						    	$(message).insertAfter('#'+key);
							}

							else {
								$('.invalid-feedback').remove();
								$(".modal-body").prepend(message);
							}
						}

						break;
				}
			}
		});
	}

	// няма избран начин на плащане
	else {
		var message = createErrorMessage('<?=$this->translate('GL_INPUT_FIELD_MUST_E')?>');
		$('.invalid-feedback').remove();
		$("#paymentSection").append(message);
	}
})


// генериране на код ПЕПДАЕУ
$("#generateCodePEPDAUE").unbind('click').bind('click', function () {

	$('#pepdaeuNumber').val("0");

	var paymentMethod = $('input[name="paymentMethod"]:checked').val();

	// плащане пепдаеу
	if (paymentMethod == 'pepdaeu') {

		showGlobalLoader();

		$(this).removeAttr('data-dismiss');

		$('.invalid-feedback').remove();
		$('input[type="text"]').removeClass('input-error');

		var registerId = '<?=$registerId?>';

		var paymentMethod = $('input[name="paymentMethod"]:checked').val();

		var sumPersonalAccount = $("#sumPersonalAccount").val();

		var obligPerson = $("#obligPerson").val();

		var obligPersonIdentityKind = $('input[name="obligPersonIdentityKind"]:checked').val();

		var obligPersonIdentity = $("#obligPersonIdentity").val();

		var data ={"paymentMethod" : paymentMethod, "registerId" : registerId, "sumPersonalAccount" : sumPersonalAccount, "obligPerson" : obligPerson, "obligPersonIdentity" : obligPersonIdentity, "obligPersonIdentityKind" : obligPersonIdentityKind};

		$.ajax({
			method: "POST",
			url: '<?=$this->url('pepdaeu_pay_power_generate_code')?>',
			data: data,
			async: true
		})
		.fail(function(jqXHR, textStatus, errorThrown) {
			location.reload();
		})
		.done(function(msg) {

			var obj = jQuery.parseJSON(JSON.stringify(msg));

			if (obj.hasOwnProperty('status')) {

				switch(obj.status) {
					case 'success':

						closeGlobalLoader();

						$('#generateCodePEPDAEU').addClass("d-none");
						$('#viewCodePEPDAEU').removeClass("d-none");

						$('#codePEPDAEU').html(obj.codePepdaeu);
						$('#pepdaeuNumber').val(obj.numberPepdaeu);

						break;

					case 'error':

						closeGlobalLoader();

						for (var i = 0; i < obj.errors.length; i++) {
						    var key = Object.keys(obj.errors[i])[0];
						    var message = createErrorMessage(obj.errors[i][key]);

							if (key != 0) {
						    	$('#'+key+' .invalid-feedback').remove();

						    	if ($('#'+key).is('input')) {
						    		$('#'+key).addClass("input-error");
						    	}

						    	$(message).insertAfter('#'+key);
							}

							else {
								$('.invalid-feedback').remove();
								$(".modal-body").prepend(message);
							}
						}

						break;
				}
			}
		});
	}
})
</script>