<?php
$class = '';
$disabled = '';
?>

<div class="row">
	<div class="col-12">

		<? if (isset($sectionLabel)) { ?>
		<label><?=$sectionLabel?></label>
		<? } ?>

		<ul id="file-list" class="custom-file-list">
			<?php

			// News
			if (isset($uploadedFileList) && $uploadedFileList->count()) {
				foreach ($uploadedFileList as $fileObj) {
					if (isset($deletedFiles) && is_array($deletedFiles) && in_array($fileObj->getDocId(), $deletedFiles))
						continue; ?>

					<li class="input-group" data-file-name="<?=$fileObj->getDocId()?>">
						<div class="form-control">
							<i class=" mr-2 ui-icon ui-icon-processed" aria-hidden="true"></i>
							<a href="<?=$this->url('load_news_document', ['fileId' => $fileObj->getDocId()])?>">
								<?=\Document\service\DocumentService::getOriginalFilename($fileObj->getFileName())?>
							</a>
						</div>
						<div class="input-group-append">
							<button class="btn btn-secondary delete-file" onClick="deleteUploadedFile('<?=$fileObj->getDocId()?>')" title="<?=$this->escapeHtmlAttr($this->translate('GL_DELETE_L'))?>" type="button">
								<i class="ui-icon ui-icon-trash" aria-hidden="true"></i>
							</button>
						</div>
					</li>
				<?php
				}
			}

			// Video Tutorials
			elseif(isset($videoLessonObj) && $isDeletedOriginalFile) {
				$class = 'd-none';
				?>
					<li class="input-group" data-uuid="<?=$videoLessonObj->getLessonId()?>">
						<div class="form-control">
							<i class=" mr-2 ui-icon ui-icon-processed" aria-hidden="true"></i>
							<?
							$routeParamArr['lessonId'] = $videoLessonObj->getLessonId();

							if (isset($lang))
								$routeParamArr['lang'] = $lang;

							if (isset($translatedFile))
								$routeParamArr['translatedFile'] = 1;

							?>
							<a href="<?=$this->url('video_lesson_file_download', $routeParamArr)?>">
								<?=\Document\service\DocumentService::getOriginalFilename((isset($translatedFile) ? $videoLessonObj->getFileNameI18n() : $videoLessonObj->getFileName()))?>
							</a>
						</div>
						<div class="input-group-append">
							<button class="btn btn-secondary delete-file" onClick="deleteFile('<?=$videoLessonObj->getLessonId()?>')" title="<?=$this->escapeHtmlAttr($this->translate('GL_DELETE_L'))?>" type="button">
								<i class="ui-icon ui-icon-trash" aria-hidden="true"></i>
							</button>
						</div>
					</li>



				<?php
			}

			elseif (isset($nestedPageObj) && !$isDeletedOriginalFile) {
				$class = 'd-none';
				?>
				<li class="input-group" data-uuid="<?=$nestedPageObj->getPageId()?>">
					<div class="form-control">
						<i class=" mr-2 ui-icon ui-icon-processed" aria-hidden="true"></i>
						<a href="<?=$this->url('nested_page_file_download', ['fileId' => $nestedPageObj->getPageId()])?>">
							<?=\Document\service\DocumentService::getOriginalFilename($nestedPageObj->getFileName())?>
						</a>
					</div>
					<div class="input-group-append">
						<button class="btn btn-secondary delete-file" onClick="deleteFile('<?=$nestedPageObj->getPageId()?>')" title="<?=$this->escapeHtmlAttr($this->translate('GL_DELETE_L'))?>" type="button">
							<i class="ui-icon ui-icon-trash" aria-hidden="true"></i>
						</button>
					</div>
				</li>
			<?
			}

			// Бюлетин
			elseif(isset($bulletinObj) && $isDeletedOriginalFile) {
				$class = 'd-none';
				?>
					<li class="input-group" data-uuid="<?=$bulletinObj->getBulletinId()?>">
						<div class="form-control">
							<i class=" mr-2 ui-icon ui-icon-processed" aria-hidden="true"></i>
							<?
							$routeParamArr['bulletinId'] = $bulletinObj->getBulletinId();

							if (isset($lang))
								$routeParamArr['lang'] = $lang;
							?>
							<a href="<?=$this->url('bulletin_file_download', $routeParamArr)?>">
								<?=\Document\service\DocumentService::getOriginalFilename($bulletinObj->getFileName())?>
							</a>
						</div>
						<div class="input-group-append">
							<button class="btn btn-secondary delete-file" onClick="deleteFile('<?=$bulletinObj->getBulletinId()?>')" title="<?=$this->escapeHtmlAttr($this->translate('GL_DELETE_L'))?>" type="button">
								<i class="ui-icon ui-icon-trash" aria-hidden="true"></i>
							</button>
						</div>
					</li>
			<?php
			}

			// Статистика
			elseif(isset($statisticReportObj) && $isDeletedOriginalFile) {
				?>
					<li class="input-group" data-uuid="<?=$statisticReportObj->getStatisticReportId()?>">
						<div class="form-control">
							<i class=" mr-2 ui-icon ui-icon-processed" aria-hidden="true"></i>
							<?
							$routeParamArr['statisticReportId'] = $statisticReportObj->getStatisticReportId();

							if (isset($lang))
								$routeParamArr['lang'] = $lang;
							?>
							<a href="<?=$this->url('statistic_report_file_download', $routeParamArr)?>">
								<?=\Document\service\DocumentService::getOriginalFilename($statisticReportObj->getFileName())?>
							</a>
						</div>
						<div class="input-group-append">
							<button class="btn btn-secondary delete-file" onClick="deleteFile('<?=$statisticReportObj->getStatisticReportId()?>')" title="<?=$this->escapeHtmlAttr($this->translate('GL_DELETE_L'))?>" type="button">
								<i class="ui-icon ui-icon-trash" aria-hidden="true"></i>
							</button>
						</div>
					</li>
			<?php
			}

			if (!empty($fileArr)) {
				foreach ($fileArr as $file) {
					$fileData = json_decode($file['value']);



				?>
				<li class="input-group" data-uuid="<?=$fileData->uuid?>">
					<div class="form-control">
						<i class=" mr-2 ui-icon ui-icon-processed" aria-hidden="true"></i><?=$this->escapeHtml($fileData->originName)?>
					</div>
					<div class="input-group-append">
						<button class="btn btn-secondary delete-file" onClick="deleteFile('<?=$this->escapeHtml($fileData->uuid)?>')" title="<?=$this->escapeHtmlAttr($this->translate('GL_DELETE_L'))?>" type="button">
							<i class="ui-icon ui-icon-trash" aria-hidden="true"></i>
						</button>
					</div>
				</li>
			<?php
				}
			}
			?>
		</ul>

		<p class="text-danger file-error"><?=$this->translate('GL_FILE_UPLOAD_ERROR_I')?>:</p>
		<ul id="file-error" class="custom-file-list">
		</ul>
	</div>
</div>

<div class="row">
<?php
if (isset($setCustomName) && $setCustomName) {
	$class = 'disabled';
	$disabled = 'disabled="disabled"'; ?>

	<div class="col-12 input-group">
		<?=$this->translate('GL_NAME_L');?>
	</div>
	<div class="col-12 input-group btn-group">
		<input type="text" class="file-input form-control" name="fileName" maxlength="90" id="customFileName">
	<?php } ?>

	<?php
	$multiple = 'multiple="multiple"';

	if ((isset($singleFile) && $singleFile) || (isset($setCustomName)))
		$multiple = '';
	?>


	<?php if (!isset($setCustomName)) { ?>
	<div class="col-12 input-group">
	<?php } ?>

	<div class="custom-file-button btn btn-secondary upload-file-section rounded-right <?=$class?>">
		<i class="ui-icon ui-icon-upload" aria-hidden="true"></i>&nbsp;<?=$this->translate('EP_USR_UPLOAD_FILE_L')?>
		<input class="custom-file-input" id="fileInput" <?=$multiple?> <?=$disabled?> type="file" title="<?=$this->escapeHtmlAttr($this->translate('EP_USR_UPLOAD_FILE_L'))?>" />
	</div>

	<?php if (!isset($setCustomName)) { ?>
	</div>
	<?php } ?>

	<?=$this->partial('partial/modal-alert.phtml',['modalId' => 'uploadFile'])?>

	<?php if (isset($setCustomName) && $setCustomName) { ?>
	</div>
	<?php } ?>
</div>

<script type="text/javascript">
<? if (isset($setCustomName) && $setCustomName) { ?>

	$('#customFileName').on('input', function(){
		if (this.value.length) {
			$('#fileInput').prop('disabled', false);
			$('.upload-file-section').removeClass('disabled');
		}
		else {
			$('#fileInput').prop('disabled', true);
			$('.upload-file-section').addClass('disabled');
		}
	});


	$(document).on('change', "#files", function(){
		$('#customFileName').val('');
		$('#fileInput').prop('disabled', true);
		$('.upload-file-section').addClass('disabled');
	});

<? } ?>

ii = 1;
$('#fileInput').on('change', function (e) {

	$("#file-error").find('li').remove();
	$("#file-error, .file-error").hide();

	var nextElement = $("#files").next();

	if ($(nextElement).is('ul') && $(nextElement).hasClass('invalid-feedback')) {
		$(nextElement).remove();
	}


	var files = $('#fileInput')[0].files;

	for (var i = 0; file = files[i]; i++) {

		<? if (isset($maxFileSize)) { ?>

		var fileSize = file.size;

		var maxFileSizeInBytes = <?=$maxFileSize?>*1000;

		if (fileSize > maxFileSizeInBytes) {

			<? if (isset($uploadUrl)) { ?>

			switch ('<?=$uploadUrl?>') {
				case 'upload_video_file':

					var message = '<?=$this->translate('EP_CMS_VIDEO_MAX_FILE_SIZE_E')?>';
					var message = message.replace("{EP_CMS_VIDEO_MAX_FILE_SIZE}", <?=$maxFileSize?>);
					$('#file-error').append('<li>'+file.name+'<br /><span class="text-danger">' + message +'</li></li>');
					$('#file-error').show();

					break;
			}

			<? } else { ?>

				var message = '<?=$this->translate('GL_DOCUMENT_MAX_FILE_SIZE_EXCEEDED_E')?>';
				var message = message.replace("{FILE_SIZE_IN_KB}", fileSize +' kB');
				var message = message.replace("{MAX_FILE_SIZE}", <?=$maxFileSize?> +' kB');
				$('#file-error').append('<li>'+file.name+'<br /><span class="text-danger">' + message +'</li></li>');
				$('#file-error').show();

			<? } ?>

			continue;
		}

	<? } ?>

		var formData = new FormData();

		var fileName = file.name;

		<?php if (isset($setCustomName) && $setCustomName) { ?>

			var customFileName = $("#customFileName").val();

			formData.append('customFileName', customFileName);

			var ext 	=  file.name.split('.').pop();
			var fileName = customFileName +'.'+ ext;

		<?php } ?>

		var fileName = fileName.replace(/[<>?":|\\/*&']/gi, '');

		formData.append('file', file);

		$('#file-list').append('<li class="input-group" id="file-id-'+ii+'" data-file-name="'+fileName+'">'
 		       + '<div class="form-control">'
 			       + '<i class="file-name-wrap mr-2 ui-icon ui-icon-loading ui-icon-spin" aria-hidden="true"></i>'
 		       + '</div>'
 		       + '<div class="input-group-append">'
 			       + '<button class="btn btn-secondary delete-file" type="button">'
 			       	+ '<i class="ui-icon ui-icon-trash" aria-hidden="true"></i>'
 			       + '</button>'
 		       + '</div>'
 		     + '</li>'
 	     );

		$.ajax({
		       url : '<?=$this->url((isset($uploadUrl) ? $uploadUrl : 'upload_file'))?>?file='+ii,
		       type : 'POST',
		       data : formData,
		       processData: false,  // tell jQuery not to process the data
		       contentType: false,  // tell jQuery not to set contentType
		       success : function(data) {

					var obj = jQuery.parseJSON(JSON.stringify(data));

			        switch(obj.response) {

						case 'error':

							if (obj.hasOwnProperty('errors')) {
								$('#file-error, .file-error').show();
								$("[data-file-name='" + obj.originName + "']").remove();

								var errors = '';

								Object.keys(obj.errors).forEach(function(key) {
									var message = obj.errors[key];
									errors += '<span class="text-danger">'+message+"</span><br>";
								});
								$('#file-error').append('<li>' + obj.originName+'</br>' + errors +'</li>');
							}

						break;

						case 'success':

							$("[data-file-name='" + obj.originName + "']").replaceWith('<li class="input-group" data-uuid="'+obj.uuid+'">'
					    		       + '<div class="form-control">'
				    			       + '<i class="file-name-wrap mr-2 ui-icon ui-icon-processed" aria-hidden="true"></i><span class="word-break">'+obj.originName
				    		       + '</span></div>'
				    		       + '<div class="input-group-append">'
				    			       + '<button class="btn btn-secondary delete-file" title="изтрий" onClick="deleteFile(\''+obj.uuid+'\')" type="button">'
				    			       	+ '<i class="ui-icon ui-icon-trash" aria-hidden="true"></i>'
				    			       + '</button>'
				    		       + '</div>'
				    		     + '</li>')


							$('#files').append($('<option>', {
								value: JSON.stringify(obj),
							    selected: true,
							    text: JSON.stringify(obj),
							    "data-uuid": obj.uuid
							}));

							$("[data-file-name='" + obj.originName + "']" + ' i.file-name-wrap').toggleClass('ui-icon-loading ui-icon-processed').removeClass('ui-icon-spin');
							$("#files").trigger("change");

							<? if (isset($singleFile)) {?>
								toggleUploadFileSection();
							<? } ?>

						break;
		    	   }
		       },
		       error: function(error){

					if (error.status === 413) {

						<? if (isset($uploadUrl) && $uploadUrl == 'upload_video_file') { ?>
							var message = '<?=$this->translate('EP_CMS_VIDEO_MAX_FILE_SIZE_E')?>';
							var message = message.replace("{EP_CMS_VIDEO_MAX_FILE_SIZE}", 30000);
						<? }
						else { ?>
							var message = '<?=$this->translate('GL_DOCUMENT_MAX_FILE_SIZE_EXCEEDED_E')?>';
							var message = message.replace("{FILE_SIZE_IN_KB}", fileSize +' kB');
							var message = message.replace("{MAX_FILE_SIZE}", 30000 +' kB');
						<? } ?>

						$('#file-error, .file-error').show();
						$("[data-file-name='" + fileName + "']").remove();
						$('#file-error').append('<li>'+fileName+'<br /><span class="text-danger">' + message +'</li></li>');
						$('#fileInput').val('');
					}
			   }
		});

		ii++;
	}

	$('#fileInput').val('');
});

function deleteFile(uuid) {
	$('#files option[data-uuid="' + uuid + '"]').remove();
	$("[data-uuid='" + uuid + "']").remove();
	$( "#files" ).trigger("change");
	ajaxRequest("<?=$this->url('delete_tmp_file')?>?fileName="+uuid, false, false);

	if (ii > 1)
		ii--;

	<? if (isset($singleFile)) {?>
		toggleUploadFileSection();
	<? } ?>

	$('#deletedFiles').append($('<option>', {
	    value: uuid,
	    selected: true,
	    text: uuid
	}));
}

function toggleUploadFileSection() {

	var countFiles = $('ul#file-list li').length;

	if (countFiles >= 1) {
		$('.upload-file-section').addClass('d-none');
	}
	else {
		$('.upload-file-section').removeClass('d-none');
	}
}

<? if (isset($singleFile)) {?>
	$(document).ready(function() {
		toggleUploadFileSection();
	});
<? } ?>
</script>