<?= $this->doctype() ?>

<html lang="bg">
    <head>
        <meta charset="utf-8">

        <?= $this->headTitle('GL_PORTAL_EPZEU_ABBR_NAME_L')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')?>

        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])
			->appendStylesheet($this->basePath('css/style.css'))
			->appendStylesheet($this->basePath('css/fonts.css'))
			->appendStylesheet($this->basePath('css/custom.css'))
        ?>

        <?= $this->headScript()
        	->prependFile($this->basePath('js/js.js'))
        	->prependFile($this->basePath('js/bootstrap.bundle.min.js'))
        	->prependFile($this->basePath('js/jquery-3.2.1.min.js'))
        ?>
    </head>

    <body class="bg-white">

		<?php
		$request = new \Zend\Http\PhpEnvironment\Request();
		$menuStateCookie = $request->getCookie() && $request->getCookie()->offsetExists('menu-state') ? $headCookie = $request->getCookie()->offsetGet('menu-state') : '';
		?>
		<!-- <div class="container-fluid" >
		 	<div class="card-body"> -->
			<?=$this->content?>
			<!-- </div>
		</div> -->
		<?= $this->inlineScript() ?>
    </body>
</html>
