<?php
$this->headTitle('EP_TMP_ADD_TEMPLATE_L');
?>
<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="<?=$this->url('home')?>"><?=$this->translate('GL_HOME_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('GL_CONTENT_L')?></li>
		<li class="breadcrumb-item"><a href="<?=$this->url('declaration_template_list')?>"><?=$this->translate('EP_TMP_CONFIG_TEMPLATE_L')?></a></li>
		<li class="breadcrumb-item active" aria-current="page"><?=$this->translate('EP_TMP_ADD_TEMPLATE_L')?></li>
	</ol>
</nav>

<div class="page-title">
	<h2><?=$this->translate('EP_TMP_ADD_TEMPLATE_L')?></h2>
</div>

<div class="card">

	<?php
	$DTForm->setAttribute('action', $this->url('add_declaration_template', ['lang' => $params->fromRoute('lang')]));
	$DTForm->setAttribute('id', 'declaration-template-form');
	$DTForm->prepare();

	echo $this->form()->openTag($DTForm);
	?>

	<div class="card-body">

		<?=$this->partial('partial/messages.phtml')?>

		<div class="row form-group">

			<div class="col-sm-6">
				<?=$this->formRow($DTForm->get('documentTypeId'))?>
			</div>

			<div class="col-sm-6">
				<?=$this->formRow($DTForm->get('activeFields'))?>
			</div>

		</div>

		<div class="row form-group">
			<div class="col-sm-12">
				<?=$this->formRow($DTForm->get('content'))?>

			<? if ($this->FormElementErrors($DTForm->get('content'))) { ?>
				<script>
					CKEDITOR.on('instanceReady', function() {
						$('#cke_content').addClass('input-error');
					});
				</script>
			<? } ?>
			</div>
		</div>



	</div>

	<div class="card-footer">
		<div class="button-bar">
			<a href="<?=$this->url('declaration_template_list', ['lang' => $params->fromRoute('lang')])?>" class="btn btn-secondary"><?=$this->translate('GL_REFUSE_L')?></a>
			<?=$this->formSubmit($DTForm->get('submit'));?>
		</div>
	</div>

	<?=$this->form()->closeTag();?>
</div>

<script>
$(document).on('submit', '#declaration-template-form', function(){
	showGlobalLoader();
});

$(document).ready(function() {

	CKEDITOR.replace('content', {toolbar: 'DeclarationTemplate'});

	$('#documentTypeId').combobox()
});
</script>
<?$this->headScript()->prependFile($this->basePath('js/combobox.js'));?>
<?$this->headScript()->prependFile($this->basePath('js/jquery-ui.js'));?>
<? $this->headScript()->appendFile($this->basePath('js/ckeditor/ckeditor.js'));?>