import * as React from "react";
import { EPZEUBaseComponent } from 'EPZEU.Core'
import { F051_BranchSeat } from '../../Models/Fields/ModelsAutoGenerated'
import { withFieldRecordContainer, FieldContainerProps, AddressUI, ContactsUI } from 'EPZEU.CR.Domain';

class F051_BranchSeatUI extends EPZEUBaseComponent<FieldContainerProps, F051_BranchSeat> {
    constructor(props: FieldContainerProps) {
        super(props);
    }

    renderEdit(): JSX.Element {
        return <>
            <AddressUI {...this.bind(m => m.address)} disabledCountry={true} />
            <ContactsUI {...this.bind(m => m.contacts)} />
        </>
    }

    renderDisplay(): JSX.Element {
        return (
            <>
                <AddressUI {...this.bind(m => m.address)} disabledCountry={true} />
                <ContactsUI {...this.bind(m => m.contacts)} />
            </>);
    }
}

export const F051_BranchSeatFieldUI = withFieldRecordContainer(F051_BranchSeatUI,
    {
        fieldLabelTextKey: "CR_F_51_L",
        isMandatoryField: true
    });