import { ObjectHelper } from "Cnsys.Core";
import { EPZEUBaseComponent } from 'EPZEU.Core';
import { FieldContainerProps, withFieldRecordContainer } from 'EPZEU.CR.Domain';
import * as React from "react";
import { F052_BranchSubjectOfActivity } from '../../Models/Fields/ModelsAutoGenerated';

class F052_BranchSubjectOfActivityUI extends EPZEUBaseComponent<FieldContainerProps, F052_BranchSubjectOfActivity> {

    renderEdit(): JSX.Element {
        return (
            <div className="row">
                <div className="form-group col-12">
                    {this.textAreaFor(x => x.text, null, 3)}
                </div>
            </div>
        );
    }

    renderDisplay(): JSX.Element {
        return (!ObjectHelper.isStringNullOrEmpty(this.model.text) ? <span className="preserve-line-breaks">{this.model.text}</span> : null);
    }
}

export const F052_BranchSubjectOfActivityFieldUI = withFieldRecordContainer(F052_BranchSubjectOfActivityUI, {
    fieldLabelTextKey: "CR_F_52_L",
    fieldLabelFor: (model: F052_BranchSubjectOfActivity) => model.text,
});