import { EPZEUBaseComponent } from 'EPZEU.Core';
import { ApplicationFormContextProps, FieldContainerProps, ProcessStates, withApplicationFormContext, withFieldRecordContainer } from 'EPZEU.CR.Domain';
import * as React from "react";
import { F055_BranchClosure } from '../../Models/Fields/ModelsAutoGenerated';

interface F055_BranchClosureProps extends FieldContainerProps, ApplicationFormContextProps {
}

class F055_BranchClosureUI extends EPZEUBaseComponent<F055_BranchClosureProps, F055_BranchClosure> {

    renderEdit(): JSX.Element {
        return <>
            <div className="row">
                <div className="form-group col-12">
                    <div className="custom-control custom-checkbox">
                        {this.checkBoxFor(x => x.closed, "GL_CLOSED_L",
                            { className: "custom-control-input", disabled: this.props.applicationManager.processState == ProcessStates.ForChange && this.model.initialState.closed === true ? true : false })}
                    </div>
                </div>
            </div>
        </>
    }

    renderDisplay(): JSX.Element {
        return (<>{this.model.closed && this.getResource('GL_OK_L')}</>);
    }
}

export const F055_BranchClosureFieldUI = withFieldRecordContainer(withApplicationFormContext(F055_BranchClosureUI),
    {
        fieldLabelTextKey: "CR_F_55_L",
        fieldLabelFor: (model: F055_BranchClosure) => model.closed
    });