import { ObjectHelper } from "Cnsys.Core";
import { EPZEUBaseComponent } from 'EPZEU.Core';
import { FieldContainerProps, withFieldRecordContainer } from 'EPZEU.CR.Domain';
import * as React from "react";
import { F212_PledgeMoney } from '../../Models/Fields/ModelsAutoGenerated';

class F212_PledgeMoneyUI extends EPZEUBaseComponent<FieldContainerProps, F212_PledgeMoney> {

    renderEdit(): JSX.Element {
        return <div className="row">
            <div className="form-group col-sm-6 col-lg-4">
                {this.labelFor(x => x.price.amount, "CR_APP_SIZE_L")}
                {this.textBoxFor(x => x.price.amount)}
            </div>
            <div className="form-group col-sm-6 col-lg-4">
                {this.labelFor(x => x.price.units, "CR_APP_CURRENCY_L")}
                {this.textBoxFor(x => x.price.units)}
            </div>
        </div>
    }

    renderDisplay(): JSX.Element {
        return (<div>
                {!ObjectHelper.isArrayNullOrEmpty(this.model.price.amount) ? <>{this.model.price.amount}</> : null}&nbsp;
                {!ObjectHelper.isArrayNullOrEmpty(this.model.price.units) ? <>{this.model.price.units}</> : null}
        </div>);
    }
}

export const F212_PledgeMoneyFieldUI = withFieldRecordContainer(F212_PledgeMoneyUI, {
    fieldLabelTextKey: "CR_F_212_L"
});