import * as React from "react";
import { EPZEUBaseComponent, attributesClassFormControlMaxL22, attributesClassFormControlMaxL8, ValidationSummaryStrategy } from 'EPZEU.Core'
import { F219_PledgeExecutionDepozitar } from '../../Models/Fields/ModelsAutoGenerated'
import { withFieldRecordContainer, FieldContainerProps, PersonUI, AddressUI, PersonTypes } from 'EPZEU.CR.Domain';
import { ObjectHelper } from "Cnsys.Core";

class F219_PledgeExecutionDepozitarUI extends EPZEUBaseComponent<FieldContainerProps, F219_PledgeExecutionDepozitar> {

    renderEdit(): JSX.Element {
        return <>
            <PersonUI {...this.bind(x => x.person)} PersonType={PersonTypes.PledgeExecutionDepozitar} />
            <AddressUI {...this.bind(x => x.address)} />
            <div className="row">
                <div className="form-group col-sm-6 col-lg-4">
                    {this.labelFor(x => x.iban, "GL_CR_IBAN_L")}
                    {this.textBoxFor(x => x.iban, attributesClassFormControlMaxL22)}
                </div>
                <div className="form-group col-6 col-md-4 col-lg-2">
                    {this.labelFor(x => x.bic, "GL_CR_BIC_L")}
                    {this.textBoxFor(x => x.bic, attributesClassFormControlMaxL8)}
                </div>
            </div>
        </>
    }

    renderDisplay(): JSX.Element {
        return <>
            <PersonUI {...this.bind(x => x.person)} PersonType={PersonTypes.PledgeExecutionDepozitar} />
            <AddressUI {...this.bind(x => x.address)} />
            {!ObjectHelper.isStringNullOrEmpty(this.model.iban) ? <div>{this.getResource("GL_CR_IBAN_L") + ": " + this.model.iban}</div> : null}
            {!ObjectHelper.isStringNullOrEmpty(this.model.bic) ? <div>{this.getResource("GL_CR_BIC_L") + ": " + this.model.bic}</div> : null}
        </>
    }
}

export const F219_PledgeExecutionDepozitarFieldUI = withFieldRecordContainer(F219_PledgeExecutionDepozitarUI, {
    fieldLabelTextKey: "CR_F_219_L",
    valSummaryRecursive: true,
    valSummaryStrategy: ValidationSummaryStrategy.excludeAllExcept,
    valSummaryPropNames: ["", "person."]
});
