import * as React from "react";
import { EPZEUBaseComponent, ValidationSummaryErrorsPreviewUI, attributesClassFormControlMaxL500 } from 'EPZEU.Core'
import { F308_Interest } from '../../Models/Fields/ModelsAutoGenerated'
import { withFieldRecordContainer, FieldContainerProps } from 'EPZEU.CR.Domain';

class F308_InterestUI extends EPZEUBaseComponent<FieldContainerProps, F308_Interest> {

    constructor(props?: FieldContainerProps) {
        super(props);
    }

    renderEdit(): JSX.Element {
        return (
            <div className="row">
                <div className="form-group col-sm-6 col-lg-4">
                    <div className="form-row">
                        <div className="col">
                            {this.textBoxFor(x => x.text, attributesClassFormControlMaxL500, null)}
                        </div>
                        <div className="col-auto">
                            <div className="col-form-label"> {this.getResource("GL_PERCENT_ABBRAVETION_L")} </div>
                        </div>
                    </div>
                </div>
            </div>
        )
    }

    renderDisplay(): JSX.Element {
        return (<>
            {this.model.text} {this.getResource("GL_PERCENT_ABBRAVETION_L")}
            <ValidationSummaryErrorsPreviewUI errors={this.props.modelReference.getErrors()} />
        </>);
    }
}

export const F308_InterestFieldUI = withFieldRecordContainer(F308_InterestUI, { fieldLabelTextKey: "CR_F_308_L" });