import { withFieldRecordContainer, withTextRecordContainer } from 'EPZEU.CR.Domain';
import { F309_InterestAndDefaultForDelay } from '../../Models/Fields/ModelsAutoGenerated'

export const F309_InterestAndDefaultForDelayFieldUI = withFieldRecordContainer(withTextRecordContainer<F309_InterestAndDefaultForDelay>(), {
    textRecordContainerCss: "form-group col-sm-6 col-lg-4",
    fieldLabelTextKey: "CR_F_309_L",
    fieldLabelFor: (x: F309_InterestAndDefaultForDelay) => x.text,
})