import * as React from "react";
import { EPZEUBaseComponent, attributesClassFormControlMaxL13TextRight } from 'EPZEU.Core'
import { F310_Size310 } from '../../Models/Fields/ModelsAutoGenerated'
import { withFieldRecordContainer, RecordContainerProps } from 'EPZEU.CR.Domain';

class F310_Size310UI extends EPZEUBaseComponent<RecordContainerProps, F310_Size310>{

    renderEdit(): JSX.Element {
        return (<>
            <div className="row">
                <div className="form-group col-sm-6 col-lg-4">
                    {this.labelFor(m => m.price.amount, 'CR_APP_SIZE_L')}
                    {this.textBoxFor(m => m.price.amount, attributesClassFormControlMaxL13TextRight, null)}
                </div>
                <div className="form-group col-sm-6 col-lg-4">
                    {this.labelFor(m => m.price.units, 'CR_APP_CURRENCY_L')}
                    {this.textBoxFor(m => m.price.units)}
                </div>
            </div>
        </>)
    }

    renderDisplay(): JSX.Element {
        return (<>
            {this.model.price.amount && <>{this.model.price.amount + " "}</>}
            {this.model.price.units && <>{this.model.price.units}</>}
        </>);
    }
}


export const F310_Size310FieldUI = withFieldRecordContainer(F310_Size310UI,
    {
        fieldLabelTextKey: "CR_F_310_L"
    });
