import { ObjectHelper } from 'Cnsys.Core';
import { EPZEUBaseComponent, ValidationSummary, ValidationSummaryStrategy } from 'EPZEU.Core';
import { FieldContainerProps, withFieldRecordContainer } from 'EPZEU.CR.Domain';
import { action } from "mobx";
import { observer } from "mobx-react";
import * as React from "react";
import { F311_Description } from '../../Models/Fields/ModelsAutoGenerated';

const valSummaryPropNames = ["wholeCompany"];

@observer class F311_DescriptionUIImpl extends EPZEUBaseComponent<FieldContainerProps, F311_Description> {
    private groupName: string;

    constructor(props?: FieldContainerProps) {
        super(props);

        this.groupName = ObjectHelper.newGuid();
        this.handleChange = this.handleChange.bind(this);
    }

    renderEdit(): JSX.Element {
        let result: any = null;

        if (this.model) {
            result = (
                <>
                    <div className="row">
                        <div className="form-group col-12">
                            <div className="custom-control custom-radio">
                                <input className={"custom-control-input"} type="radio" onChange={this.handleChange} id={this.groupName + '_wholeCompany'} name={this.groupName} value={'wholeCompany'} checked={this.model.wholeCompany} />
                                <label className={"custom-control-label"} htmlFor={this.groupName + '_wholeCompany'}>{this.getResource('CR_APP_ENTERPRISE_AS_WHOLE_L')}</label>
                            </div>
                            <div className="custom-control custom-radio">
                                <input className={"custom-control-input"} type="radio" onChange={this.handleChange} id={this.groupName + '_partOfCompany'} name={this.groupName} value={'partOfCompany'} checked={this.model.partOfCompany} />
                                <label className={"custom-control-label"} htmlFor={this.groupName + '_partOfCompany'}>{this.getResource('CR_APP_PART_ENTERPRISE_L')}</label>
                            </div>
                        </div>
                    </div>
                </>);
        }

        return result;
    }

    renderDisplay(): JSX.Element {
        return <>{this.renderChosenWayOfRepresentation()}</>
    }

    private renderChosenWayOfRepresentation() {
        if (this.model.wholeCompany)
            return this.getResource('CR_APP_ENTERPRISE_AS_WHOLE_L')
        else if (this.model.partOfCompany)
            return this.getResource('CR_APP_PART_ENTERPRISE_L')
        else
            return null;
    }

    @action private handleChange(e: any) {
        if (e.target.value == 'wholeCompany') {
            this.model.wholeCompany = true;
            this.model.partOfCompany = false;
        } else if (e.target.value == 'partOfCompany') {
            this.model.wholeCompany = false;
            this.model.partOfCompany = true;
        }
    }
}

export const F311_DescriptionFieldUI = withFieldRecordContainer(F311_DescriptionUIImpl, { fieldLabelTextKey: "CR_F_311_L", isMandatoryField: true });