import * as React from "react";
import { EPZEUBaseComponent } from 'EPZEU.Core'
import { F314a_PledgedCreditorAgreement2 } from '../../Models/Fields/ModelsAutoGenerated'
import { withFieldRecordContainer, FieldContainerProps } from 'EPZEU.CR.Domain';


class F314a_PledgedCreditorAgreement2UI extends EPZEUBaseComponent<FieldContainerProps, F314a_PledgedCreditorAgreement2 > {

    renderEdit(): JSX.Element {
        return (
            <div className="row">
                    <div className="form-group col-12">
                        <div className="custom-control custom-checkbox">{this.checkBoxFor(x => x.article_8_Para_3_Of_SPA, "CR_APP_00106_L")}</div>
                        <div className="custom-control custom-checkbox">{this.checkBoxFor(x => x.article_21_Para_5_Of_SPA, "CR_APP_00108_L")}</div>
                        <div className="custom-control custom-checkbox">{this.checkBoxFor(x => x.article_32_Para_5_Of_SPA, "CR_APP_00107_L")}</div>
                </div>
        </div>);

    }

    renderDisplay(): JSX.Element {
        return (<div>
            {this.model.article_8_Para_3_Of_SPA ? <div>{this.getResource("CR_APP_00106_L")}</div> : null}
            {this.model.article_21_Para_5_Of_SPA ? <div>{this.getResource("CR_APP_00108_L")}</div> : null}
            {this.model.article_32_Para_5_Of_SPA ? <div>{this.getResource("CR_APP_00107_L")}</div> : null}
        </div>);
    }
}

export const F314a_PledgedCreditorAgreement2FieldUI = withFieldRecordContainer(F314a_PledgedCreditorAgreement2UI, {
    fieldLabelTextKey: "CR_F_314a_L"
});
