import { EPZEUBaseComponent } from 'EPZEU.Core';
import { FieldContainerProps, withFieldRecordContainer } from 'EPZEU.CR.Domain';
import { observer } from 'mobx-react';
import * as React from "react";
import { F404_Size404 } from '../../Models/Fields/ModelsAutoGenerated';
import { ObjectHelper } from 'Cnsys.Core';

@observer class F404_Size404UI extends EPZEUBaseComponent<FieldContainerProps, F404_Size404> {

    constructor(props: FieldContainerProps) {
        super(props);
    }

    renderEdit(): JSX.Element {
        return (
            <div className='row'>
                <div className='form-group col-sm-6 col-lg-4'>
                    {this.labelFor(m => m.price.amount, 'CR_APP_SIZE_L')}
                    {this.textBoxFor(m => m.price.amount)}
                </div>
                <div className='form-group col-sm-6 col-lg-4'>
                    {this.labelFor(m => m.price.units, 'CR_APP_CURRENCY_L')}
                    {this.textBoxFor(m => m.price.units)}
                </div>
            </div>
        );
    }

    renderDisplay(): JSX.Element {
        return (
            <>
                {this.model.price.amount} {!ObjectHelper.isStringNullOrEmpty(this.model.price.amount) && this.model.price.units}
            </>
        );
    }
}

export const F404_Size404FieldUI = withFieldRecordContainer(F404_Size404UI, {
    fieldLabelTextKey: "CR_F_404_L",
    isMandatoryField: true,
});