import { EPZEUBaseComponent } from 'EPZEU.Core';
import { FieldContainerProps, withFieldRecordContainer } from 'EPZEU.CR.Domain';
import { observer } from 'mobx-react';
import * as React from "react";
import { F404a_MoratoryRate } from '../../Models/Fields/ModelsAutoGenerated';
import { ObjectHelper } from 'Cnsys.Core';

@observer class F404a_MoratoryRateUI extends EPZEUBaseComponent<FieldContainerProps, F404a_MoratoryRate> {

    renderEdit(): JSX.Element {
        return (
            <div className='row'>
                <div className='form-group col-sm-6 col-lg-4'>
                    {this.labelFor(m => m.price.amount, 'CR_APP_SIZE_L')}
                    {this.textBoxFor(m => m.price.amount)}
                </div>
                <div className='form-group col-sm-6 col-lg-4'>
                    {this.labelFor(m => m.price.units, 'CR_APP_CURRENCY_L')}
                    {this.textBoxFor(m => m.price.units)}
                </div>
                <div className='form-group col-sm-12 col-lg-4'>
                    {this.labelFor(m => m.date, 'CR_APP_CALCULATED_DATE_L')}
                    {this.dateFor(m => m.date)}
                </div>
            </div>
        );
    }

    renderDisplay(): JSX.Element {
        return (
            <>
                {this.model.price.amount} {!ObjectHelper.isStringNullOrEmpty(this.model.price.amount) && this.model.price.units}
                {(this.model.price.amount && this.model.date) && <>, {this.getResource('CR_APP_CALCULATED_DATE_L')}: {this.dateDisplayFor(this.model.date, null, this.getResource('GL_YEAR_ABBREVIATION_L'))}</>}
            </>
        );
    }
}

export const F404a_MoratoryRateFieldUI = withFieldRecordContainer(F404a_MoratoryRateUI, {
    fieldLabelTextKey: "CR_F_404a_L"
});