import * as React from 'react';
import { EPZEUBaseComponent } from 'EPZEU.Core';
import { FieldContainerProps, withFieldRecordContainer } from 'EPZEU.CR.Domain';
import { F53702_OffshoreDirectControlCompanyLegalForm } from '../../Models/Fields/ModelsAutoGenerated';
import { ObjectHelper } from 'Cnsys.Core';

class F53702_OffshoreDirectControlCompanyLegalFormUIImpl extends EPZEUBaseComponent<FieldContainerProps, F53702_OffshoreDirectControlCompanyLegalForm> {

    renderEdit(): JSX.Element {
        return <>
            <div className="row">
                <div className="form-group col-12">
                    <label>{this.getResource("GL_LEGAL_FORM_L")}</label>
                    {this.textBoxFor(x => x.dcLegalForm)}
                </div>
            </div>
        </>
    }

    renderDisplay(): JSX.Element {

        if (!ObjectHelper.isStringNullOrEmpty(this.model.dcLegalForm))
            return <>{`${this.getResource("GL_LEGAL_FORM_L")}: ${this.model.dcLegalForm}`}</>

        return null;
    }
}

export const F53702_OffshoreDirectControlCompanyLegalFormFieldUI = withFieldRecordContainer(F53702_OffshoreDirectControlCompanyLegalFormUIImpl, {
    fieldLabelFor: (model: F53702_OffshoreDirectControlCompanyLegalForm) => model.dcLegalForm
});