import * as React from "react";
import { EPZEUBaseComponent } from 'EPZEU.Core'
import { F53805_OffshoreNoDirectControlCompanyAddress } from '../../Models/Fields/ModelsAutoGenerated'
import { withFieldRecordContainer, FieldContainerProps, SectionInfoUI, AddressUI, ContactsUI } from 'EPZEU.CR.Domain';

class F53805_OffshoreNoDirectControlCompanyAddressUI extends EPZEUBaseComponent<FieldContainerProps, F53805_OffshoreNoDirectControlCompanyAddress> {

    renderEdit(): JSX.Element {
        return (<>
                <div className="row">
                    <div className="form-group col">
                        <AddressUI {...this.bind(m => m.address)} />
                        <ContactsUI {...this.bind(m => m.contacts)} />
                    </div>
                </div>
        </>)
    }

    renderDisplay(): JSX.Element {
        return (<>
            <AddressUI {...this.bind(m => m.address)} />
            <ContactsUI {...this.bind(m => m.contacts)} />
        </>
        );
    }
}

export const F53805_OffshoreNoDirectControlCompanyAddressFieldUI = withFieldRecordContainer(F53805_OffshoreNoDirectControlCompanyAddressUI, {
});