import * as React from 'react';
import { EPZEUBaseComponent } from 'EPZEU.Core';
import { withFieldRecordContainer, FieldContainerProps } from 'EPZEU.CR.Domain';
import { F5380_OffshoreNoDirectControlCompany } from '../../Models/Fields/ModelsAutoGenerated';
import { ObjectHelper } from 'Cnsys.Core';

class F5380_OffshoreNoDirectControlCompanyUIImpl extends EPZEUBaseComponent<FieldContainerProps, F5380_OffshoreNoDirectControlCompany> {

    renderEdit(): JSX.Element {
        return <>
            <div className="row">
                <div className="form-group col-12">
                    <label>{this.getResource("CR_GL_COMPANY_NAME_L")}</label>
                    {this.textBoxFor(x => x.name)}
                </div>
            </div>
        </>;
    }

    renderDisplay(): JSX.Element {

        if (!ObjectHelper.isStringNullOrEmpty(this.model.name))
            return <>{`${this.getResource("CR_GL_COMPANY_NAME_L")}: ${this.model.name}`}</>

        return null;
    }
}

export const F5380_OffshoreNoDirectControlCompanyFieldUI = withFieldRecordContainer(F5380_OffshoreNoDirectControlCompanyUIImpl, {
    fieldLabelFor: (model: F5380_OffshoreNoDirectControlCompany) => model.name
});
