import { EPZEUBaseComponent } from 'EPZEU.Core';
import { ApplicationFormContextProps, FieldContainerProps, ProcessStates, withApplicationFormContext, withFieldRecordContainer } from 'EPZEU.CR.Domain';
import * as React from "react";
import { F551_EraseActualOwner } from '../../Models/Fields/ModelsAutoGenerated';

interface F551_EraseActualOwnerProps extends FieldContainerProps, ApplicationFormContextProps {
}

class F551_EraseActualOwnerUI extends EPZEUBaseComponent<F551_EraseActualOwnerProps, F551_EraseActualOwner> {

    renderEdit(): JSX.Element {
        return <>
            <div className="row">
                <div className="form-group col">
                    <div className="custom-control custom-checkbox">
                        {this.checkBoxFor(x => x.cheked, "GL_EFFACEMENT_L",
                            { className: "custom-control-input", disabled: this.props.applicationManager.processState == ProcessStates.ForChange && this.model.initialState.cheked === true ? true : false })}
                    </div>
                </div>
            </div>
        </>
    }

    renderDisplay(): JSX.Element {
        return (<>{
            this.model.cheked && this.getResource('GL_OK_L')}</>);
    }
}

export const F551_EraseActualOwnerFieldUI = withFieldRecordContainer(withApplicationFormContext(F551_EraseActualOwnerUI), {
    fieldLabelTextKey: "CR_F_551_L",
    fieldLabelFor: (model: F551_EraseActualOwner) => model.cheked
});