//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.20 at 02:18:31 PM EET 
//


package bg.registryagency.epzeu.pr.application.segment;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Данни за имот
 * 
 * <p>Java class for Property complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Property"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Type" type="{PropertyType}PropertyType"/&gt;
 *         &lt;element name="Settlement" type="{PlaceNomenclature}PlaceNomenclature"/&gt;
 *         &lt;element name="Municipality" type="{PlaceNomenclature}PlaceNomenclature"/&gt;
 *         &lt;element name="Area" type="{PlaceNomenclature}PlaceNomenclature"/&gt;
 *         &lt;element name="CountrySide" type="{CountrySide}CountrySide" minOccurs="0"/&gt;
 *         &lt;element name="CadastralId" type="{CadastralId}CadastralId" minOccurs="0"/&gt;
 *         &lt;element name="AccountNumber" type="{AccountNumber}AccountNumber" minOccurs="0"/&gt;
 *         &lt;element name="OldAccountNumber" type="{AccountNumber}AccountNumber" minOccurs="0"/&gt;
 *         &lt;element name="AreaByDocuments" type="{AreaByDocuments}AreaByDocuments"/&gt;
 *         &lt;element name="PropertyLimits" type="{PropertyLimits}PropertyLimits" minOccurs="0"/&gt;
 *         &lt;element name="PropertyRemark" type="{PropertyRemark}PropertyRemark" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@Getter
@Setter
@NoArgsConstructor
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Property", propOrder = {
    "type",
    "settlement",
    "municipality",
    "area",
    "countrySide",
    "cadastralId",
    "accountNumber",
    "oldAccountNumber",
    "areaByDocuments",
    "propertyLimits",
    "propertyRemark"
})
public class Property {

    @XmlElement(name = "Type", required = true)
    protected PropertyType type;
    /** Населено място */
    @XmlElement(name = "Settlement", required = true)
    protected PlaceNomenclaturePr settlement;
    /** Община */
    @XmlElement(name = "Municipality", required = true)
    protected PlaceNomenclaturePr municipality;
    /** Област */
    @XmlElement(name = "Area", required = true)
    protected PlaceNomenclaturePr area;
    @XmlElement(name = "CountrySide")
    protected String countrySide;
    @XmlElement(name = "CadastralId")
    protected String cadastralId;
    @XmlElement(name = "AccountNumber")
    protected String accountNumber;
    @XmlElement(name = "OldAccountNumber")
    protected String oldAccountNumber;
    @XmlElement(name = "AreaByDocuments", required = true)
    protected Float areaByDocuments;
    @XmlElement(name = "PropertyLimits")
    protected String propertyLimits;
    @XmlElement(name = "PropertyRemark")
    protected String propertyRemark;

}
