<? $this->headTitle($this->getTitleI18n('bank-account-'.$register)) ?>

<div class="page-header-wrapper">
	<div class="breadcrumbs">
		<div class="fixed-content-width">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="<?=$this->url('home', ['lang' => $this->language()->getCurrentLang()])?>"><?=$this->translate('GL_HOME_L')?></a></li>

					<? if ($register == 'cr') { ?>
						<li class="breadcrumb-item">
						<a href="<?=$this->url('commercial_register', ['lang' => $this->language()->getCurrentLang()])?>">
							<?=$this->translate('GL_CR_REG_NAME_L_SHORT_L')?>
						</a>
						</li>
					<? } else { ?>
						<li class="breadcrumb-item">

						<a href="<?=$this->url('property_register', ['lang' => $this->language()->getCurrentLang()])?>">
							<?=$this->translate('GL_PR_REG_NAME_L')?>
						</a>

						</li>
					<? } ?>
					<li class="breadcrumb-item active" aria-current="page"><?=$this->getTitleI18n('bank-account-'.$register)?></li>
				</ol>
			</nav>
		</div>
	</div>

	<div class="section-wrapper">
		<div class="fixed-content-width">
			<div class="page-header">
				<div class="row">
					<div class="col">
						<h1 class="page-title"><?=$this->getTitleI18n('bank-account-'.$register)?></h1>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="main-wrapper" class="main-wrapper">
	<div class="page-wrapper">
		<div class="section-wrapper section-wrapper--margins">
			<div class="fixed-content-width">
				<div class="card card-page">
					<div class="card-body card-page__body">
						<div class="row">
							<div class="col-sm-6">
								<?=$bankAccountObj->getContent()?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>