<?
echo $this->doctype();
$currentLang = $this->language()->getCurrentLang();
$currentLang = $currentLang == 'bg' ? null : $currentLang;
$defaultLang = $this->language()->getCurrentLang(true);
$routeName = isset($routeName) ? $routeName : '';
$registerType = isset($registerType) ? $registerType : null;
$cookieDomain = isset($cookieDomain) ? $cookieDomain : null;

$version = isset($version) ? $version : null;
?>

<html lang="<?=$defaultLang?>">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->translate('GL_PORTAL_EPZEU_ABBR_NAME_L'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')->setAutoEscape(false)?>

        <?=
        	$this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])
			->appendStylesheet($this->basePath('css/style.css'))
			->appendStylesheet($this->basePath('css/fonts.css'))
			->appendStylesheet($this->basePath('css/custom.css'))->setAutoEscape(false)
        ?>

        <?= $this->headScript()
        	->prependFile($this->basePath('js/js.js?v=1'))
        	->prependFile($this->basePath('js/bootstrap.bundle.min.js'))
        	->prependFile($this->basePath('js/scrolltotop.js'))
        	->prependFile($this->basePath('js/jquery-3.2.1.min.js'))->setAutoEscape(false)
        ?>
    </head>
    <body>

    <div class="layout-wrapper">

		<?
   		$staticPageList = $this->staticPage()->getPageList($currentLang);
    	?>

    	<div id="header-wrapper" class="header-wrapper">
			<header class="header">
	            <div class="row header-container fixed-content-width">
	                <div class="col-auto">
	                    <a href="<?=$this->url('home', ['lang' => $currentLang])?>"><img class="registryagency-text d-none d-lg-inline-block" src="<?=$this->basePath($currentLang == 'en' ? 'images/registryagency-text-en.svg' : 'images/registryagency-text.svg')?>"></a><a href="<?=$this->url('home', ['lang' => $currentLang])?>"><img class="registryagency-logo" src="<?=$this->basePath('images/registryagency-logo.svg')?>"></a><div class="divider d-none d-sm-inline-block"></div>
	                </div>

					<?
					if (@$routeName == 'integration_container') { // контейнер за интеграция на регистри
						?>
						<div class="col header-title header-title--register">
				        	<h1 nav_key="title"></h1>
				        	<p><?=$this->translate('GL_PORTAL_EPZEU_FULL_NAME_L')?></p>
				        </div>
						<?
					}

					else {
						switch (strtoupper($registerType)) {
							case 'PR':
									?>
									<div class="col header-title header-title--register">
					                    <h1><?=$this->translate('GL_PR_REG_NAME_L')?></h1>
					                    <p><?=$this->translate('GL_PORTAL_EPZEU_FULL_NAME_L')?></p>
					                </div>
									<?

									break;
							case 'CR':
									?>
									<div class="col header-title header-title--register">
					                    <h1 class="d-none d-md-block"><?=$this->translate('GL_CR_REG_NAME_L')?></h1>
					                    <h1 class="d-md-none"><?=$this->translate('GL_CR_REG_NAME_L_SHORT_L')?></h1>
					                    <p><?=$this->translate('GL_PORTAL_EPZEU_FULL_NAME_L')?></p>
					                </div>
									<?
									break;

							default:
									?>
									<div class="col header-title">
										<h1><?=$this->translate('GL_PORTAL_EPZEU_FULL_NAME_L')?></h1>
									</div>
									<?
									break;
							}
					}
					?>
	            </div>

	        	<div class="brand-line brand-line--header"></div>
			</header>

			<nav class="navbar-top">
	            <div class="fixed-content-width">
	                <div class="navbar-top-container">

						<?=$this->partial('partial\menu', ['routeName' => $routeName, 'currentLang' => $currentLang, 'staticPageList' => $staticPageList, 'params' => isset($params) ? $params: [] ])?>

	                    <ul class="navbar-top-container-right">

							<li class="navbar-top-search">
								<?
								$searchForm = $this->searchFormHelper();
								$searchForm->setAttribute('action', $this->url('search', ['lang' => $currentLang]));
								$searchForm->prepare();

								echo $this->form()->openTag($searchForm);
								?>

								<div class="navbar-top-item">
									<div class="navbar-top-item-text navbar-top-item-icon">

										<?=$this->formElement($searchForm->get('sKey'))?>
										<a href="javascript://" title="<?=$this->translate('GL_SEARCH_L')?>" onclick="$(this).closest('form').submit();">
											<i class="ui-icon ui-icon-search-top" aria-hidden="true"></i>
										</a>
									</div>
								</div>

								<?=$this->form()->closeTag();?>
							</li>

							<li class="dropdown position-static show">
								<a class="navbar-top-item" href="#" role="button" data-boundary="window" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Език">
									<div class="navbar-top-item-text navbar-top-item-icon dropdown-toggle">
										<i class="ui-icon ui-icon-globe-top" aria-hidden="true"></i><?=$defaultLang?>
									</div>
								</a>
								<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
									<div class="dropdown-menu--scrollable">
									<? foreach ($this->language()->renderLanguagesMenu() as $menuLang)
										echo $menuLang;
									?>
									</div>
								</div>
							</li>

							<li class="navbar-top-font-size">
								<div class="navbar-top-item">
									<div class="navbar-top-item-text navbar-top-item-icon">
										<a href="javascript:setFontSize(-1, '<?=$cookieDomain?>');" title="<?=$this->translate('GL_DECREASE_FONT_SIZE_L')?>"><i class="ui-icon ui-icon-font-size-minus" aria-hidden="true"></i></a><a href="javascript:setFontSize(0, '<?=$cookieDomain?>');"  title="<?=$this->translate('GL_NORMAL_FONT_L')?>"><i class="ui-icon ui-icon-font-size" aria-hidden="true"></i></a><a href="javascript:setFontSize(1, '<?=$cookieDomain?>');" title="<?=$this->translate('GL_INCREASE_FONT_SIZE_L')?>"><i class="ui-icon ui-icon-font-size-plus" aria-hidden="true"></i></a>
									</div>
								</div>
							</li>

	                   	</ul>
	                </div>
	            </div>


				<div class="navbar-top-subnav collapse">
					<div class="fixed-content-width">
						<div class="navbar-top-subnav-container">
							<ul id="cr-navbar-top-subnav">
								<li>
									<a class="navbar-top-subnav-item <?=$routeName == 'commercial_register' ? 'active' : '' ?>" href="<?=$this->url('commercial_register', ['lang' => $currentLang])?>">
										<h3 class="navbar-top-subnav-title"><?=$this->translate('GL_CR_REG_NAME_L_SHORT_L')?></h3>
									</a>
								</li>
								<li>
									<? if (isset($staticPageList['CR_SERVICES']) && $urlObj = $staticPageList['CR_SERVICES']) { ?>
									<a class="navbar-top-subnav-item" href="<?=$urlObj->url ?>" nav_key="cr_services"><?=$this->translate($urlObj->labelKey)?></a>
									<? } ?>
								</li>
								<li>
									<? if (isset($staticPageList['CR_APPLICATIONS']) && $urlObj = $staticPageList['CR_APPLICATIONS']) { ?>
									<a class="navbar-top-subnav-item" href="<?=$urlObj->url?>" nav_key="cr_applications">
										<?=$this->translate($urlObj->labelKey)?>
									</a>
									<? } ?>
								</li>
								<li><a class="navbar-top-subnav-item <?=($routeName == 'legislation' && $params['registerType'] == 'cr') ? 'active' : '' ?>" href="<?=$this->url('legislation', ['lang' => $currentLang, 'registerType' => 'cr'])?>"><?=$this->translate('EP_LEGISLATION_L')?></a></li>
								<li><a class="navbar-top-subnav-item <?=($routeName == 'document_template' && $params['registerType'] == 'cr') ? 'active' : '' ?>" href="<?=$this->url('document_template', ['lang' => $currentLang, 'registerType' => 'cr'])?>"><?=$this->translate('EP_DOCUMENTS_L')?></a></li>
								<li>
									<? if (isset($staticPageList['CR_REPORTS']) && $urlObj = $staticPageList['CR_REPORTS']) { ?>
									<a class="navbar-top-subnav-item" href="<?=$urlObj->url?>" nav_key="cr_reports">
										<?=$this->translate($urlObj->labelKey)?>
									</a>
									<? } ?>
								</li>
								<li><a class="navbar-top-subnav-item <?=($routeName == 'video_lesson_list' && $params['registerType'] == 'cr') ? 'active' : '' ?>" href="<?=$this->url('video_lesson_list', ['lang' => $currentLang, 'registerType' => 'cr'])?>"><?=$this->translate('EP_VIDEOS_L')?></a></li>
								<li><a class="navbar-top-subnav-item <?=($routeName == 'statistic' && $params['registerType'] == 'cr') ? 'active' : '' ?>" href="<?=$this->url('statistic', ['lang' => $currentLang, 'registerType' => 'cr'])?>"><?=$this->translate('EP_STATISTICS_L')?></a></li>
							</ul>
						</div>
						<div class="navbar-top-subnav-divider"></div>
						<div class="navbar-top-subnav-container">
	                            <ul id="pr-navbar-top-subnav">
									<li>
										<a class="navbar-top-subnav-item <?=$routeName == 'property_register' ? 'active' : '' ?>" href="<?=$this->url('property_register', ['lang' => $currentLang])?>">
											<h3 class="navbar-top-subnav-title"><?=$this->translate('GL_PR_REG_NAME_L')?></h3>
										</a>
									</li>
									<li>
									<? if (isset($staticPageList['PR_SERVICES']) && $urlObj = $staticPageList['PR_SERVICES']) { ?>
										<a class="navbar-top-subnav-item" href="<?=$urlObj->url ?>" nav_key="pr_services">
											<?=$this->translate($urlObj->labelKey)?>
										</a>
									<? } ?>
									</li>
									<li>
										<? if (isset($staticPageList['PR_APPLICATIONS']) && $urlObj = $staticPageList['PR_APPLICATIONS']) { ?>
										<a class="navbar-top-subnav-item" href="<?=$urlObj->url?>" nav_key="pr_applications">
											<?=$this->translate($urlObj->labelKey)?>
										</a>
										<? } ?>
									</li>

									<li><a class="navbar-top-subnav-item <?=($routeName == 'legislation' && $params['registerType'] == 'pr') ? 'active' : '' ?>" href="<?=$this->url('legislation', ['lang' => $currentLang, 'registerType' => 'pr'])?>"><?=$this->translate('EP_LEGISLATION_L')?></a></li>
									<li><a class="navbar-top-subnav-item <?=($routeName == 'document_template' && $params['registerType'] == 'pr') ? 'active' : '' ?>" href="<?=$this->url('document_template', ['lang' => $currentLang, 'registerType' => 'pr'])?>"><?=$this->translate('EP_DOCUMENTS_L')?></a></li>

									<li>
										<? if (isset($staticPageList['PR_REPORTS']) && $urlObj = $staticPageList['PR_REPORTS']) {?>
										<a class="navbar-top-subnav-item" href="<?=$urlObj->url?>" nav_key="pr_reports">
											<?=$this->translate($urlObj->labelKey)?>
										</a>
										<? } ?>

									</li>

									<li><a class="navbar-top-subnav-item <?=($routeName == 'video_lesson_list' && $params['registerType'] == 'pr') ? 'active' : '' ?>" href="<?=$this->url('video_lesson_list', ['lang' => $currentLang, 'registerType' => 'pr'])?>"><?=$this->translate('EP_VIDEOS_L')?></a></li>
									<? if (isset($staticPageList['PR_STATE_FEE_CALCULATOR']) && $urlObj = $staticPageList['PR_STATE_FEE_CALCULATOR']) {?>
									<li>
										<a class="navbar-top-subnav-item" href="<?=$this->translate($urlObj->url)?>" nav_key="pr_calculator">
										<?=$this->translate($urlObj->labelKey)?>
										</a>
									</li>
									<? } ?>
									<li><a class="navbar-top-subnav-item <?=($routeName == 'statistic' && $params['registerType'] == 'pr') ? 'active' : '' ?>" href="<?=$this->url('statistic', ['lang' => $currentLang, 'registerType' => 'pr'])?>"><?=$this->translate('EP_STATISTICS_L')?></a></li>
	                            </ul>
						</div>

						<div class="navbar-top-subnav-close d-none d-lg-block">
                            <button type="button" class="close" aria-label="Close" onclick="toggleSubnav()">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
					</div>
				</div>
	        </nav>
        </div>

		<div class="content-wrapper" id="content-wrapper">
			<?=$this->content?>
		</div>

		<? if (!$footer = $this->winCache()->getItem('footer-'.$defaultLang)) {
			$cacheOptions = $this->winCache()->getOptions();
			$oldTtl = $cacheOptions->getTtl();
			$cacheOptions->setTtl(30);
			$footer = $this->partial('partial\footer.phtml', ['staticPageList' => $staticPageList, 'currentLang' => $currentLang, 'version' => $version]);
			$this->winCache()->setItem('footer-'.$defaultLang, $footer);
			$cacheOptions->setTtl($oldTtl);
		 } ?>

		<?=$footer?>


	</div>
	<?= $this->inlineScript() ?>

	<? if ($this->identity()) { ?>

		<? if ($cookieDomain) {
			$dateInterval = \Application\Service\AppService::fromPg($idle);
			$idle = \Application\Service\AppService::dateIntervalToSeconds($dateInterval);
			$idleLoguotUrl = $this->url('idle_logout', ['lang' => $currentLang]);
			?>

			<script>
			$(document).ready(function () {
				if (typeof idleLogout !== "undefined") {
					idleLogout('<?=$idle?>', '<?=$idleLoguotUrl?>', '<?=$cookieDomain?>');
				}
			});
			</script>
		<? } ?>

	<? } ?>

	<div id="scrollToTopLabel" style="display:none;"><?=$this->translate('GL_SCROLL_TO_TOP_L')?></div>

	<aside id="cookieInfo" class="cookie-info d-none">
		<div class="fixed-content-width">
			<p><?=str_replace('{LINK_COOKIES}', '<a href="'.$this->url('redefined_page', ['lang' => $currentLang, 'url' => 'cookies']).'" class="text-white"><b>'.$this->getTitleI18n('cookies').'</b></a>', $this->translate('GL_COOKIES_I')) ?></p>
			<div class="button-bar">
				<div class="left-side">
				</div>
				<div class="right-side">
					<button type="button" onclick="setCookiePrivacyAccept('<?=$cookieDomain?>');" class="btn btn-outline-light text-info"><?=$this->translate('GL_ACCEPT_COOKIES_L')?></button>
				</div>
			</div>
		</div>
	</aside>

    </body>
</html>