import { ObjectHelper } from 'Cnsys.Core';
import { EPZEUBaseValidator } from 'EPZEU.Core';
import { IApplicationFormValidationContext } from 'EPZEU.CR.Domain';
import { F7040_Branch704Subject, F704_Branches704 } from '../ModelsAutoGenerated';
import { F704_BranchSubjectValidator } from './F704_BranchSubjectValidator';

export class F704_BranchesValidator extends EPZEUBaseValidator<F704_Branches704, IApplicationFormValidationContext> {
    constructor() {
        super();

        this.ruleFor(m => m.branchList).setCollectionValidator(new F704_BranchSubjectValidator());
    }

    public validate(obj: F704_Branches704): boolean {
        let isValid = super.validate(obj);
        var branchesCodes: string[] = [];

        for (var i = 0; i < obj.branchList.length; i++) {
            let record = obj.branchList[i];

            if (this.isBranchItemEmpty(record) && (obj.branchList.length > 1)) {
                record.clearErrors();
                record.addError(this.getMessage('CR_APP_00063_E')); //Попълнете данните за полето или го изтрийте.
                isValid = false;
            } else {

                for (var currentBranch of obj.branchList[i].branches) {

                    if ((ObjectHelper.isStringNullOrEmpty(currentBranch.branchCode)) || (branchesCodes.filter(x => x == currentBranch.branchCode).length == 0))
                        branchesCodes.push(currentBranch.branchCode)
                    else {
                        currentBranch.addError(this.getMessage("CR_APP_00148_E")); // Този клон вече е посочен.
                        isValid = false;
                    }
                }
            }
        }

        return isValid;
    }

    private isBranchItemEmpty(branchItem: F7040_Branch704Subject) {
        if (branchItem.branchSubject.name || branchItem.branchSubject.indent)
            return false;

        for (var i = 0; i < branchItem.branches.length; i++) {

            if (!ObjectHelper.isStringNullOrEmpty(branchItem.branches[i].branchCode) ||
                !ObjectHelper.isStringNullOrEmpty(branchItem.branches[i].firmName)) {
                return false;
            }
        }

        return true;
    }
}