import { RecordValidator } from 'EPZEU.CR.Domain';
import { F801_FormOfTransforming801 } from '../ModelsAutoGenerated';

export class F801_FormOfTransformingValidator extends RecordValidator<F801_FormOfTransforming801> {
    constructor() {
        super();

        // задължително е да се избере форма на преобразуване
        this.ruleFor(m => m.separation).must(m => { return m.separation == true })
            .when(m => !(m.division
                || m.fusion
                || m.influx))
            .withMessage(this.getMessage('GL_INPUT_FIELD_MUST_E'));
    }

    public validateInternal(obj: F801_FormOfTransforming801): boolean {
        let isValid = super.validateInternal(obj);

        return isValid;
    }
}